import type {
  Product,
  Confectioner,
  Courier,
  Supplier,
  SupplierProduct,
  Order,
  ChatRoom,
  ChatMessage,
  ChannelPost,
  ChannelStory,
  ChannelFollower,
  User,
} from "./types";

// ===== ПОЛЬЗОВАТЕЛИ (для авторизации) =====
export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: "u1",
    email: "customer@demo.ru",
    password: "demo123",
    name: "Анна Соколова",
    phone: "+7 916 123-45-67",
    roles: ["CUSTOMER"],
    createdAt: "2025-03-12",
    city: "Москва",
    loyaltyLevel: "GOLD",
    bonusBalance: 1240,
    avatar: "https://i.pravatar.cc/150?img=47",
  },
  {
    id: "u2",
    email: "confectioner@demo.ru",
    password: "demo123",
    name: "Мария Уездная",
    phone: "+7 905 222-33-44",
    roles: ["CONFECTIONER", "CUSTOMER"],
    createdAt: "2024-11-04",
    city: "Тула",
    avatar: "https://i.pravatar.cc/150?img=32",
  },
  {
    id: "u3",
    email: "supplier@demo.ru",
    password: "demo123",
    name: "Андрей Поляков",
    phone: "+7 903 555-66-77",
    roles: ["SUPPLIER"],
    createdAt: "2024-08-20",
    city: "Москва",
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    id: "u4",
    email: "courier@demo.ru",
    password: "demo123",
    name: "Иван Курьеров",
    phone: "+7 926 888-99-00",
    roles: ["COURIER"],
    createdAt: "2025-01-15",
    city: "Москва",
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    id: "u5",
    email: "admin@demo.ru",
    password: "admin123",
    name: "Администратор Платформы",
    phone: "+7 495 000-00-01",
    roles: ["ADMIN", "SUPER_ADMIN"],
    createdAt: "2024-01-01",
    city: "Москва",
    avatar: "https://i.pravatar.cc/150?img=68",
  },
];

// ===== КОНДИТЕРЫ =====
export const MOCK_CONFECTIONERS: Confectioner[] = [
  // ===== ОСНОВНОЙ КОНДИТЕР (РЕАЛЬНЫЙ) =====
  {
    id: "c0",
    userId: "u0",
    businessName: "Торты на заказ | Сахарная печать",
    slug: "torty-na-zakaz-saharnaya-pechat",
    description:
      "Домашняя кондитерская из Волоколамска. Специализируюсь на тортах для свадеб, крестин и других праздников. Уникальная услуга — сахарная печать: нанесение любого изображения на торт с помощью съедобной бумаги и пищевых чернил. Каждый торт — индивидуальный подход, натуральные ингредиенты, ручная работа. Принимаю заказы на торты любой сложности.",
    avatar: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400",
    cover: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=1200",
    location: {
      country: "Россия",
      region: "Московская область",
      city: "Волоколамск",
      district: "Центральный",
      street: "ул. Революционная",
      house: "",
      apartment: "",
      postalCode: "143600",
      lat: 56.9555,
      lng: 35.9567,
      serviceRadiusKm: 50,
      deliveryCities: ["Волоколамск", "Москва", "Можайск", "Клин", "Истра", "Руза"],
    },
    city: "Волоколамск",
    rating: 5.0,
    reviewsCount: 1,
    ordersCount: 1,
    verified: true,
    trustLevel: "TRUSTED",
    tariff: "PREMIUM",
    legalInfo: {
      status: "NPD",
      inn: "",
      npdRegisteredAt: "2024-01-01",
      documentsVerified: true,
      verifiedAt: "2024-01-15",
    },
    taxMode: "NPD",
    specialization: ["Свадебные торты", "Торты на крестины", "Сахарная печать", "Праздничные торты", "Торты с фото"],
    portfolioImages: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=600",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
    ],
    followersCount: 1,
    responseTime: "обычно отвечает в течение часа",
    joinedAt: "2024-01-10",
    selfPickup: true,
    deliveryOptions: ["own", "courier", "pickup_point"],
    paymentSettings: {
      acceptCard: true,
      acceptSbp: true,
      acceptCash: true,
      acceptSplit: true,
      acceptInstallment: false,
      installmentMinAmount: 0,
      installmentProviders: [],
      installmentPlans: [],
    },
    balance: 0,
    totalEarnings: 0,
    monthlyEarnings: 0,
  },
  {
    id: "c1",
    userId: "u2",
    businessName: "Сладкая уездная",
    slug: "sladkaya-uezdnaya",
    description:
      "Домашняя кондитерская из Тулы. Специализируемся на бисквитных тортах, медовиках и авторских десертах. Все изделия — из натуральных ингредиентов, без маргарина и консервантов. Работаем с 2019 года, более 1200 испечённых тортов.",
    avatar: "https://i.pravatar.cc/150?img=32",
    cover: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=1200",
    location: {
      country: "Россия",
      region: "Тульская область",
      city: "Тула",
      district: "Центральный",
      street: "ул. Первомайская",
      house: "12",
      apartment: "5",
      postalCode: "300000",
      lat: 54.1961,
      lng: 37.6182,
      serviceRadiusKm: 25,
      deliveryCities: ["Тула", "Щёкино", "Новомосковск", "Алексин"],
    },
    city: "Тула",
    rating: 4.9,
    reviewsCount: 247,
    ordersCount: 1248,
    verified: true,
    trustLevel: "MASTER",
    tariff: "PREMIUM",
    legalInfo: {
      status: "NPD",
      inn: "710200012345",
      npdRegisteredAt: "2019-08-20",
      documentsVerified: true,
      verifiedAt: "2019-09-01",
    },
    taxMode: "NPD",
    specialization: ["Бисквитные торты", "Медовики", "Авторские десерты", "Капкейки"],
    portfolioImages: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
      "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600",
    ],
    followersCount: 3420,
    responseTime: "обычно отвечает в течение часа",
    joinedAt: "2019-08-14",
    selfPickup: true,
    deliveryOptions: ["own", "courier", "pickup_point"],
    paymentSettings: {
      acceptCard: true,
      acceptSbp: true,
      acceptCash: true,
      acceptSplit: true,
      acceptInstallment: true,
      installmentMinAmount: 1500,
      installmentProviders: ["split", "tinkoff"],
      installmentPlans: [
        {
          id: "ip1_c1",
          name: "Рассрочка на 3 месяца",
          months: 3,
          interestRate: 0,
          minAmount: 1500,
          downPaymentPercent: 0,
          provider: "split",
          description: "Беспроцентная рассрочка на 3 месяца через Сплит",
          isActive: true,
        },
        {
          id: "ip2_c1",
          name: "Рассрочка на 6 месяцев",
          months: 6,
          interestRate: 5,
          minAmount: 3000,
          downPaymentPercent: 20,
          provider: "tinkoff",
          description: "Рассрочка 6 месяцев, первый взнос 20%, переплата 5%",
          isActive: true,
        },
      ],
    },
    balance: 84200,
    totalEarnings: 1284000,
    monthlyEarnings: 184000,
  },
  {
    id: "c2",
    userId: "u6",
    businessName: "Кондитерская Купец",
    slug: "konditerskaya-kupets",
    description:
      "Семейная кондитерская из Москвы. Готовим торты и пирожные по дореволюционным рецептам. Используем масло Вологодское, сливки 33%, настоящий шоколад Callebaut. Принимаем заказы на свадебные и корпоративные торты.",
    avatar: "https://i.pravatar.cc/150?img=23",
    cover: "https://images.unsplash.com/photo-1557925923-cd4648e211a0?w=1200",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Сокольники",
      street: "ул. Русаковская",
      house: "28",
      apartment: "12",
      postalCode: "107014",
      lat: 55.7937,
      lng: 37.6798,
      serviceRadiusKm: 30,
      deliveryCities: ["Москва", "Химки", "Балашиха", "Подольск", "Мытищи"],
    },
    city: "Москва",
    rating: 4.8,
    reviewsCount: 412,
    ordersCount: 2380,
    verified: true,
    trustLevel: "EXPERT",
    tariff: "PROFI",
    legalInfo: {
      status: "IP",
      ipOgrnip: "318770000012345",
      ipInn: "770000012345",
      ipUsnRate: "6%",
      documentsVerified: true,
      verifiedAt: "2018-04-01",
      bankAccount: "40802810000000123456",
      bankBik: "044525225",
      bankName: "ПАО Сбербанк",
    },
    taxMode: "IP",
    specialization: ["Свадебные торты", "Классика", "Пирожные", "Корпоративные"],
    portfolioImages: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
      "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600",
      "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600",
    ],
    followersCount: 5680,
    responseTime: "ответ в течение 2 часов",
    joinedAt: "2018-03-20",
    selfPickup: true,
    deliveryOptions: ["own", "courier", "pickup_point", "cdek"],
    paymentSettings: {
      acceptCard: true,
      acceptSbp: true,
      acceptCash: false,
      acceptSplit: true,
      acceptInstallment: true,
      installmentMinAmount: 5000,
      installmentProviders: ["split", "tinkoff", "sberbank"],
      installmentPlans: [
        {
          id: "ip1_c2",
          name: "Рассрочка на 4 месяца",
          months: 4,
          interestRate: 0,
          minAmount: 5000,
          downPaymentPercent: 25,
          provider: "split",
          description: "Беспроцентная рассрочка 4 месяца, первый взнос 25%",
          isActive: true,
        },
        {
          id: "ip2_c2",
          name: "Рассрочка на 12 месяцев",
          months: 12,
          interestRate: 12,
          minAmount: 10000,
          downPaymentPercent: 0,
          provider: "tinkoff",
          description: "Рассрочка на год, переплата 12%",
          isActive: true,
        },
        {
          id: "ip3_c2",
          name: "СберРассрочка на 6 месяцев",
          months: 6,
          interestRate: 0,
          minAmount: 3000,
          downPaymentPercent: 0,
          provider: "sberbank",
          description: "Беспроцентная рассрочка от Сбербанка",
          isActive: true,
        },
      ],
    },
    balance: 152800,
    totalEarnings: 3120000,
    monthlyEarnings: 287000,
  },
  {
    id: "c3",
    userId: "u7",
    businessName: "Татьяна-Кондитер",
    slug: "tatyana-konditer",
    description:
      "Домашний кондитер из Петербурга. Люблю создавать нежные муссовые торты и cheesecake. Работаю на заказ, каждая работа уникальна. Принимаю заказы за 3-5 дней.",
    avatar: "https://i.pravatar.cc/150?img=44",
    cover: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=1200",
    location: {
      country: "Россия",
      region: "Санкт-Петербург",
      city: "Санкт-Петербург",
      district: "Петроградский",
      street: "Большой пр. ПС",
      house: "55",
      apartment: "12",
      postalCode: "197198",
      lat: 59.9603,
      lng: 30.3096,
      serviceRadiusKm: 20,
      deliveryCities: ["Санкт-Петербург", "Кудрово", "Всеволожск"],
    },
    city: "Санкт-Петербург",
    rating: 5.0,
    reviewsCount: 89,
    ordersCount: 312,
    verified: true,
    trustLevel: "TRUSTED",
    tariff: "START",
    legalInfo: {
      status: "NPD",
      inn: "784200012345",
      npdRegisteredAt: "2023-05-15",
      documentsVerified: true,
      verifiedAt: "2023-05-20",
    },
    taxMode: "NPD",
    specialization: ["Муссовые торты", "Cheesecake", "Макаронс", "Бенто-торты"],
    portfolioImages: [
      "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
    ],
    followersCount: 1240,
    responseTime: "ответ в течение 30 минут",
    joinedAt: "2023-05-10",
    selfPickup: true,
    deliveryOptions: ["own", "courier"],
    balance: 18700,
    totalEarnings: 287000,
    monthlyEarnings: 64000,
  },
  {
    id: "c4",
    userId: "u8",
    businessName: "Сахарный Лебедь",
    slug: "saharnyy-lebed",
    description:
      "Ателье авторских тортов. Художественная роспись, сахарная флористика, вафельная бумага. Каждый торт — произведение искусства. Принимаем заказы от 5000 руб.",
    avatar: "https://i.pravatar.cc/150?img=20",
    cover: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=1200",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Хамовники",
      street: "ул. Льва Толстого",
      house: "16",
      apartment: "8",
      postalCode: "119021",
      lat: 55.7338,
      lng: 37.5878,
      serviceRadiusKm: 40,
      deliveryCities: ["Москва", "Подольск", "Красногорск", "Одинцово", "Химки"],
    },
    city: "Москва",
    rating: 4.95,
    reviewsCount: 156,
    ordersCount: 420,
    verified: true,
    trustLevel: "MASTER",
    tariff: "PREMIUM",
    legalInfo: {
      status: "OOO",
      oooOgrn: "1177700000123",
      oooInn: "7700000123",
      oooKpp: "770001001",
      oooLegalAddress: "г. Москва, ул. Льва Толстого, д. 16",
      oooTaxSystem: "USN_6",
      documentsVerified: true,
      verifiedAt: "2017-10-01",
      bankAccount: "40702810000000123456",
      bankBik: "044525225",
      bankName: "ПАО Сбербанк",
    },
    taxMode: "OOO",
    specialization: ["Авторские торты", "Свадебные", "Сахарная флористика", "Тематические"],
    portfolioImages: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
      "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=600",
    ],
    followersCount: 7230,
    responseTime: "ответ в течение часа",
    joinedAt: "2017-09-25",
    selfPickup: false,
    deliveryOptions: ["own", "courier", "pickup_point", "cdek"],
    balance: 234500,
    totalEarnings: 5240000,
    monthlyEarnings: 412000,
  },
];

// ===== КУРЬЕРЫ =====
export const MOCK_COURIERS: Courier[] = [
  {
    id: "cr1",
    userId: "u4",
    name: "Иван Курьеров",
    avatar: "https://i.pravatar.cc/150?img=15",
    phone: "+7 926 888-99-00",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Тверской",
      street: "ул. Тверская",
      house: "12",
      postalCode: "125009",
      lat: 55.7558,
      lng: 37.6173,
      serviceRadiusKm: 15,
    },
    city: "Москва",
    legalInfo: {
      status: "NPD",
      inn: "770000045678",
      npdRegisteredAt: "2025-01-20",
      documentsVerified: true,
      verifiedAt: "2025-01-25",
    },
    transport: "car",
    maxWeightKg: 30,
    serviceRadiusKm: 15,
    workingHours: { from: "09:00", to: "21:00" },
    workingDays: [1, 2, 3, 4, 5, 6],
    isOnline: true,
    rating: 4.9,
    deliveriesCount: 312,
    balance: 18750,
    earningsToday: 1850,
    earningsMonth: 52000,
    earningsTotal: 487000,
    earningsPerDelivery: 450,
    verified: true,
  },
  {
    id: "cr2",
    userId: "u13",
    name: "Пётр Доставкин",
    avatar: "https://i.pravatar.cc/150?img=33",
    phone: "+7 903 555-12-34",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Басманный",
      street: "ул. Покровка",
      house: "20",
      postalCode: "101000",
      lat: 55.7573,
      lng: 37.6372,
      serviceRadiusKm: 10,
    },
    city: "Москва",
    legalInfo: {
      status: "IP",
      ipOgrnip: "320770000012345",
      ipInn: "770000023456",
      ipUsnRate: "6%",
      documentsVerified: true,
      verifiedAt: "2024-06-01",
    },
    transport: "bicycle",
    maxWeightKg: 8,
    serviceRadiusKm: 10,
    workingHours: { from: "10:00", to: "20:00" },
    workingDays: [1, 2, 3, 4, 5],
    isOnline: true,
    rating: 4.85,
    deliveriesCount: 187,
    balance: 9800,
    earningsToday: 950,
    earningsMonth: 28400,
    earningsTotal: 198000,
    earningsPerDelivery: 350,
    verified: true,
  },
  {
    id: "cr3",
    userId: "u14",
    name: "Сергей Везёт",
    avatar: "https://i.pravatar.cc/150?img=58",
    phone: "+7 916 222-33-44",
    location: {
      country: "Россия",
      region: "Тульская область",
      city: "Тула",
      district: "Центральный",
      street: "пр. Ленина",
      house: "55",
      postalCode: "300000",
      lat: 54.1961,
      lng: 37.6182,
      serviceRadiusKm: 25,
    },
    city: "Тула",
    legalInfo: {
      status: "NPD",
      inn: "710200045678",
      npdRegisteredAt: "2025-03-10",
      documentsVerified: true,
      verifiedAt: "2025-03-15",
    },
    transport: "motorbike",
    maxWeightKg: 15,
    serviceRadiusKm: 25,
    workingHours: { from: "08:00", to: "22:00" },
    workingDays: [1, 2, 3, 4, 5, 6, 0],
    isOnline: false,
    rating: 4.92,
    deliveriesCount: 412,
    balance: 34200,
    earningsToday: 0,
    earningsMonth: 64000,
    earningsTotal: 612000,
    earningsPerDelivery: 500,
    verified: true,
  },
];

// ===== ПРОДУКТЫ =====
export const MOCK_PRODUCTS: Product[] = [
  // ===== ТОВАРЫ ОСНОВНОГО КОНДИТЕРА (c0 — Волоколамск) =====
  {
    id: "p0_wedding",
    confectionerId: "c0",
    title: "Свадебный торт «Сахарная печать» (многоярусный)",
    slug: "svadebnyy-tort-saharnaya-pechat",
    description:
      "Многоярусный свадебный торт с уникальной технологией — сахарная печать вашего фото или рисунка на съедобной бумаге. Бисквит на выбор: ванильный, шоколадный, красный бархат. Крем: маскарпоне, сливочный сыр или шоколадный ганаш. Декор: свежие ягоды, съедобные бусины, лента. Вес от 3 кг, порций от 25.",
    category: "cakes",
    subcategory: "wedding",
    price: 4500,
    oldPrice: 5500,
    weight: "от 3 кг",
    servings: 25,
    prepTime: "3-5 дней",
    images: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800",
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
    ],
    rating: 5.0,
    reviewsCount: 1,
    tags: ["Свадебный", "Сахарная печать", "Многоярусный", "Премиум", "Хит"],
    fillings: [
      { name: "Ванильный бисквит + маскарпоне", priceModifier: 0 },
      { name: "Шоколадный бисквит + ганаш", priceModifier: 300 },
      { name: "Красный бархат + сливочный сыр", priceModifier: 200 },
    ],
    coatings: [
      { name: "Крем-чиз", priceModifier: 0 },
      { name: "Белый ганаш", priceModifier: 200 },
    ],
    decorations: [
      { name: "Сахарная печать (ваше фото)", priceModifier: 500 },
      { name: "Свежие ягоды", priceModifier: 400 },
      { name: "Съедобные бусины", priceModifier: 300 },
    ],
    customizable: true,
    suitableFor: ["wedding", "anniversary"],
    isPopular: true,
    isNew: true,
    inStock: 999,
    available: true,
    ecoBadges: ["Натуральные ингредиенты", "Ручная работа"],
    // AR / 3D preview
    modelUrl: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
    arEnabled: true,
  },
  {
    id: "p0_christening",
    confectionerId: "c0",
    title: "Торт на крестины «Ангел» с сахарной печатью",
    slug: "tort-na-krestiny-angel",
    description:
      "Торт для крестин с нежным декором: ангелочки, крестильная тематика, имя ребёнка. Сахарная печать — фото малыша или тематический рисунок. Бисквит ванильный с кремом пломбир. Вес от 1.5 кг, порций от 12.",
    category: "cakes",
    subcategory: "christening",
    price: 2800,
    weight: "от 1.5 кг",
    servings: 12,
    prepTime: "2-3 дня",
    images: [
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    ],
    rating: 5.0,
    reviewsCount: 1,
    tags: ["Крестины", "Сахарная печать", "Детский", "Имя на торте"],
    fillings: [
      { name: "Ванильный + крем пломбир", priceModifier: 0 },
      { name: "Шоколадный + ганаш", priceModifier: 300 },
    ],
    coatings: [
      { name: "Крем-чиз белый", priceModifier: 0 },
    ],
    decorations: [
      { name: "Сахарная печать (фото/рисунок)", priceModifier: 500 },
      { name: "Имя ребёнка (надпись)", priceModifier: 300 },
      { name: "Фигурки ангелов", priceModifier: 600 },
    ],
    customizable: true,
    suitableFor: ["christening", "kids"],
    isPopular: false,
    isNew: true,
    inStock: 999,
    available: true,
    ecoBadges: ["Натуральные ингредиенты"],
  },
  {
    id: "p0_birthday",
    confectionerId: "c0",
    title: "Торт с фото (сахарная печать) на день рождения",
    slug: "tort-s-foto-saharnaya-pechat",
    description:
      "Праздничный торт с любой фотографией или изображением — напечатанным на съедобной бумаге пищевыми чернилами. Идеально для дня рождения: фото именинника, персонаж мультфильма, логотип компании. Бисквит и начинку выбираете вы. Вес от 1 кг.",
    category: "cakes",
    subcategory: "birthday",
    price: 2200,
    weight: "от 1 кг",
    servings: 10,
    prepTime: "1-2 дня",
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
      "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800",
    ],
    rating: 5.0,
    reviewsCount: 1,
    tags: ["Сахарная печать", "Торт с фото", "День рождения", "Хит"],
    fillings: [
      { name: "Ванильный + сгущёнка", priceModifier: 0 },
      { name: "Шоколадный + ганаш", priceModifier: 300 },
      { name: "Красный бархат + маскарпоне", priceModifier: 200 },
    ],
    coatings: [
      { name: "Крем-чиз", priceModifier: 0 },
    ],
    decorations: [
      { name: "Сахарная печать (1 фото)", priceModifier: 500 },
      { name: "Надпись", priceModifier: 200 },
      { name: "Свечи-цифры", priceModifier: 150 },
    ],
    customizable: true,
    suitableFor: ["birthday", "kids", "corporate"],
    isPopular: true,
    isNew: false,
    inStock: 999,
    available: true,
    ecoBadges: ["Натуральные ингредиенты", "Ручная работа"],
    // AR / 3D preview
    modelUrl: "https://modelviewer.dev/shared-assets/models/Astronaut.glb",
    arEnabled: true,
  },
  {
    id: "p0_custom",
    confectionerId: "c0",
    title: "Торт на заказ (индивидуальный дизайн)",
    slug: "tort-na-zakaz-individualnyy",
    description:
      "Любой торт по вашему желанию! Обсудим дизайн, начинку, декор. Сахарная печать, мастика, кремовый декор, живые цветы — всё в одном месте. Опыт работы с тортами любой сложности: от классики до авторских шедевров. Расчёт стоимости — индивидуально.",
    category: "cakes",
    subcategory: "custom",
    price: 1800,
    weight: "от 1 кг",
    servings: 8,
    prepTime: "2-5 дней",
    images: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
      "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800",
    ],
    rating: 5.0,
    reviewsCount: 1,
    tags: ["На заказ", "Индивидуальный", "Сахарная печать", "Любой дизайн"],
    fillings: [
      { name: "На выбор (обсудим)", priceModifier: 0 },
    ],
    coatings: [
      { name: "На выбор (обсудим)", priceModifier: 0 },
    ],
    decorations: [
      { name: "Сахарная печать", priceModifier: 500 },
      { name: "Мастика (декор)", priceModifier: 800 },
      { name: "Кремовый декор", priceModifier: 400 },
    ],
    customizable: true,
    suitableFor: ["birthday", "wedding", "kids", "corporate", "anniversary"],
    isPopular: false,
    isNew: false,
    inStock: 999,
    available: true,
    ecoBadges: ["Ручная работа", "Натуральные ингредиенты"],
  },
  // ===== Остальные товары =====
  {
    id: "p1",
    title: "Торт «Уездный классический»",
    slug: "conditera-classic",
    description:
      "Бисквитный торт с нежным кремом пломбир и варёной сгущёнкой. Пропитан сиропом, украшен свежими ягодами. Классика, проверенная временем.",
    price: 2400,
    oldPrice: 2900,
    category: "cakes",
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
    ],
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    rating: 4.9,
    reviewsCount: 87,
    weight: "1.5 кг",
    servings: 10,
    prepTime: "2 дня",
    isPopular: true,
    isHit: true,
    tags: ["бисквит", "сгущёнка", "ягоды"],
    fillings: [
      { name: "Варёная сгущёнка", priceModifier: 0 },
      { name: "Крем пломбир", priceModifier: 200 },
      { name: "Шоколадный ганаш", priceModifier: 350 },
      { name: "Творожный крем", priceModifier: 250 },
    ],
    coatings: [
      { name: "Крем-чиз", priceModifier: 0 },
      { name: "Ганаш белый", priceModifier: 200 },
      { name: "Ганаш тёмный", priceModifier: 250 },
    ],
    decorations: [
      { name: "Свежие ягоды", priceModifier: 400 },
      { name: "Шоколадная крошка", priceModifier: 150 },
      { name: "Безе", priceModifier: 300 },
      { name: "Сахарные бусины", priceModifier: 200 },
    ],
    paymentOptions: {
      acceptCard: true,
      acceptSbp: true,
      acceptCash: true,
      acceptInstallment: true,
      availableInstallments: ["ip1_c1", "ip2_c1"],
    },
  },
  {
    id: "p2",
    title: "Торт «Купеческий медовик»",
    slug: "kupetcheskiy-medovik",
    description:
      "Многослойный медовик с ароматным мёдом и сметанным кремом. 8 тонких коржей, тающий во рту. По рецепту конца XIX века.",
    price: 2100,
    category: "cakes",
    images: ["https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800"],
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    rating: 4.95,
    reviewsCount: 142,
    weight: "1.4 кг",
    servings: 12,
    prepTime: "1 день",
    isHit: true,
    tags: ["мёд", "сметана", "классика"],
    fillings: [
      { name: "Сметанный крем", priceModifier: 0 },
      { name: "Заварной крем", priceModifier: 200 },
      { name: "Сливочный с мёдом", priceModifier: 250 },
    ],
    coatings: [
      { name: "Крошка из коржей", priceModifier: 0 },
      { name: "Карамельная глазурь", priceModifier: 200 },
    ],
    decorations: [
      { name: "Орехи грецкие", priceModifier: 200 },
      { name: "Кунжут карамельный", priceModifier: 150 },
    ],
  },
  {
    id: "p3",
    title: "Муссовый торт «Северное сияние»",
    slug: "mussovyy-severnoe-siyanie",
    description:
      "Нежный муссовый торт с прослойкой маракуйи и зеркальной глазурью. Без выпечки, лёгкий, тающий. Идеален для летнего праздника.",
    price: 3200,
    category: "cakes",
    images: ["https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800"],
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    rating: 5.0,
    reviewsCount: 38,
    weight: "1.2 кг",
    servings: 8,
    prepTime: "3 дня",
    isNew: true,
    tags: ["мусс", "маракуйя", "без выпечки"],
    fillings: [
      { name: "Маракуйя", priceModifier: 0 },
      { name: "Малина", priceModifier: 150 },
      { name: "Манго-маракуйя", priceModifier: 250 },
    ],
    coatings: [
      { name: "Зеркальная глазурь", priceModifier: 0 },
      { name: "Велюр шоколадный", priceModifier: 300 },
    ],
    decorations: [
      { name: "Съедобный декор", priceModifier: 250 },
      { name: "Шоколадные сферы", priceModifier: 400 },
    ],
  },
  {
    id: "p4",
    title: "Авторский торт «Лебедь»",
    slug: "avtorskiy-lebed",
    description:
      "Художественный торт с ручной росписью и сахарными цветами. 3 яруса, выполнен в технике «сахарная флористика». Шедевр для особого случая.",
    price: 12500,
    category: "cakes",
    images: ["https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800"],
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    rating: 4.98,
    reviewsCount: 24,
    weight: "5 кг",
    servings: 40,
    prepTime: "7 дней",
    isPopular: true,
    tags: ["свадебный", "3 яруса", "роспись"],
    fillings: [
      { name: "Бисквит + крем пломбир", priceModifier: 0 },
      { name: "Шоколад + вишня", priceModifier: 800 },
      { name: "Красный бархат", priceModifier: 600 },
    ],
    coatings: [
      { name: "Сахарная мастика", priceModifier: 0 },
      { name: "Ганаш + роспись", priceModifier: 1200 },
    ],
    decorations: [
      { name: "Сахарные цветы (5 шт)", priceModifier: 2500 },
      { name: "Художественная роспись", priceModifier: 1800 },
      { name: "Лента из вафельной бумаги", priceModifier: 900 },
    ],
    paymentOptions: {
      acceptCard: true,
      acceptSbp: true,
      acceptCash: false,
      acceptInstallment: true,
      availableInstallments: ["ip1_c2", "ip2_c2", "ip3_c2"],
    },
  },
  {
    id: "p5",
    title: "Набор капкейков «Праздничный»",
    slug: "kapkeyki-prazdnichnyy",
    description:
      "12 капкейков с разными вкусами: ваниль, шоколад, красный бархат, лимон. Украшены шапочкой из крем-чиза и декором.",
    price: 1800,
    category: "cupcakes",
    images: ["https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800"],
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    rating: 4.85,
    reviewsCount: 56,
    weight: "0.7 кг",
    servings: 12,
    prepTime: "1 день",
    isPopular: true,
    tags: ["капкейки", "набор", "праздник"],
  },
  {
    id: "p6",
    title: "Бенто-торт «Мини-радость»",
    slug: "bento-mini-radost",
    description:
      "Маленький бенто-торт 10-12 см с индивидуальной надписью. Идеален для одного-двух человек. Любой дизайн и цвет.",
    price: 890,
    category: "bento",
    images: ["https://images.unsplash.com/photo-1612203985729-70726954388c?w=800"],
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    rating: 4.92,
    reviewsCount: 73,
    weight: "0.4 кг",
    servings: 2,
    prepTime: "1 день",
    isNew: true,
    tags: ["бенто", "мини", "надпись"],
    fillings: [
      { name: "Сгущёнка", priceModifier: 0 },
      { name: "Крем-чиз", priceModifier: 100 },
      { name: "Шоколад", priceModifier: 150 },
    ],
    coatings: [
      { name: "Крем-чиз", priceModifier: 0 },
      { name: "Мастика", priceModifier: 200 },
    ],
    decorations: [{ name: "Надпись", priceModifier: 0 }],
  },
  {
    id: "p7",
    title: "Макаронс ассорти (12 шт)",
    slug: "makarons-assorti",
    description:
      "Набор французских макаронс: фисташка, малина, шоколад, ваниль, лимон, лаванда. Хрустящая оболочка, нежная начинка.",
    price: 1450,
    category: "macarons",
    images: ["https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800"],
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    rating: 4.97,
    reviewsCount: 41,
    weight: "0.2 кг",
    servings: 12,
    prepTime: "2 дня",
    isHit: true,
    tags: ["французские", "ассорти", "подарок"],
  },
  {
    id: "p8",
    title: "Чизкейк «Нью-Йорк»",
    slug: "chizkeyk-new-york",
    description:
      "Классический чизкейк Нью-Йорк на песочной основе. Нежный, кремовый, с лёгкой ванильной ноткой. Подаётся с ягодным соусом.",
    price: 1980,
    category: "desserts",
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800"],
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    rating: 4.88,
    reviewsCount: 98,
    weight: "1.3 кг",
    servings: 10,
    prepTime: "1 день",
    isPopular: true,
    tags: ["чизкейк", "классика", "ваниль"],
  },
  {
    id: "p9",
    title: "Пирожные «Корзиночка» (10 шт)",
    slug: "pirozhnye-korzinochka",
    description:
      "Песочные корзиночки с белковым кремом и ягодами. Знакомый вкус из детства. Сделаны вручную по ГОСТу.",
    price: 1200,
    category: "pastries",
    images: ["https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800"],
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    rating: 4.91,
    reviewsCount: 67,
    weight: "0.6 кг",
    servings: 10,
    prepTime: "1 день",
    tags: ["корзиночка", "ГОСТ", "детство"],
  },
  {
    id: "p10",
    title: "Шоколадные конфеты ручной работы",
    slug: "shokoladnye-konfety",
    description:
      "Набор из 16 шоколадных конфет ручной работы: пралине, трюфели, ganache. Бельгийский шоколад Callebaut.",
    price: 2200,
    category: "chocolate",
    images: ["https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800"],
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    rating: 4.96,
    reviewsCount: 32,
    weight: "0.25 кг",
    servings: 16,
    prepTime: "3 дня",
    isNew: true,
    tags: ["шоколад", "ручная работа", "подарок"],
  },
  {
    id: "p11",
    title: "Печенье «Имбирное уездное» (20 шт)",
    slug: "pechene-imbirnoe",
    description:
      "Имбирное печенье с глазурью ручной росписи. Каждое печенье — уникальное. Идеально к чаю и как подарок.",
    price: 980,
    category: "cookies",
    images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800"],
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    rating: 4.87,
    reviewsCount: 45,
    weight: "0.4 кг",
    servings: 20,
    prepTime: "2 дня",
    tags: ["имбирное", "роспись", "подарок"],
  },
  {
    id: "p12",
    title: "Торт «Праздничный бенто-сет» 6 шт",
    slug: "bento-set-6",
    description:
      "Набор из 6 бенто-тортов с разными вкусами и дизайном. Отличный подарок для коллег или друзей. Каждый с авторской надписью.",
    price: 4500,
    oldPrice: 5400,
    category: "bento",
    images: ["https://images.unsplash.com/photo-1612203985729-70726954388c?w=800"],
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    rating: 4.93,
    reviewsCount: 19,
    weight: "2.4 кг",
    servings: 12,
    prepTime: "2 дня",
    isHit: true,
    tags: ["бенто", "сет", "подарок"],
  },
];

// ===== ПОСТАВЩИКИ =====
export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "s1",
    businessName: "Мукомольная компания «Колос»",
    description:
      "Оптовый поставщик муки премиум-класса. Прямые поставки с мельниц Краснодарского края. Мука высшего сорта, тёрочная, цельнозерновая.",
    avatar: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=400",
    location: {
      country: "Россия",
      region: "Московская область",
      city: "Подольск",
      district: "Промзона",
      street: "ул. Заводская",
      house: "1",
      postalCode: "142100",
      lat: 55.4310,
      lng: 37.5448,
    },
    city: "Москва",
    rating: 4.9,
    minOrder: 3000,
    deliveryTime: "1-3 дня",
    categories: ["Мука", "Крупы", "Сахар"],
    legalInfo: {
      status: "OOO",
      oooOgrn: "1155000012345",
      oooInn: "5000000123",
      oooKpp: "500001001",
      oooLegalAddress: "Московская обл., г. Подольск, ул. Заводская, д. 1",
      oooTaxSystem: "USN_6",
      documentsVerified: true,
      verifiedAt: "2015-06-01",
      bankAccount: "40702810000000987654",
      bankBik: "044525700",
      bankName: "АО «Альфа-Банк»",
    },
    deliveryRegions: ["Москва", "Московская область", "Тульская область", "Вся Россия"],
    deliveryOptions: ["own", "cdek", "pickup_point"],
  },
  {
    id: "s2",
    businessName: "Шоколад-Опт",
    description:
      "Поставщик бельгийского и российского шоколада. Callebaut, Cacao Barry, Babaevsky. Оптовые цены, сертификация.",
    avatar: "https://images.unsplash.com/photo-1623345238651-00d2f4f2c4c4?w=400",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Дорогомилово",
      street: "Кутузовский пр-т",
      house: "45",
      postalCode: "121248",
      lat: 55.7370,
      lng: 37.5470,
    },
    city: "Москва",
    rating: 4.8,
    minOrder: 5000,
    deliveryTime: "2-4 дня",
    categories: ["Шоколад", "Какао", "Глазурь"],
    legalInfo: {
      status: "OOO",
      oooOgrn: "1187700012345",
      oooInn: "7700000234",
      oooKpp: "770001001",
      oooLegalAddress: "г. Москва, Кутузовский пр-т, д. 45",
      oooTaxSystem: "VAT",
      documentsVerified: true,
      verifiedAt: "2018-08-15",
      bankAccount: "40702810000000456789",
      bankBik: "044525225",
      bankName: "ПАО Сбербанк",
    },
    deliveryRegions: ["Москва", "Санкт-Петербург", "Вся Россия"],
    deliveryOptions: ["own", "cdek", "boxberry", "pickup_point"],
  },
  {
    id: "s3",
    businessName: "Сливочный край",
    description:
      "Молочная продукция для кондитеров: сливки 33%, масло 82.5%, творог, сыры. Только натуральное, без растительных жиров.",
    avatar: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    location: {
      country: "Россия",
      region: "Вологодская область",
      city: "Вологда",
      district: "Октябрьский",
      street: "ул. Мира",
      house: "20",
      postalCode: "160000",
      lat: 59.2205,
      lng: 39.8915,
    },
    city: "Вологда",
    rating: 4.95,
    minOrder: 2000,
    deliveryTime: "1-2 дня",
    categories: ["Сливки", "Масло", "Сыры"],
    legalInfo: {
      status: "OOO",
      oooOgrn: "1093500001234",
      oooInn: "3500000123",
      oooKpp: "350001001",
      oooLegalAddress: "г. Вологда, ул. Мира, д. 20",
      oooTaxSystem: "USN_15",
      documentsVerified: true,
      verifiedAt: "2009-09-01",
      bankAccount: "40702810000000345678",
      bankBik: "041909644",
      bankName: "ПАО «ВТБ»",
    },
    deliveryRegions: ["Вологодская область", "Москва", "Санкт-Петербург", "Московская область"],
    deliveryOptions: ["own", "cdek", "pickup_point"],
  },
  {
    id: "s4",
    businessName: "Ягоды-Опт",
    description:
      "Свежие и замороженные ягоды круглый год. Прямые поставки из Сербии, Польши, Краснодарского края. Малина, клубника, черника, маракуйя.",
    avatar: "https://images.unsplash.com/photo-1543528176-61b239494933?w=400",
    location: {
      country: "Россия",
      region: "Москва",
      city: "Москва",
      district: "Южное Бутово",
      street: "ул. Изюмская",
      house: "55",
      postalCode: "117042",
      lat: 55.5530,
      lng: 37.5400,
    },
    city: "Москва",
    rating: 4.7,
    minOrder: 1500,
    deliveryTime: "1-2 дня",
    categories: ["Ягоды", "Фрукты"],
    legalInfo: {
      status: "IP",
      ipOgrnip: "321770000023456",
      ipInn: "770000034567",
      ipUsnRate: "15%",
      documentsVerified: true,
      verifiedAt: "2021-04-12",
    },
    deliveryRegions: ["Москва", "Московская область"],
    deliveryOptions: ["own", "cdek"],
  },
];

export const MOCK_SUPPLIER_PRODUCTS: SupplierProduct[] = [
  {
    id: "sp1",
    supplierId: "s1",
    title: "Мука пшеничная высший сорт 2кг",
    description: "Мука Макфа высшего сорта. Идеальна для бисквитов и слоёного теста.",
    price: 145,
    unit: "уп.",
    category: "Мука",
    inStock: 1240,
    image: "https://images.unsplash.com/photo-1568254183919-78a4f43a2877?w=400",
    bulkPrices: [
      { quantity: 10, price: 130 },
      { quantity: 50, price: 115 },
    ],
  },
  {
    id: "sp2",
    supplierId: "s1",
    title: "Сахар-песок 5кг",
    description: "Сахар рафинад песок. ГОСТ.",
    price: 320,
    unit: "мешок",
    category: "Сахар",
    inStock: 580,
    image: "https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400",
    bulkPrices: [{ quantity: 20, price: 290 }],
  },
  {
    id: "sp3",
    supplierId: "s2",
    title: "Шоколад Callebaut 811 тёмный 54% 2.5кг",
    description: "Бельгийский тёмный шоколад Callebault 811. Классика для кондитеров.",
    price: 2980,
    unit: "блок",
    category: "Шоколад",
    inStock: 84,
    image: "https://images.unsplash.com/photo-1623345238651-00d2f4f2c4c4?w=400",
    bulkPrices: [
      { quantity: 5, price: 2780 },
      { quantity: 20, price: 2480 },
    ],
  },
  {
    id: "sp4",
    supplierId: "s2",
    title: "Какао-порошок Valrhona 1кг",
    description: "Французский какао-порошок Valrhona 100%. Насыщенный вкус.",
    price: 1890,
    unit: "уп.",
    category: "Какао",
    inStock: 42,
    image: "https://images.unsplash.com/photo-1610725664285-7c57e6eeac3f?w=400",
  },
  {
    id: "sp5",
    supplierId: "s3",
    title: "Сливки 33% Petrow 1л",
    description: "Сливки 33% Petrow. Идеальны для взбивания и кремов.",
    price: 290,
    unit: "л",
    category: "Сливки",
    inStock: 320,
    image: "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400",
    bulkPrices: [{ quantity: 20, price: 265 }],
  },
  {
    id: "sp6",
    supplierId: "s3",
    title: "Масло сливочное Вологодское 82.5% 200г",
    description: "Настоящее вологодское масло 82.5%. ГОСТ.",
    price: 195,
    unit: "уп.",
    category: "Масло",
    inStock: 580,
    image: "https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400",
  },
  {
    id: "sp7",
    supplierId: "s4",
    title: "Малина замороженная 1кг",
    description: "Малина шоковой заморозки. Сербия. Без сахара.",
    price: 540,
    unit: "кг",
    category: "Ягоды",
    inStock: 145,
    image: "https://images.unsplash.com/photo-1543528176-61b239494933?w=400",
    bulkPrices: [{ quantity: 10, price: 490 }],
  },
  {
    id: "sp8",
    supplierId: "s4",
    title: "Клубника свежая 500г",
    description: "Клубника свежая. Краснодарский край. Сезон.",
    price: 380,
    unit: "уп.",
    category: "Ягоды",
    inStock: 76,
    image: "https://images.unsplash.com/photo-1464982326199-86b0ba616a37?w=400",
  },
];

// ===== ЗАКАЗЫ =====
export const MOCK_ORDERS: Order[] = [
  {
    id: "o1",
    number: "UK-2025-0001",
    customerId: "u1",
    customerName: "Анна Соколова",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    items: [
      {
        productId: "p1",
        title: "Торт «Уездный классический»",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        price: 2600,
        quantity: 1,
        customization: { filling: "Крем пломбир", coating: "Крем-чиз", decoration: "Свежие ягоды", inscription: "С днём рождения!" },
      },
    ],
    total: 2950,
    status: "DELIVERING",
    deliveryAddress: "Москва, ул. Тверская, д. 12, кв. 45",
    deliveryDate: "2026-07-02",
    deliveryTime: "14:00-16:00",
    deliveryCost: 350,
    createdAt: "2026-06-28",
    paymentMethod: "card",
    paymentStatus: "escrow",
    comment: "Позвонить за час до доставки",
  },
  {
    id: "o2",
    number: "UK-2025-0002",
    customerId: "u1",
    customerName: "Анна Соколова",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    items: [
      {
        productId: "p7",
        title: "Макаронс ассорти (12 шт)",
        image: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=400",
        price: 1450,
        quantity: 2,
      },
    ],
    total: 2900,
    status: "COMPLETED",
    deliveryAddress: "Москва, ул. Тверская, д. 12",
    deliveryDate: "2026-06-15",
    deliveryCost: 300,
    createdAt: "2026-06-10",
    paymentMethod: "card",
    paymentStatus: "released",
  },
  {
    id: "o3",
    number: "UK-2025-0003",
    customerId: "u1",
    customerName: "Анна Соколова",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    items: [
      {
        productId: "p8",
        title: "Чизкейк «Нью-Йорк»",
        image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
        price: 1980,
        quantity: 1,
      },
    ],
    total: 2280,
    status: "PENDING",
    deliveryAddress: "Москва, ул. Тверская, д. 12",
    deliveryDate: "2026-07-05",
    deliveryCost: 300,
    createdAt: "2026-06-29",
    paymentMethod: "card",
    paymentStatus: "paid",
  },
  {
    id: "o4",
    number: "UK-2025-0004",
    customerId: "u9",
    customerName: "Ольга Иванова",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    items: [
      {
        productId: "p5",
        title: "Набор капкейков «Праздничный»",
        image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400",
        price: 1800,
        quantity: 2,
      },
    ],
    total: 3900,
    status: "IN_PROGRESS",
    deliveryAddress: "Тула, пр. Ленина, д. 55",
    deliveryDate: "2026-07-03",
    deliveryCost: 300,
    createdAt: "2026-06-29",
    paymentMethod: "card",
    paymentStatus: "escrow",
  },
  {
    id: "o5",
    number: "UK-2025-0005",
    customerId: "u10",
    customerName: "Дмитрий Петров",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    items: [
      {
        productId: "p1",
        title: "Торт «Уездный классический»",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        price: 2400,
        quantity: 1,
      },
    ],
    total: 2700,
    status: "READY",
    deliveryAddress: "Тула, ул. Первомайская, д. 8",
    deliveryDate: "2026-06-30",
    deliveryCost: 300,
    createdAt: "2026-06-26",
    paymentMethod: "cash",
    paymentStatus: "escrow",
  },
  {
    id: "o6",
    number: "UK-2025-0006",
    customerId: "u11",
    customerName: "Екатерина Смирнова",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    items: [
      {
        productId: "p11",
        title: "Печенье «Имбирное уездное» (20 шт)",
        image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400",
        price: 980,
        quantity: 3,
      },
    ],
    total: 2940,
    status: "CONFIRMED",
    deliveryAddress: "Тула, ул. Советская, д. 22",
    deliveryDate: "2026-07-04",
    deliveryCost: 0,
    createdAt: "2026-06-29",
    paymentMethod: "card",
    paymentStatus: "escrow",
  },
  {
    id: "o7",
    number: "UK-2025-0007",
    customerId: "u12",
    customerName: "Сергей Волков",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    items: [
      {
        productId: "p1",
        title: "Торт «Уездный классический»",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        price: 2600,
        quantity: 1,
        customization: { filling: "Крем пломбир", coating: "Крем-чиз" },
      },
    ],
    total: 2900,
    status: "COMPLETED",
    deliveryAddress: "Тула, ул. Кутузова, д. 4",
    deliveryDate: "2026-06-20",
    deliveryCost: 300,
    createdAt: "2026-06-15",
    paymentMethod: "card",
    paymentStatus: "released",
  },
];

// ===== ЧАТ =====
export const MOCK_CHAT_ROOMS: ChatRoom[] = [
  {
    id: "r1",
    type: "direct",
    name: "Сладкая уездная",
    avatar: "https://i.pravatar.cc/150?img=32",
    participants: [
      { id: "u1", name: "Анна Соколова", avatar: "https://i.pravatar.cc/150?img=47" },
      { id: "u2", name: "Мария Уездная", avatar: "https://i.pravatar.cc/150?img=32" },
    ],
    lastMessage: "Да, конечно! Можем добавить надпись «С днём рождения!»",
    lastMessageAt: "2026-06-30T10:30:00",
    unreadCount: 2,
  },
  {
    id: "r2",
    type: "order",
    name: "Заказ UK-2025-0001",
    avatar: "https://i.pravatar.cc/150?img=32",
    participants: [
      { id: "u1", name: "Анна Соколова" },
      { id: "u2", name: "Мария Уездная" },
      { id: "u4", name: "Иван Курьеров" },
    ],
    lastMessage: "Курьер выехал, буду через 40 минут",
    lastMessageAt: "2026-06-30T11:15:00",
    unreadCount: 1,
    orderId: "o1",
  },
  {
    id: "r3",
    type: "support",
    name: "Поддержка Уездного",
    avatar: "https://i.pravatar.cc/150?img=68",
    participants: [
      { id: "u1", name: "Анна Соколова" },
      { id: "u5", name: "Поддержка" },
    ],
    lastMessage: "Спасибо за обращение! Ваш вопрос решён.",
    lastMessageAt: "2026-06-28T16:45:00",
    unreadCount: 0,
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  // === Bot welcome для order-чата r2 ===
  {
    id: "mbot1",
    roomId: "r2",
    senderId: "bot",
    senderName: "Уездный помощник",
    senderAvatar: "/logo.png",
    text:
      "🤖 Добро пожаловать! Я — Уездный помощник, сопроводитель вашего заказа #UK-2025-0001.\n\n" +
      "📋 Состав заказа:\n  • Торт «Уездный классический» × 1 = 4500₽\n\n" +
      "💰 Итого: 4800₽\n\n" +
      "Я буду держать вас в курсе статуса заказа. Если есть вопросы — задавайте!",
    createdAt: "2026-06-30T09:00:00",
    isBot: true,
    botKind: "welcome",
    quickReplies: [
      { label: "Когда привезут?", action: "faq:delivery_time" },
      { label: "Как оплатить?", action: "faq:payment" },
      { label: "Изменить состав", action: "faq:modify_order" },
      { label: "Соединить с оператором", action: "human:operator" },
    ],
  },
  {
    id: "m1",
    roomId: "r1",
    senderId: "u2",
    senderName: "Мария Уездная",
    senderAvatar: "https://i.pravatar.cc/150?img=32",
    text: "Здравствуйте! Меня заинтересовал ваш заказ на торт «Уездный классический».",
    createdAt: "2026-06-30T10:15:00",
  },
  {
    id: "m2",
    roomId: "r1",
    senderId: "u1",
    senderName: "Анна Соколова",
    senderAvatar: "https://i.pravatar.cc/150?img=47",
    text: "Добрый день! Да, хочу заказать его на день рождения дочери.",
    createdAt: "2026-06-30T10:20:00",
    isOwn: true,
  },
  {
    id: "m3",
    roomId: "r1",
    senderId: "u1",
    senderName: "Анна Соколова",
    senderAvatar: "https://i.pravatar.cc/150?img=47",
    text: "Можно ли добавить надпись «С днём рождения, Маша!»?",
    createdAt: "2026-06-30T10:21:00",
    isOwn: true,
  },
  {
    id: "m4",
    roomId: "r1",
    senderId: "u2",
    senderName: "Мария Уездная",
    senderAvatar: "https://i.pravatar.cc/150?img=32",
    text: "Да, конечно! Можем добавить надпись «С днём рождения!»",
    createdAt: "2026-06-30T10:30:00",
    reactions: [{ emoji: "❤️", count: 1 }],
  },
];

// ===== СОЦИАЛЬНЫЙ КАНАЛ =====
export const MOCK_CHANNEL_POSTS: ChannelPost[] = [
  {
    id: "cp1",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    caption:
      "Сегодня испекла торт для свадьбы на 80 человек! Три яруса, крем-чиз, свежие ягоды. Невеста была в восторге ❤️ #свадьба #торт",
    likes: 245,
    comments: 3,
    createdAt: "2026-06-29T14:30:00",
    postComments: [
      {
        id: "cc1",
        postId: "cp1",
        userId: "u1",
        userName: "Анна Соколова",
        userAvatar: "https://i.pravatar.cc/150?img=47",
        text: "Какая красота! Можно заказать такой на 50 человек?",
        createdAt: "2026-06-29T15:00:00",
        likes: 5,
      },
      {
        id: "cc2",
        postId: "cp1",
        userId: "u9",
        userName: "Екатерина Смирнова",
        userAvatar: "https://i.pravatar.cc/150?img=49",
        text: "Шикарный торт! Сколько стоит ярус такого размера?",
        createdAt: "2026-06-29T16:30:00",
        likes: 2,
      },
      {
        id: "cc3",
        postId: "cp1",
        userId: "u2",
        userName: "Мария Уездная",
        userAvatar: "https://i.pravatar.cc/150?img=32",
        text: "@Анна Конечно! Напишите в чат, обсудим детали 🍰",
        createdAt: "2026-06-29T17:00:00",
        likes: 8,
      },
    ],
  },
  {
    id: "cp2",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800",
    caption:
      "Набор капкейков на детский праздник 🎉 12 штук, разные вкусы: ваниль, шоколад, красный бархел. Заказать можно в каталоге!",
    likes: 187,
    comments: 2,
    createdAt: "2026-06-28T11:00:00",
    postComments: [
      {
        id: "cc4",
        postId: "cp2",
        userId: "u10",
        userName: "Ольга Иванова",
        userAvatar: "https://i.pravatar.cc/150?img=44",
        text: "Заказывала на день рождения дочери — дети были в восторге!",
        createdAt: "2026-06-28T14:00:00",
        likes: 3,
      },
      {
        id: "cc5",
        postId: "cp2",
        userId: "u1",
        userName: "Анна Соколова",
        userAvatar: "https://i.pravatar.cc/150?img=47",
        text: "А можно с надписью «С Днём Рождения»?",
        createdAt: "2026-06-28T15:30:00",
        likes: 1,
      },
    ],
  },
  {
    id: "cp3",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800",
    caption:
      "Имбирное печенье с ручной росписью. Каждое уникально! Это отличный подарок к чаю 🍵",
    likes: 134,
    comments: 1,
    createdAt: "2026-06-27T16:20:00",
    postComments: [
      {
        id: "cc6",
        postId: "cp3",
        userId: "u11",
        userName: "Дмитрий Петров",
        userAvatar: "https://i.pravatar.cc/150?img=51",
        text: "Подскажите, можно ли заказать с корпоративным логотипом?",
        createdAt: "2026-06-27T18:00:00",
        likes: 0,
      },
    ],
  },
];

// Сторис кондитеров (исчезают через 24 часа)
export const MOCK_CHANNEL_STORIES: ChannelStory[] = [
  {
    id: "cs1",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600",
    caption: "Процесс декорирования торта 🎨",
    createdAt: "2026-06-30T10:00:00",
    expiresAt: "2026-07-01T10:00:00",
    views: 234,
    viewed: false,
  },
  {
    id: "cs2",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600",
    caption: "Свежие ягоды для торта 🍓",
    createdAt: "2026-06-30T08:00:00",
    expiresAt: "2026-07-01T08:00:00",
    views: 156,
    viewed: false,
  },
  {
    id: "cs3",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    image: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600",
    caption: "Медовик по рецепту XIX века",
    createdAt: "2026-06-30T09:00:00",
    expiresAt: "2026-07-01T09:00:00",
    views: 89,
    viewed: false,
  },
];

// Подписчики кондитеров
export const MOCK_CHANNEL_FOLLOWERS: ChannelFollower[] = [
  { id: "cf1", confectionerId: "c1", userId: "u1", userName: "Анна Соколова", userAvatar: "https://i.pravatar.cc/150?img=47", followedAt: "2026-03-15", isFollowing: false },
  { id: "cf2", confectionerId: "c1", userId: "u9", userName: "Екатерина Смирнова", userAvatar: "https://i.pravatar.cc/150?img=49", followedAt: "2026-04-10", isFollowing: false },
  { id: "cf3", confectionerId: "c1", userId: "u10", userName: "Ольга Иванова", userAvatar: "https://i.pravatar.cc/150?img=44", followedAt: "2026-05-01", isFollowing: true },
  { id: "cf4", confectionerId: "c1", userId: "u11", userName: "Дмитрий Петров", userAvatar: "https://i.pravatar.cc/150?img=51", followedAt: "2026-05-20", isFollowing: false },
  { id: "cf5", confectionerId: "c1", userId: "u12", userName: "Светлана К.", userAvatar: "https://i.pravatar.cc/150?img=23", followedAt: "2026-06-01", isFollowing: true },
];

// ===== КАТЕГОРИИ ДЛЯ КАТАЛОГА =====
export const CATEGORIES = [
  { slug: "cakes", name: "Торты", icon: "🎂", count: 8, group: "Кондитерские изделия" },
  { slug: "cupcakes", name: "Капкейки", icon: "🧁", count: 1, group: "Кондитерские изделия" },
  { slug: "pastries", name: "Пирожные", icon: "🥮", count: 1, group: "Кондитерские изделия" },
  { slug: "cookies", name: "Печенье", icon: "🍪", count: 1, group: "Кондитерские изделия" },
  { slug: "chocolate", name: "Шоколад", icon: "🍫", count: 1, group: "Кондитерские изделия" },
  { slug: "macarons", name: "Макаронс", icon: "🌸", count: 1, group: "Кондитерские изделия" },
  { slug: "bento", name: "Бенто-торты", icon: "🍱", count: 2, group: "Кондитерские изделия" },
  { slug: "desserts", name: "Десерты", icon: "🍰", count: 1, group: "Кондитерские изделия" },
  // Новые категории
  { slug: "zephyr_bouquets", name: "Зефирные букеты", icon: "💐", count: 0, group: "Кондитерские изделия" },
  { slug: "pies", name: "Пироги", icon: "🥧", count: 0, group: "Кондитерские изделия" },
  { slug: "patties", name: "Пирожки", icon: "🥟", count: 0, group: "Кондитерские изделия" },
  { slug: "rolls", name: "Рулеты", icon: "🍰", count: 0, group: "Кондитерские изделия" },
  { slug: "healthy", name: "ПП изделия", icon: "🥗", count: 0, group: "Кондитерские изделия" },
  { slug: "pastila", name: "Пастила", icon: "🍬", count: 0, group: "Кондитерские изделия" },
  { slug: "oriental_sweets", name: "Восточные сладости", icon: "🍯", count: 0, group: "Кондитерские изделия" },
  { slug: "candies", name: "Конфеты", icon: "🍫", count: 0, group: "Кондитерские изделия" },
  { slug: "marmalade", name: "Мармелад", icon: "🍊", count: 0, group: "Кондитерские изделия" },
  { slug: "lollipops", name: "Леденцы", icon: "🍭", count: 0, group: "Кондитерские изделия" },
  { slug: "gingerbread", name: "Пряники", icon: "🍪", count: 0, group: "Кондитерские изделия" },
  { slug: "realistic_cakes", name: "Реалистичные пирожные", icon: "🎭", count: 0, group: "Кондитерские изделия" },
  // Сопутствующие
  { slug: "decor", name: "Декор для тортов", icon: "🎀", count: 0, group: "Сопутствующие товары", link: "decor-shop" },
  { slug: "packaging", name: "Упаковка", icon: "📦", count: 0, group: "Сопутствующие товары", link: "decor-shop" },
  { slug: "ingredients", name: "Ингредиенты", icon: "🧂", count: 0, group: "Сопутствующие товары", link: "supplier-shop" },
  { slug: "equipment", name: "Оборудование", icon: "🔧", count: 0, group: "Сопутствующие товары", link: "supplier-shop" },
  { slug: "tools", name: "Инвентарь", icon: "🥄", count: 0, group: "Сопутствующие товары", link: "supplier-shop" },
  { slug: "services", name: "Услуги и площадки", icon: "🎭", count: 0, group: "Сопутствующие товары", link: "services-shop" },
  { slug: "certificates", name: "Подарочные сертификаты", icon: "💳", count: 0, group: "Сопутствующие товары", link: "gift-certificates" },
  { slug: "edible-printing", name: "Печать на пряниках и бумаге", icon: "🖨️", count: 0, group: "Сопутствующие товары", link: "services-shop" },
] as const;

export const CATEGORY_GROUPS = [
  { id: "confectionery", name: "Кондитерские изделия", icon: "🎂" },
  { id: "supplies", name: "Сопутствующие товары", icon: "🎁" },
] as const;

// ===== Опции для конструктора тортов =====
export const CAKE_BUILDER_OPTIONS = {
  // Типы кондитерских изделий — определяет доступные шаги и опции
  productTypes: [
    {
      id: "cake",
      label: "Торт",
      icon: "🎂",
      description: "Классический многоярусный или одноярусный торт",
      unit: "порция",
      defaultServings: 8,
      minServings: 4,
      maxServings: 100,
      priceBase: 1500,
      steps: ["event", "base", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["sponge", "mousse", "honey", "red_velvet", "biscuit"],
      hasTiers: true,
      hasShape: true,
    },
    {
      id: "cupcakes",
      label: "Капкейки",
      icon: "🧁",
      description: "Маленькие кексы с кремом — набор от 6 штук",
      unit: "шт",
      defaultQuantity: 12,
      minQuantity: 6,
      maxQuantity: 100,
      priceBase: 200,
      steps: ["event", "base", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["sponge", "biscuit"],
    },
    {
      id: "macarons",
      label: "Макаронс",
      icon: "🟡",
      description: "Французское миндальное пирожное — набор от 8 штук",
      unit: "шт",
      defaultQuantity: 16,
      minQuantity: 8,
      maxQuantity: 100,
      priceBase: 150,
      steps: ["event", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "pastries",
      label: "Пирожные",
      icon: "🍰",
      description: "Десерт в стакане или корзиночке — набор от 6 штук",
      unit: "шт",
      defaultQuantity: 8,
      minQuantity: 6,
      maxQuantity: 50,
      priceBase: 250,
      steps: ["event", "base", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["sponge", "biscuit", "cheesecake"],
    },
    {
      id: "cookies",
      label: "Печенье",
      icon: "🍪",
      description: "Имбирное или песочное печенье — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 20,
      minQuantity: 10,
      maxQuantity: 200,
      priceBase: 80,
      steps: ["event", "base", "decor", "diet", "delivery", "summary"],
      applicableBases: ["biscuit"],
    },
    {
      id: "cheesecake",
      label: "Чизкейк",
      icon: "🧀",
      description: "Десерт на сливочном сыре — целиком или порционно",
      unit: "порция",
      defaultServings: 8,
      minServings: 4,
      maxServings: 30,
      priceBase: 1800,
      steps: ["event", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: ["cheesecake"],
    },
    {
      id: "tart",
      label: "Тарт",
      icon: "🥧",
      description: "Открытый пирог с фруктами или ягодами",
      unit: "порция",
      defaultServings: 8,
      minServings: 4,
      maxServings: 30,
      priceBase: 1600,
      steps: ["event", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: ["biscuit"],
      hasShape: true,
    },
    {
      id: "mousse_cake",
      label: "Муссовый торт",
      icon: "🍮",
      description: "Многослойный муссовый десерт с зеркальной глазурью",
      unit: "порция",
      defaultServings: 8,
      minServings: 4,
      maxServings: 30,
      priceBase: 2200,
      steps: ["event", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["mousse"],
      hasTiers: true,
      hasShape: true,
    },
    {
      id: "brownies",
      label: "Брауни",
      icon: "🍫",
      description: "Шоколадное пирожное без выпечки — набор от 6 штук",
      unit: "шт",
      defaultQuantity: 9,
      minQuantity: 6,
      maxQuantity: 50,
      priceBase: 180,
      steps: ["event", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "gingerbread",
      label: "Пряники",
      icon: "🔴",
      description: "Имбирные пряники с росписью — набор от 5 штук",
      unit: "шт",
      defaultQuantity: 10,
      minQuantity: 5,
      maxQuantity: 100,
      priceBase: 120,
      steps: ["event", "decor", "diet", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "bento",
      label: "Бенто-торт",
      icon: "🍱",
      description: "Мини-торт на 1-2 человека в коробочке",
      unit: "шт",
      defaultQuantity: 1,
      minQuantity: 1,
      maxQuantity: 20,
      priceBase: 700,
      steps: ["event", "base", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["sponge", "mousse", "red_velvet"],
      hasShape: true,
    },
    {
      id: "desserts",
      label: "Десерты в стакане",
      icon: "🍰",
      description: "Слоёные десерты в стаканчиках — набор от 6 штук",
      unit: "шт",
      defaultQuantity: 8,
      minQuantity: 6,
      maxQuantity: 50,
      priceBase: 180,
      steps: ["event", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: ["mousse", "cheesecake"],
    },
    {
      id: "zephyr_bouquets",
      label: "Зефирные букеты",
      icon: "💐",
      description: "Съедобный букет из зефира — от 7 штук",
      unit: "шт",
      defaultQuantity: 12,
      minQuantity: 7,
      maxQuantity: 50,
      priceBase: 350,
      steps: ["event", "decor", "diet", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "pies",
      label: "Пироги",
      icon: "🥧",
      description: "Сладкий пирог целиком — на 6-20 порций",
      unit: "порция",
      defaultServings: 8,
      minServings: 6,
      maxServings: 20,
      priceBase: 900,
      steps: ["event", "base", "filling", "decor", "diet", "delivery", "summary"],
      applicableBases: ["biscuit", "honey"],
      hasShape: true,
    },
    {
      id: "patties",
      label: "Пирожки",
      icon: "🥟",
      description: "Сладкие пирожки с начинкой — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 15,
      minQuantity: 10,
      maxQuantity: 100,
      priceBase: 90,
      steps: ["event", "filling", "diet", "delivery", "summary"],
      applicableBases: ["biscuit"],
    },
    {
      id: "rolls",
      label: "Рулеты",
      icon: "🍰",
      description: "Сладкий рулет с начинкой — целиком",
      unit: "порция",
      defaultServings: 8,
      minServings: 6,
      maxServings: 20,
      priceBase: 1100,
      steps: ["event", "base", "filling", "coating", "decor", "diet", "delivery", "summary"],
      applicableBases: ["sponge", "honey", "biscuit"],
      hasShape: false, // Рулет всегда одной формы
    },
    {
      id: "healthy",
      label: "ПП изделия",
      icon: "🥗",
      description: "Без сахара, на натуральных подсластителях",
      unit: "порция",
      defaultServings: 8,
      minServings: 4,
      maxServings: 20,
      priceBase: 1400,
      steps: ["event", "base", "filling", "coating", "decor", "delivery", "summary"],
      applicableBases: ["sponge", "mousse", "cheesecake"],
      hasShape: true,
    },
    {
      id: "pastila",
      label: "Пастила",
      icon: "🍬",
      description: "Воздушная пастила — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 15,
      minQuantity: 10,
      maxQuantity: 100,
      priceBase: 100,
      steps: ["event", "decor", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "oriental_sweets",
      label: "Восточные сладости",
      icon: "🍯",
      description: "Чак-чак, пахлава, рахат-лукум — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 15,
      minQuantity: 10,
      maxQuantity: 100,
      priceBase: 130,
      steps: ["event", "decor", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "candies",
      label: "Конфеты",
      icon: "🍫",
      description: "Авторские шоколадные конфеты — набор от 12 штук",
      unit: "шт",
      defaultQuantity: 16,
      minQuantity: 12,
      maxQuantity: 100,
      priceBase: 120,
      steps: ["event", "decor", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "marmalade",
      label: "Мармелад",
      icon: "🍊",
      description: "Натуральный фруктовый мармелад — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 15,
      minQuantity: 10,
      maxQuantity: 100,
      priceBase: 90,
      steps: ["event", "decor", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "lollipops",
      label: "Леденцы",
      icon: "🍭",
      description: "Авторские леденцы с узорами — набор от 10 штук",
      unit: "шт",
      defaultQuantity: 15,
      minQuantity: 10,
      maxQuantity: 200,
      priceBase: 80,
      steps: ["event", "decor", "delivery", "summary"],
      applicableBases: [],
    },
    {
      id: "realistic_cakes",
      label: "Реалистичные пирожные",
      icon: "🎭",
      description: "Пирожные в виде предметов (книги, растения и т.д.)",
      unit: "шт",
      defaultQuantity: 6,
      minQuantity: 1,
      maxQuantity: 50,
      priceBase: 500,
      steps: ["event", "base", "filling", "coating", "decor", "delivery", "summary"],
      applicableBases: ["sponge", "mousse"],
      hasShape: true,
    },
    {
      id: "chocolate",
      label: "Шоколад",
      icon: "🍫",
      description: "Авторский шоколад и шоколадные фигуры",
      unit: "шт",
      defaultQuantity: 10,
      minQuantity: 6,
      maxQuantity: 100,
      priceBase: 150,
      steps: ["event", "filling", "decor", "delivery", "summary"],
      applicableBases: [], // Шоколад не имеет основы-бисквита
    },
  ],
  // Формы изделий (для тортов, пирогов, бенто и т.д.)
  shapes: [
    { id: "round", label: "Круг", icon: "⭕", description: "Классическая круглая форма", priceModifier: 0 },
    { id: "square", label: "Квадрат", icon: "⬜", description: "Квадратная форма — современный вид", priceModifier: 200 },
    { id: "heart", label: "Сердце", icon: "❤️", description: "Форма сердца — для романтических событий", priceModifier: 300 },
    { id: "sphere", label: "Шар", icon: "⚪", description: "Сферическая форма — для муссовых тортов", priceModifier: 500 },
    { id: "book", label: "Книга", icon: "📚", description: "Торт в виде книги — для выпускного", priceModifier: 400 },
    { id: "number", label: "Цифра", icon: "🔢", description: "Торт в виде цифры (возраст)", priceModifier: 350 },
    { id: "letter", label: "Буква", icon: "🔤", description: "Торт в виде буквы (первая буква имени)", priceModifier: 350 },
    { id: "custom", label: "Своя форма", icon: "✨", description: "Уникальная форма по вашему эскизу", priceModifier: 800 },
  ],
  // Количество ярусов (для тортов)
  tiers: [
    { id: 1, label: "1 ярус", minGuests: 4, maxGuests: 15, recommendedWeight: 1.5, priceModifier: 0 },
    { id: 2, label: "2 яруса", minGuests: 15, maxGuests: 40, recommendedWeight: 3.5, priceModifier: 1500 },
    { id: 3, label: "3 яруса", minGuests: 40, maxGuests: 80, recommendedWeight: 6, priceModifier: 3500 },
    { id: 4, label: "4+ ярусов", minGuests: 80, maxGuests: 200, recommendedWeight: 10, priceModifier: 6000 },
  ],
  eventTypes: [
    { id: "birthday", label: "День рождения", icon: "🎂", description: "Праздничный торт для именинника" },
    { id: "wedding", label: "Свадьба", icon: "💍", description: "Многоярусный торт для торжества" },
    { id: "kids", label: "Детский праздник", icon: "🧸", description: "Яркий торт с любимыми героями" },
    { id: "corporate", label: "Корпоратив", icon: "🏢", description: "Для офисного праздника" },
    { id: "romantic", label: "Романтический", icon: "💕", description: "Торт для двоих" },
    { id: "just", label: "Просто так", icon: "🍰", description: "Угостить себя и близких" },
    { id: "anniversary", label: "Юилей", icon: "🎉", description: "Круглая дата — торт с цифрой" },
    { id: "newyear", label: "Новый год", icon: "🎄", description: "Торт в новогодней тематике" },
    { id: "valentine", label: "День святого Валентина", icon: "💝", description: "Торт в форме сердца" },
    { id: "march8", label: "8 марта", icon: "🌷", description: "Торт с весенними цветами" },
    { id: "feb23", label: "23 февраля", icon: "🎖️", description: "Торт в мужской тематике" },
    { id: "christmas", label: "Рождество", icon: "🕯️", description: "Рождественский торт" },
    { id: "easter", label: "Пасха", icon: "🥚", description: "Пасхальный кулич и декор" },
    { id: "graduation", label: "Выпускной", icon: "🎓", description: "Торт в виде книги или диплома" },
    { id: "babyshower", label: "Baby shower", icon: "🍼", description: "Торт для будущей мамы" },
    { id: "engagement", label: "Помолвка", icon: "💎", description: "Торт для предложения" },
    { id: "memorial", label: "Поминки", icon: "🕊️", description: "Торт для поминальной трапезы" },
    { id: "housewarming", label: "Новоселье", icon: "🏡", description: "Торт на новоселье" },
    { id: "professional", label: "Профессиональный", icon: "💼", description: "День юриста, медика, учителя и т.д." },
    { id: "city_day", label: "День города", icon: "🏙️", description: "Городской праздник" },
  ],
  bases: [
    { id: "sponge", label: "Бисквит", description: "Классический воздушный бисквит", priceBase: 0 },
    { id: "mousse", label: "Муссовый", description: "Нежный мусс без выпечки", priceBase: 400 },
    { id: "cheesecake", label: "Чизкейк", description: "На песочной основе", priceBase: 300 },
    { id: "honey", label: "Медовик", description: "Тонкие медовые коржи", priceBase: 0 },
    { id: "red_velvet", label: "Красный бархат", description: "Яркий бисквит со сливочным кремом", priceBase: 200 },
    { id: "biscuit", label: "Песочный бисквит", description: "Рассыпчатая текстура", priceBase: 0 },
  ],
  fillings: [
    { id: "condensed_milk", label: "Варёная сгущёнка", price: 0 },
    { id: "cream_pleshir", label: "Крем пломбир", price: 200 },
    { id: "chocolate_ganache", label: "Шоколадный ганаш", price: 350 },
    { id: "curd_cream", label: "Творожный крем", price: 250 },
    { id: "raspberry", label: "Малиновый конфитюр", price: 280 },
    { id: "mango_passion", label: "Манго-маракуйя", price: 400 },
    { id: "strawberry", label: "Клубничный конфитюр", price: 300 },
    { id: "lemon_curd", label: "Лимонный курд", price: 250 },
  ],
  coatings: [
    { id: "cream_cheese", label: "Крем-чиз", price: 0 },
    { id: "ganache_white", label: "Белый ганаш", price: 200 },
    { id: "ganache_dark", label: "Тёмный ганаш", price: 250 },
    { id: "mirror_glaze", label: "Зеркальная глазурь", price: 350 },
    { id: "velvet_spray", label: "Велюровое напыление", price: 400 },
    { id: "mastic", label: "Сахарная мастика", price: 500 },
  ],
  decorations: [
    { id: "berries", label: "Свежие ягоды", price: 400 },
    { id: "chocolate_curls", label: "Шоколадная стружка", price: 150 },
    { id: "macarons", label: "Макаронс", price: 350 },
    { id: "meringue", label: "Безе", price: 300 },
    { id: "sugar_flowers", label: "Сахарные цветы", price: 800 },
    { id: "fresh_fruit", label: "Свежие фрукты", price: 350 },
    { id: "edible_gold", label: "Сусальное золото", price: 600 },
    { id: "wafer_paper", label: "Вафельная бумага", price: 250 },
  ],
  dietary: [
    { id: "sugar_free", label: "Без сахара", description: "Сахарозаменитель вместо сахара" },
    { id: "gluten_free", label: "Без глютена", description: "Без пшеничной муки" },
    { id: "lactose_free", label: "Без лактозы", description: "Растительные сливки" },
    { id: "vegan", label: "Веганский", description: "Без животных продуктов" },
    { id: "keto", label: "Кето", description: "Низкоуглеводный" },
    { id: "hypoallergenic", label: "Гипоаллергенный", description: "Без орехов и яиц" },
  ],
};

// Заявки на конструктор (для дашборда кондитера)
export const MOCK_CONSTRUCTOR_INQUIRIES = [
  {
    id: "ci1",
    customerName: "Ольга Иванова",
    customerAvatar: "https://i.pravatar.cc/150?img=49",
    eventType: "kids",
    base: "sponge",
    filling: "Крем пломбир",
    coating: "Крем-чиз",
    decorations: ["Свежие ягоды"],
    servings: 10,
    city: "Москва",
    budget: 3500,
    deliveryDate: "2026-07-10",
    createdAt: "2026-06-29T09:15:00",
    status: "new" as const,
    comment: "Хочу торт с машинкой для сына",
  },
  {
    id: "ci2",
    customerName: "Дмитрий Петров",
    customerAvatar: "https://i.pravatar.cc/150?img=51",
    eventType: "wedding",
    base: "sponge",
    filling: "Шоколадный ганаш",
    coating: "Сахарная мастика",
    decorations: ["Сахарные цветы", "Сусальное золото"],
    servings: 40,
    city: "Тула",
    budget: 15000,
    deliveryDate: "2026-07-20",
    createdAt: "2026-06-28T14:30:00",
    status: "quoted" as const,
    comment: "Свадебный торт, 3 яруса",
  },
];

// Команда (для дашборда кондитера-студии)
export const MOCK_TEAM_TASKS = [
  { id: "t1", title: "Испечь торт на 80 человек", assignee: "Мария", status: "in_progress" as const, deadline: "2026-07-02", priority: "high" as const },
  { id: "t2", title: "Закупить ягоды на оптовом", assignee: "Светлана", status: "todo" as const, deadline: "2026-07-01", priority: "high" as const },
  { id: "t3", title: "Оформить доставку свадебного", assignee: "Иван", status: "todo" as const, deadline: "2026-07-05", priority: "medium" as const },
  { id: "t4", title: "Согласовать эскиз с клиентом", assignee: "Мария", status: "review" as const, deadline: "2026-06-30", priority: "medium" as const },
  { id: "t5", title: "Сфотографировать работы для канала", assignee: "Светлана", status: "done" as const, deadline: "2026-06-28", priority: "low" as const },
];

// Аналитика для дашборда кондитера
export const CONFECTIONER_ANALYTICS = {
  revenue: [
    { month: "Янв", value: 145000 },
    { month: "Фев", value: 162000 },
    { month: "Мар", value: 178000 },
    { month: "Апр", value: 152000 },
    { month: "Май", value: 198000 },
    { month: "Июн", value: 184000 },
  ],
  ordersByStatus: [
    { name: "Новые", value: 4, color: "oklch(0.55 0.18 25)" },
    { name: "В работе", value: 7, color: "oklch(0.70 0.14 70)" },
    { name: "Готовы", value: 3, color: "oklch(0.65 0.10 145)" },
    { name: "Доставляются", value: 2, color: "oklch(0.78 0.16 80)" },
    { name: "Завершены", value: 28, color: "oklch(0.55 0.12 305)" },
  ],
  topProducts: [
    { name: "Торт «Уездный классический»", sold: 14, revenue: 33600 },
    { name: "Капкейки «Праздничный»", sold: 9, revenue: 16200 },
    { name: "Имбирное печенье", sold: 6, revenue: 5880 },
  ],
};
