import type {
  Promotion,
  Recipe,
  InventoryItem,
  StockMovement,
  GanttTask,
  Reminder,
} from "./types";

// ===== АКЦИИ =====
export const MOCK_PROMOTIONS: Promotion[] = [
  {
    id: "pr1",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Скидка 15% на первый заказ",
    description:
      "Дарим новым клиентам скидку 15% на первый заказ любого торта. Используйте промокод при оформлении.",
    type: "first_order",
    value: 15,
    promoCode: "WELCOME15",
    minOrderAmount: 1500,
    startDate: "2026-06-01",
    endDate: "2026-07-31",
    cities: ["Тула", "Щёкино", "Новомосковск"],
    regions: ["Тульская область"],
    maxUsageCount: 100,
    usedCount: 32,
    maxPerUser: 1,
    status: "active",
    isPromoted: true,
    promotedUntil: "2026-07-15",
    promotedRegions: ["Тульская область", "Московская область"],
    promotionBudget: 5000,
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    createdAt: "2026-05-28",
    views: 1240,
    clicks: 184,
    conversions: 32,
  },
  {
    id: "pr2",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Бесплатная доставка при заказе от 3000 ₽",
    description:
      "Закажите торт на сумму от 3000 рублей и получите бесплатную доставку по Туле и области в радиусе 25 км.",
    type: "free_delivery",
    minOrderAmount: 3000,
    startDate: "2026-06-15",
    endDate: "2026-08-15",
    cities: ["Тула", "Щёкино", "Новомосковск", "Алексин"],
    regions: ["Тульская область"],
    status: "active",
    isPromoted: false,
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
    createdAt: "2026-06-10",
    views: 856,
    clicks: 92,
    conversions: 28,
    usedCount: 28,
  },
  {
    id: "pr3",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    title: "Свадебный сезон: торт + 50 макаронс в подарок",
    description:
      "При заказе свадебного торта от 15000 ₽ дарим набор из 50 макаронс для гостей. Только в июле-августе.",
    type: "gift",
    promoCode: "WEDDING2026",
    minOrderAmount: 15000,
    startDate: "2026-07-01",
    endDate: "2026-08-31",
    cities: ["Москва", "Химки", "Балашиха", "Подольск", "Мытищи"],
    regions: ["Москва", "Московская область"],
    maxUsageCount: 20,
    usedCount: 4,
    status: "active",
    isPromoted: true,
    promotedUntil: "2026-08-01",
    promotedRegions: ["Москва", "Московская область"],
    promotionBudget: 15000,
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
    createdAt: "2026-06-20",
    views: 2150,
    clicks: 312,
    conversions: 4,
  },
  {
    id: "pr4",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    title: "Корпоративный набор -20%",
    description:
      "Скидка 20% на корпоративные заказы от 10000 ₽. Идеально для офисных праздников и подарков сотрудникам.",
    type: "discount_percent",
    value: 20,
    promoCode: "CORP20",
    minOrderAmount: 10000,
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    cities: ["Москва"],
    regions: ["Москва"],
    status: "active",
    isPromoted: false,
    image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800",
    createdAt: "2026-05-25",
    views: 645,
    clicks: 78,
    conversions: 12,
    usedCount: 12,
  },
  {
    id: "pr5",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    title: "Бенто-торт 2+1: третий в подарок",
    description:
      "При заказе двух бенто-тортов третий в подарок. Идеально для небольших праздников и подарков.",
    type: "bundle",
    promoCode: "BENTO23",
    startDate: "2026-06-25",
    endDate: "2026-07-25",
    cities: ["Санкт-Петербург", "Кудрово", "Всеволожск"],
    regions: ["Санкт-Петербург"],
    status: "active",
    isPromoted: true,
    promotedUntil: "2026-07-25",
    promotedRegions: ["Санкт-Петербург", "Ленинградская область"],
    promotionBudget: 3000,
    image: "https://images.unsplash.com/photo-1612203985729-70726954388c?w=800",
    createdAt: "2026-06-22",
    views: 980,
    clicks: 142,
    conversions: 18,
    usedCount: 18,
  },
  {
    id: "pr6",
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    title: "Раннее бронирование -10%",
    description:
      "Закажите авторский торт за 14 дней до мероприятия и получите скидку 10%. Достаточно времени на проработку эскиза.",
    type: "early_booking",
    value: 10,
    promoCode: "EARLY14",
    minOrderAmount: 5000,
    startDate: "2026-06-01",
    endDate: "2026-12-31",
    cities: ["Москва", "Подольск", "Красногорск", "Одинцово", "Химки"],
    regions: ["Москва", "Московская область"],
    status: "active",
    isPromoted: true,
    promotedUntil: "2026-07-31",
    promotedRegions: ["Москва", "Московская область"],
    promotionBudget: 12000,
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
    createdAt: "2026-05-30",
    views: 1840,
    clicks: 245,
    conversions: 16,
    usedCount: 16,
  },
  {
    id: "pr7",
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    title: "Чёрная пятница: -25% на шоколадные конфеты",
    description:
      "Только в последнюю неделю ноября — скидка 25% на все наборы шоколадных конфет ручной работы.",
    type: "discount_percent",
    value: 25,
    promoCode: "BLACK25",
    startDate: "2026-11-25",
    endDate: "2026-11-30",
    cities: ["Москва"],
    regions: ["Москва", "Московская область"],
    status: "scheduled",
    isPromoted: false,
    image: "https://images.unsplash.com/photo-1519915028121-7d3463d20b13?w=800",
    createdAt: "2026-06-28",
    views: 0,
    clicks: 0,
    conversions: 0,
    usedCount: 0,
  },
  {
    id: "pr8",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Счастливые часы: -15% с 10:00 до 14:00",
    description:
      "Закажите торт в утренние часы и получите скидку 15%. Действует только на самовывоз.",
    type: "happy_hours",
    value: 15,
    promoCode: "HAPPY14",
    startDate: "2026-06-01",
    endDate: "2026-07-31",
    cities: ["Тула"],
    regions: ["Тульская область"],
    status: "active",
    isPromoted: false,
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800",
    createdAt: "2026-05-29",
    views: 420,
    clicks: 56,
    conversions: 14,
    usedCount: 14,
  },
  {
    id: "pr9",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    title: "День рождения клиента: x3 бонусов",
    description:
      "В месяц вашего дня рождения начисляем тройные бонусы за заказ. Покажите паспорт при получении.",
    type: "loyalty_bonus",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    cities: ["Санкт-Петербург"],
    regions: ["Санкт-Петербург"],
    status: "active",
    isPromoted: false,
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800",
    createdAt: "2026-01-10",
    views: 1560,
    clicks: 187,
    conversions: 45,
    usedCount: 45,
  },
  {
    id: "pr10",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    title: "8 июля — День семьи: торт «Медовик» -20%",
    description:
      "Праздничная акция ко Дню семьи, любви и верности. Скидка 20% на классический медовик весь день.",
    type: "holiday",
    value: 20,
    promoCode: "FAMILY8",
    startDate: "2026-07-08",
    endDate: "2026-07-08",
    cities: ["Москва"],
    regions: ["Москва", "Московская область"],
    status: "scheduled",
    isPromoted: true,
    promotedUntil: "2026-07-08",
    promotedRegions: ["Москва", "Московская область"],
    promotionBudget: 8000,
    image: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800",
    createdAt: "2026-06-29",
    views: 0,
    clicks: 0,
    conversions: 0,
    usedCount: 0,
  },
];

// ===== РЕЦЕПТЫ И УРОКИ =====
export const MOCK_RECIPES: Recipe[] = [
  {
    id: "rc1",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    type: "recipe",
    title: "Идеальный бисквит: секреты кондитера",
    description:
      "Подробный рецепт воздушного бисквита, который получается всегда. Раскрываю все секреты: температуру ингредиентов, время взбивания и режим выпекания.",
    coverImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    prepTime: 20,
    cookTime: 35,
    totalTime: 55,
    difficulty: "easy",
    servings: 10,
    ingredients: [
      { name: "Яйца", amount: "5", unit: "шт" },
      { name: "Сахар", amount: "200", unit: "г" },
      { name: "Мука пшеничная", amount: "180", unit: "г" },
      { name: "Крахмал", amount: "20", unit: "г" },
      { name: "Разрыхлитель", amount: "1", unit: "ч.л." },
      { name: "Ванилин", amount: "1", unit: "г" },
    ],
    steps: [
      {
        title: "Подготовка",
        description: "Яйца достать из холодильника за 30 минут до начала. Разогреть духовку до 180°C.",
      },
      {
        title: "Взбивание",
        description: "Взбивать яйца с сахаром на водяной бане 5-7 минут до увеличения объёма в 3 раза.",
      },
      {
        title: "Добавление муки",
        description: "Аккуратно вмешать просеянную муку с крахмалом и разрыхлителем лопаткой сверху вниз.",
      },
      {
        title: "Выпечка",
        description: "Выпекать 35 минут. Не открывать духовку первые 25 минут!",
      },
    ],
    tips: [
      "Все ингредиенты должны быть комнатной температуры",
      "Не открывайте духовку в первые 25 минут — бисквит опадёт",
      "Готовность проверяйте деревянной шпажкой",
    ],
    tags: ["бисквит", "основа", "выпечка", "для начинающих"],
    category: "Основы",
    access: "free",
    views: 4280,
    likes: 612,
    comments: 47,
    published: true,
    publishedAt: "2026-05-15",
    createdAt: "2026-05-10",
  },
  {
    id: "rc2",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    type: "master_class",
    title: "Мастер-класс: крем-чиз без комочков",
    description:
      "Видеоматер-класс по приготовлению идеального крем-чиза. Разбираем частые ошибки и показываем техники. 45 минут записи.",
    coverImage: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
    videoUrl: "https://example.com/video/cream-cheese",
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    difficulty: "medium",
    servings: 1,
    ingredients: [
      { name: "Творожный сыр", amount: "500", unit: "г" },
      { name: "Сливочное масло 82.5%", amount: "100", unit: "г" },
      { name: "Сахарная пудра", amount: "150", unit: "г" },
      { name: "Ванильный экстракт", amount: "1", unit: "ч.л." },
    ],
    steps: [
      {
        title: "Подготовка масла",
        description: "Масло должно быть мягким, комнатной температуры. Нарезать кубиками.",
      },
      {
        title: "Взбивание",
        description: "Взбить масло с пудрой до белой пышной массы, 5-7 минут.",
      },
      {
        title: "Добавление сыра",
        description: "Порциями добавить творожный сыр, взбивая на низкой скорости.",
      },
    ],
    tips: [
      "Не перебейте крем, иначе расслоится",
      "Используйте только холодный творожный сыр",
    ],
    tags: ["крем", "крем-чиз", "видеоурок", "декор"],
    category: "Кремы",
    access: "paid",
    price: 990,
    views: 1240,
    likes: 187,
    comments: 23,
    published: true,
    publishedAt: "2026-06-10",
    createdAt: "2026-06-05",
  },
  {
    id: "rc3",
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    type: "video_lesson",
    title: "Сахарная флористика: реалистичная роза",
    description:
      "Полный видеоурок по созданию сахарной розы. Техники раскатки, тонирования и сборки. 2 часа видео + PDF с шаблонами.",
    coverImage: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
    videoUrl: "https://example.com/video/sugar-rose",
    prepTime: 30,
    cookTime: 180,
    totalTime: 210,
    difficulty: "expert",
    servings: 1,
    ingredients: [
      { name: "Сахарная паста", amount: "500", unit: "г" },
      { name: "Клей пищевой", amount: "1", unit: "шт" },
      { name: "Красители гелевые", amount: "5", unit: "цветов" },
      { name: "Инструменты для флористики", amount: "1", unit: "набор" },
    ],
    steps: [
      {
        title: "Подготовка пасты",
        description: "Окрасить сахарную пасту в нужный оттенок, дать отдохнуть 30 минут.",
      },
      {
        title: "Раскатка лепестков",
        description: "Раскатать 30 тонких лепестков разного размера на специальной подушке.",
      },
      {
        title: "Тонирование",
        description: "Сухой кистью нанести более тёмный краситель на края лепестков.",
      },
      {
        title: "Сборка",
        description: "Собрать розу от центра, приклеивая лепестки по спирали.",
      },
    ],
    tips: [
      "Работайте в прохладном помещении",
      "Лепестки накройте плёнкой, чтобы не высохли",
    ],
    tags: ["сахарная флористика", "роза", "декор", "продвинутый"],
    category: "Декор",
    access: "paid",
    price: 2900,
    views: 856,
    likes: 234,
    comments: 41,
    published: true,
    publishedAt: "2026-06-18",
    createdAt: "2026-06-12",
  },
  {
    id: "rc4",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    type: "article",
    title: "История медовика: от царской кухни до наших дней",
    description:
      "Исторический очерк о происхождении медовика. Старинные рецепты XIX века и современная адаптация.",
    coverImage: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800",
    prepTime: 0,
    cookTime: 0,
    totalTime: 15,
    difficulty: "easy",
    servings: 1,
    ingredients: [],
    steps: [],
    tags: ["история", "медовик", "классика"],
    category: "История",
    access: "free",
    views: 2150,
    likes: 412,
    comments: 87,
    published: true,
    publishedAt: "2026-06-20",
    createdAt: "2026-06-15",
  },
  {
    id: "rc5",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    type: "recipe",
    title: "Муссовый торт «Северное сияние»: пошагово",
    description:
      "Рецепт моего фирменного муссового торта с зеркальной глазурью. Полностью без выпечки, нежный и лёгкий.",
    coverImage: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800",
    prepTime: 60,
    cookTime: 0,
    totalTime: 240,
    difficulty: "hard",
    servings: 8,
    ingredients: [
      { name: "Белый шоколад", amount: "200", unit: "г" },
      { name: "Сливки 33%", amount: "300", unit: "мл" },
      { name: "Маракуйя", amount: "5", unit: "шт" },
      { name: "Желатин", amount: "10", unit: "г" },
      { name: "Зеркальная глазурь", amount: "500", unit: "г" },
    ],
    steps: [
      {
        title: "Маракуйя конфи",
        description: "Сварить пюре из маракуйи с сахаром, добавить желатин, заморозить в форме.",
      },
      {
        title: "Мусс",
        description: "Растопить шоколад, смешать со взбитыми сливками, добавить желатин.",
      },
      {
        title: "Сборка",
        description: "Залить мусс в форму, утопить замороженную маракуйю, заморозить 4 часа.",
      },
      {
        title: "Глазурь",
        description: "Нагреть зеркальную глазурь до 35°C, вылить на замороженный торт.",
      },
    ],
    tips: [
      "Торт должен быть полностью заморожен перед заливкой глазури",
      "Глазурь должна стекать сама — не размазывайте",
    ],
    tags: ["мусс", "маракуйя", "без выпечки", "зеркальная глазурь"],
    category: "Торты",
    access: "free",
    views: 3120,
    likes: 489,
    comments: 56,
    published: true,
    publishedAt: "2026-06-08",
    createdAt: "2026-06-01",
  },
  {
    id: "rc6",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    type: "recipe",
    title: "Французские макаронс: 5 вкусов",
    description:
      "Базовый рецепт макаронс и 5 вариантов начинок: фисташка, малина, шоколад, лимон, лаванда. Секрет идеальной юбочки.",
    coverImage: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800",
    prepTime: 45,
    cookTime: 15,
    totalTime: 60,
    difficulty: "hard",
    servings: 30,
    ingredients: [
      { name: "Миндальная мука", amount: "150", unit: "г" },
      { name: "Сахарная пудра", amount: "150", unit: "г" },
      { name: "Яичные белки", amount: "110", unit: "г" },
      { name: "Сахар", amount: "150", unit: "г" },
      { name: "Вода", amount: "50", unit: "мл" },
    ],
    steps: [
      {
        title: "Подготовка",
        description: "Просеять миндальную муку с пудрой дважды. Белки состарить (выдержать сутки в холодильнике).",
      },
      {
        title: "Итальянская меренга",
        description: "Сварить сироп 118°C, тонкой струйкой влить во взбитые белки, продолжая взбивать.",
      },
      {
        title: "Макаронаж",
        description: "Соединить сухие ингредиенты с меренгой, вымесить до состояния «текущей ленты».",
      },
      {
        title: "Отсадка",
        description: "Отсадить одинаковые кружки на пергамент, постучать противнем о стол, дать корочке 30 минут.",
      },
      {
        title: "Выпечка",
        description: "Выпекать 15 минут при 150°C. Остудить полностью перед снятием.",
      },
    ],
    tips: [
      "Миндальная мука должна быть мелкого помола",
      "Корочка обязательна — иначе треснут",
      "Не снимайте с пергамента тёплыми",
    ],
    tags: ["макаронс", "французская кухня", "меренга", "продвинутый"],
    category: "Печенье",
    access: "free",
    views: 2840,
    likes: 532,
    comments: 78,
    published: true,
    publishedAt: "2026-05-22",
    createdAt: "2026-05-18",
  },
  {
    id: "rc7",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    type: "recipe",
    title: "Классический медовик: как в детстве",
    description:
      "Тот самый медовик — нежный, тающий во рту, с насыщенным сметанным кремом. Пошаговый рецепт с фотографиями каждого этапа. Коржи получаются тонкими и воздушными, крем пропитывает каждый слой.",
    coverImage: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800",
    prepTime: 40,
    cookTime: 10,
    totalTime: 240,
    difficulty: "medium",
    servings: 12,
    ingredients: [
      { name: "Мёд натуральный", amount: "3", unit: "ст.л." },
      { name: "Сахар", amount: "200", unit: "г" },
      { name: "Сливочное масло", amount: "100", unit: "г" },
      { name: "Яйца", amount: "2", unit: "шт" },
      { name: "Мука пшеничная", amount: "500", unit: "г" },
      { name: "Сода", amount: "2", unit: "ч.л." },
      { name: "Сметана 20%", amount: "800", unit: "г" },
      { name: "Сахарная пудра", amount: "150", unit: "г" },
      { name: "Ванильный сахар", amount: "10", unit: "г" },
    ],
    steps: [
      { title: "Заваривание теста", description: "На водяной бане растопить мёд, масло, сахар. Добавить соду — масса вспенится и побелеет. Снять с огня." },
      { title: "Замешивание", description: "В остывшую массу вбить яйца, постепенно добавить муку. Тесто должно быть мягким, не липнуть к рукам." },
      { title: "Выпечка коржей", description: "Разделить тесто на 8 частей. Раскатать каждый корж тонко (2-3 мм), выпекать 3-5 минут при 180°C до золотистости." },
      { title: "Крем", description: "Взбить сметану с пудрой и ванилью до густоты. Не перевзбейте — иначе масло отделится." },
      { title: "Сборка", description: "Промазать каждый корж кремом (2-3 ст.л. на корж). Верхний корж тоже смазать, обсыпать крошкой из обрезков." },
      { title: "Пропитка", description: "Оставить торт минимум на 4 часа (лучше на ночь) при комнатной температуре, затем в холодильнике 2 часа." },
    ],
    tips: [
      "Коржи пекутся очень быстро — не отвлекайтесь!",
      "Сметана должна быть холодной и жирной (от 20%)",
      "Чем дольше пропитывается — тем нежнее",
      "Обрезки коржей измельчите для обсыпки",
    ],
    tags: ["медовик", "классика", "сметанный крем", "мёд"],
    category: "Торты",
    access: "free",
    views: 5630,
    likes: 891,
    comments: 134,
    published: true,
    publishedAt: "2026-04-28",
    createdAt: "2026-04-20",
  },
  {
    id: "rc8",
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    type: "recipe",
    title: "Зеркальная глазурь: идеальный глянец",
    description:
      "Профессиональный рецепт зеркальной глазури для муссовых тортов. Получается идеальный глянец без пузырьков. Рецепт с точными температурами и техникой заливки.",
    coverImage: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
    prepTime: 30,
    cookTime: 15,
    totalTime: 240,
    difficulty: "hard",
    servings: 1,
    ingredients: [
      { name: "Сахар", amount: "300", unit: "г" },
      { name: "Вода", amount: "150", unit: "мл" },
      { name: "Глюкозный сироп", amount: "300", unit: "г" },
      { name: "Сгущённое молоко", amount: "200", unit: "г" },
      { name: "Белый шоколад", amount: "300", unit: "г" },
      { name: "Желатин листовой", amount: "20", unit: "г" },
      { name: "Краситель пищевой гелевый", amount: "по желанию", unit: "" },
    ],
    steps: [
      { title: "Подготовка желатина", description: "Замочить листовой желатин в ледяной воде на 10 минут до полного размягчения." },
      { title: "Сироп", description: "В кастрюле смешать сахар, воду и глюкозный сироп. Довести до 103°C. Снять с огня." },
      { title: "Шоколад", description: "В горячий сироп добавить измельчённый белый шоколад, перемешать до полного растворения." },
      { title: "Сборка", description: "Добавить отжатый желатин и сгущёнку. Пробить блендером (иммерсионным) под углом 45°, чтобы не было пузырьков." },
      { title: "Окраска", description: "Добавить гелевый краситель, снова пробить. Процедить через сито." },
      { title: "Остывание", description: "Остудить глазурь до 32-35°C. Торт должен быть полностью заморожен (-18°C)." },
      { title: "Заливка", description: "Поставить торт на стакан над противнем. Выливать глазурь по центру круговыми движениями. Излишки стекут." },
    ],
    tips: [
      "Температура глазури 32-35°C — критично!",
      "Торт должен быть полностью заморожен",
      "Не трогайте глазурь после заливки — дайте застыть",
      "Излишки можно собрать и использовать повторно",
      "Глюкозный сироп можно заменить инвертным",
    ],
    tags: ["зеркальная глазурь", "муссовый торт", "глазурь", "профессиональный"],
    category: "Техники",
    access: "free",
    views: 3890,
    likes: 645,
    comments: 92,
    published: true,
    publishedAt: "2026-05-12",
    createdAt: "2026-05-05",
  },
  {
    id: "rc9",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    type: "recipe",
    title: "Птичье молоко: советская классика",
    description:
      "Легендарный торт «Птичье молоко» — воздушный суфле на агаре, шоколадная глазурь и нежный бисквит. Рецепт, максимально приближенный к оригиналу ГУМа.",
    coverImage: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800",
    prepTime: 45,
    cookTime: 20,
    totalTime: 300,
    difficulty: "hard",
    servings: 10,
    ingredients: [
      { name: "Яйца (для бисквита)", amount: "2", unit: "шт" },
      { name: "Сахар (бисквит)", amount: "100", unit: "г" },
      { name: "Мука (бисквит)", amount: "100", unit: "г" },
      { name: "Яичные белки (суфле)", amount: "3", unit: "шт" },
      { name: "Сахар (суфле)", amount: "300", unit: "г" },
      { name: "Вода (суфле)", amount: "150", unit: "мл" },
      { name: "Агар-агар", amount: "4", unit: "ч.л." },
      { name: "Сливочное масло", amount: "200", unit: "г" },
      { name: "Сгущённое молоко", amount: "100", unit: "г" },
      { name: "Лимонная кислота", amount: "0.5", unit: "ч.л." },
      { name: "Тёмный шоколад", amount: "150", unit: "г" },
      { name: "Сливочное масло (глазурь)", amount: "30", unit: "г" },
    ],
    steps: [
      { title: "Бисквит", description: "Взбить яйца с сахаром, добавить муку. Выпекать 20 мин при 180°C. Остудить, разрезать на 2 коржа." },
      { title: "Сироп с агаром", description: "Смешать воду, сахар и агар. Варить до 110°C (густой сироп). Добавить лимонную кислоту." },
      { title: "Белковая масса", description: "Взбить белки в крепкую пень. Тонкой струйкой влить горячий сироп, продолжая взбивать." },
      { title: "Масляный крем", description: "Взбить мягкое масло со сгущёнкой. По ложке добавить в белковую массу, аккуратно перемешать." },
      { title: "Сборка", description: "На бисквит выложить суфле (оно быстро застывает от агара!). Накрыть вторым коржом." },
      { title: "Глазурь", description: "Растопить шоколад с маслом. Залить торт. Охладить 2 часа." },
    ],
    tips: [
      "Агар-агар нельзя заменить желатином — структура будет другой",
      "Суфле застывает за 15 минут — работайте быстро",
      "Температура сиропа критична — нужен термометр",
      "Масло для крема должно быть комнатной температуры",
    ],
    tags: ["птичье молоко", "суфле", "агар", "советская классика", "шоколад"],
    category: "Торты",
    access: "free",
    views: 4720,
    likes: 723,
    comments: 108,
    published: true,
    publishedAt: "2026-04-15",
    createdAt: "2026-04-08",
  },
  {
    id: "rc10",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    type: "recipe",
    title: "Чизкейк Нью-Йорк: без трещин",
    description:
      "Идеальный чизкейк Нью-Йорк с кремовой текстурой. Техника водяной бани предотвращает трещины. Печенье «Джонни» для основы, сливочный сыр «Филадельфия» для начинки.",
    coverImage: "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=800",
    prepTime: 30,
    cookTime: 75,
    totalTime: 345,
    difficulty: "medium",
    servings: 12,
    ingredients: [
      { name: "Печенье песочное", amount: "300", unit: "г" },
      { name: "Сливочное масло", amount: "150", unit: "г" },
      { name: "Сливочный сыр", amount: "900", unit: "г" },
      { name: "Сахар", amount: "250", unit: "г" },
      { name: "Яйца", amount: "4", unit: "шт" },
      { name: "Сметана 20%", amount: "200", unit: "г" },
      { name: "Ванильный экстракт", amount: "1", unit: "ч.л." },
      { name: "Цедра лимона", amount: "1", unit: "шт" },
    ],
    steps: [
      { title: "Основа", description: "Измельчить печенье в крошку. Растопить масло, смешать. Утрамбовать в форму (24 см), охладить 30 мин." },
      { title: "Начинка", description: "Взбить сливочный сыр с сахаром на низкой скорости. Добавить яйца по одному, не перевзбивая." },
      { title: "Дополнение", description: "Добавить сметану, ваниль, цедру. Перемешать лопаткой. Вылить на основу." },
      { title: "Водяная баня", description: "Завернуть форму в фольгу (2 слоя). Поставить в большее противень с кипятком (2 см)." },
      { title: "Выпечка", description: "Выпекать 75 минут при 160°C. Края должны схватиться, центр — слегка дрожать." },
      { title: "Остывание", description: "Остудить в духовке с приоткрытой дверцей 1 час. Затем в холодильнике минимум 4 часа (лучше ночь)." },
    ],
    tips: [
      "Все ингредиенты комнатной температуры!",
      "Не перевзбивайте — иначе будут пузыри и трещины",
      "Водяная баня обязательна для кремовой текстуры",
      "Фольга должна быть герметичной — вода не должна попасть",
      "Центр должен «дрожать» при покачивании формы",
    ],
    tags: ["чизкейк", "нью-йорк", "сливочный сыр", "водяная баня"],
    category: "Торты",
    access: "free",
    views: 6210,
    likes: 945,
    comments: 156,
    published: true,
    publishedAt: "2026-03-20",
    createdAt: "2026-03-15",
  },
  {
    id: "rc11",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    type: "recipe",
    title: "Эклеры с заварным кремом: пошагово",
    description:
      "Идеальные французские эклеры — хрустящее заварное тесто, нежный ванильный крем, зеркальная помадка. Рецепт с техникой отсадки и секретами полых внутри пирожных.",
    coverImage: "https://images.unsplash.com/photo-1612203985729-70726954388c?w=800",
    prepTime: 40,
    cookTime: 25,
    totalTime: 90,
    difficulty: "medium",
    servings: 15,
    ingredients: [
      { name: "Вода", amount: "250", unit: "мл" },
      { name: "Сливочное масло", amount: "100", unit: "г" },
      { name: "Сахар", amount: "1", unit: "ч.л." },
      { name: "Соль", amount: "0.5", unit: "ч.л." },
      { name: "Мука пшеничная", amount: "150", unit: "г" },
      { name: "Яйца", amount: "4", unit: "шт" },
      { name: "Молоко", amount: "500", unit: "мл" },
      { name: "Желтки", amount: "4", unit: "шт" },
      { name: "Сахар (крем)", amount: "100", unit: "г" },
      { name: "Кукурузный крахмал", amount: "40", unit: "г" },
      { name: "Ваниль", amount: "1", unit: "стручок" },
    ],
    steps: [
      { title: "Заварное тесто", description: "Воду с маслом, солью, сахаром довести до кипения. Всыпать муку, быстро вымесить лопаткой до плёнки на дне." },
      { title: "Остывание и яйца", description: "Тесто остудить до 60°C. Вбивать яйца по одному, каждый раз тщательно вмешивая. Тесто должно стекать лентой." },
      { title: "Отсадка", description: "Отсадить эклеры длиной 12 см через мешок с насадкой. Разгладить пики влажным пальцем." },
      { title: "Выпечка", description: "Выпекать 25 минут при 200°C. Первые 15 минут НЕ ОТКРЫВАТЬ духовку! Остудить на решётке." },
      { title: "Крем", description: "Молоко с ванилью закипятить. Желтки взбить с сахаром и крахмалом. Влить горячее молоко, вернуть на огонь до загустения." },
      { title: "Сборка", description: "Проколоть эклеры с двух сторон. Наполнить кремом через мешок. Сверху покрыть помадкой." },
    ],
    tips: [
      "Тесто должно быть тёплым при добавлении яиц (60°C)",
      "Консистенция — «стекает лентой» с лопатки",
      "Духовку НЕ открывать первые 15 минут!",
      "Эклеры должны быть полностью полыми внутри",
      "Крем должен быть холодным при наполнении",
    ],
    tags: ["эклеры", "заварное тесто", "французская кухня", "крем"],
    category: "Пирожные",
    access: "free",
    views: 3420,
    likes: 567,
    comments: 89,
    published: true,
    publishedAt: "2026-05-30",
    createdAt: "2026-05-25",
  },
  {
    id: "rc12",
    confectionerId: "c4",
    confectionerName: "Сахарный Лебедь",
    confectionerAvatar: "https://i.pravatar.cc/150?img=20",
    type: "recipe",
    title: "ПП-торт без сахара: банан-овсяный",
    description:
      "Полезный торт без сахара и белой муки. Сладость от бананов, основа из овсянки, крем из греческого йогурта. Идеально для тех, кто следит за питанием, но хочет десерт.",
    coverImage: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800",
    prepTime: 25,
    cookTime: 20,
    totalTime: 180,
    difficulty: "easy",
    servings: 8,
    ingredients: [
      { name: "Спелые бананы", amount: "3", unit: "шт" },
      { name: "Овсяные хлопья", amount: "200", unit: "г" },
      { name: "Яйца", amount: "2", unit: "шт" },
      { name: "Мёд", amount: "2", unit: "ст.л." },
      { name: "Разрыхлитель", amount: "1", unit: "ч.л." },
      { name: "Греческий йогурт 2%", amount: "400", unit: "г" },
      { name: "Творог мягкий 5%", amount: "200", unit: "г" },
      { name: "Стевия", amount: "по вкусу", unit: "" },
      { name: "Ягоды свежие", amount: "200", unit: "г" },
    ],
    steps: [
      { title: "Коржи", description: "Размять бананы вилкой. Смешать с овсянкой, яйцами, мёдом и разрыхлителем. Выпекать 2 коржа 20 мин при 180°C." },
      { title: "Крем", description: "Взбить йогурт с творогом и стевией до однородности. Охладить 30 минут." },
      { title: "Сборка", description: "Корж → крем → ягоды → корж → крем → ягоды. Украсить свежими ягодами." },
      { title: "Пропитка", description: "Оставить в холодильнике минимум 2 часа. Коржи пропитаются кремом и станут мягкими." },
    ],
    tips: [
      "Бананы должны быть очень спелыми (с чёрными точками)",
      "Овсянку можно смолоть в муку для более нежной текстуры",
      "Стевию добавляйте понемногу — она слаще сахара",
      "Калорийность: 145 ккал на 100г, БЖУ: 8/3/21",
    ],
    tags: ["ПП", "без сахара", "банан", "овсянка", "диетический", "без выпечки"],
    category: "ПП-десерты",
    access: "free",
    views: 2890,
    likes: 612,
    comments: 95,
    published: true,
    publishedAt: "2026-06-25",
    createdAt: "2026-06-20",
  },
  {
    id: "rc13",
    confectionerId: "c2",
    confectionerName: "Кондитерская Купец",
    confectionerAvatar: "https://i.pravatar.cc/150?img=23",
    type: "recipe",
    title: "Тирамису: классический итальянский",
    description:
      "Настоящий тирамису с маскарпоне, espresso и Marsala. Без яиц в сыром виде — используем технику на водяной бане. Печенье савоярди, пропитанное кофе, и нежнейший крем.",
    coverImage: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
    prepTime: 30,
    cookTime: 10,
    totalTime: 300,
    difficulty: "medium",
    servings: 8,
    ingredients: [
      { name: "Маскарпоне", amount: "500", unit: "г" },
      { name: "Яйца", amount: "4", unit: "шт" },
      { name: "Сахар", amount: "100", unit: "г" },
      { name: "Печенье савоярди", amount: "300", unit: "г" },
      { name: "Кофе espresso", amount: "300", unit: "мл" },
      { name: "Вино Marsala", amount: "50", unit: "мл" },
      { name: "Какао-порошок", amount: "30", unit: "г" },
    ],
    steps: [
      { title: "Крем", description: "Желтки взбить с сахаром на водяной бане до густоты (5-7 мин). Снять, остудить." },
      { title: "Маскарпоне", description: "Вмешать маскарпоне в остывшие желтки. Взбить белки в крепкую пень, аккуратно вмешать лопаткой." },
      { title: "Кофе", description: "Сварить espresso, добавить Marsala, остудить. Окунать савоярди на 1 секунду (не дольше!)." },
      { title: "Сборка", description: "Слой печенья → слой крема → слой печенья → слой крема. Верх посыпать какао через сито." },
      { title: "Пропитка", description: "Минимум 4 часа в холодильнике, лучше на ночь." },
    ],
    tips: [
      "Савоярди окунаем на 1 секунду — иначе раскиснут",
      "Желтки на водяной бане — безопасно, без сальмонеллы",
      "Marsala можно заменить амаретто или пропустить",
      "Какао посыпать только перед подачей",
    ],
    tags: ["тирамису", "итальянская кухня", "маскарпоне", "кофе", "без выпечки"],
    category: "Десерты",
    access: "free",
    views: 4180,
    likes: 734,
    comments: 67,
    published: true,
    publishedAt: "2026-04-05",
    createdAt: "2026-03-28",
  },
  {
    id: "rc14",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    type: "recipe",
    title: "Праздничный красный бархат",
    description:
      "Торт «Красный бархат» — насыщенный цвет, влажная текстура, крем-чиз. Идеальный торт для дня рождения или свадьбы. Техника многослойности и декора.",
    coverImage: "https://images.unsplash.com/photo-1586788680434-90d5d4f3e1a5?w=800",
    prepTime: 45,
    cookTime: 30,
    totalTime: 240,
    difficulty: "medium",
    servings: 12,
    ingredients: [
      { name: "Мука пшеничная", amount: "350", unit: "г" },
      { name: "Сахар", amount: "300", unit: "г" },
      { name: "Какао-порошок", amount: "30", unit: "г" },
      { name: "Сода", amount: "1", unit: "ч.л." },
      { name: "Соль", amount: "0.5", unit: "ч.л." },
      { name: "Яйца", amount: "3", unit: "шт" },
      { name: "Растительное масло", amount: "300", unit: "мл" },
      { name: "Кефир", amount: "300", unit: "мл" },
      { name: "Красный пищевой краситель", amount: "30", unit: "мл" },
      { name: "Уксус яблочный", amount: "1", unit: "ч.л." },
      { name: "Ванильный экстракт", amount: "1", unit: "ч.л." },
      { name: "Творожный сыр (крем)", amount: "600", unit: "г" },
      { name: "Сливочное масло (крем)", amount: "100", unit: "г" },
      { name: "Сахарная пудра (крем)", amount: "200", unit: "г" },
    ],
    steps: [
      { title: "Сухие ингредиенты", description: "Просеять муку, какао, соду, соль. Перемешать." },
      { title: "Жидкие ингредиенты", description: "Взбить яйца с сахаром, добавить масло, кефир, краситель, уксус, ваниль." },
      { title: "Тесто", description: "Соединить сухие и жидкие. Тесто должно быть насыщенно-красным и льющимся." },
      { title: "Выпечка", description: "Выпекать 2 коржа (24 см) 30 минут при 180°C. Остудить полностью, разрезать на 4." },
      { title: "Крем-чиз", description: "Взбить масло с пудрой, добавить творожный сыр, ваниль. Не перевзбивать!" },
      { title: "Сборка", description: "4 коржа × 3 слоя крема. Обмазать снаружи, украсить крошкой из обрезков." },
    ],
    tips: [
      "Краситель — гелевый даёт насыщенный цвет",
      "Кефир + уксус + сода = реакция, дающая пышность",
      "Коржи должны полностью остыть перед нарезкой",
      "Крем-чиз не перевзбивать — иначе расслоится",
      "Влажная текстура — это правильно, не пересушите!",
    ],
    tags: ["красный бархат", "торт", "крем-чиз", "праздничный", "день рождения"],
    category: "Торты",
    access: "free",
    views: 5340,
    likes: 812,
    comments: 143,
    published: true,
    publishedAt: "2026-02-28",
    createdAt: "2026-02-20",
  },
  {
    id: "rc15",
    confectionerId: "c3",
    confectionerName: "Татьяна-Кондитер",
    confectionerAvatar: "https://i.pravatar.cc/150?img=44",
    type: "recipe",
    title: "Карамельный бенто-торт: мини-формат",
    description:
      "Модный бенто-торт (диаметр 10-12 см) с солёной карамелью. Идеальный формат для одного-двух человек. Подарочная упаковка, личная надпись. Рецепт адаптирован для домашних кондитеров.",
    coverImage: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800",
    prepTime: 30,
    cookTime: 20,
    totalTime: 120,
    difficulty: "easy",
    servings: 2,
    ingredients: [
      { name: "Мука", amount: "100", unit: "г" },
      { name: "Сахар", amount: "80", unit: "г" },
      { name: "Яйцо", amount: "1", unit: "шт" },
      { name: "Сливочное масло", amount: "40", unit: "г" },
      { name: "Молоко", amount: "50", unit: "мл" },
      { name: "Разрыхлитель", amount: "0.5", unit: "ч.л." },
      { name: "Сахар (карамель)", amount: "100", unit: "г" },
      { name: "Сливки 33% (карамель)", amount: "100", unit: "мл" },
      { name: "Соль морская (карамель)", amount: "0.5", unit: "ч.л." },
      { name: "Сливочное масло (карамель)", amount: "30", unit: "г" },
      { name: "Сливочный сыр (крем)", amount: "150", unit: "г" },
      { name: "Сахарная пудра", amount: "50", unit: "г" },
    ],
    steps: [
      { title: "Бисквит", description: "Взбить яйцо с сахаром, добавить растопленное масло и молоко. Всыпать муку с разрыхлителем. Выпекать 20 мин при 180°C в форме 12 см." },
      { title: "Солёная карамель", description: "Растопить сахар до янтарного цвета. Влить тёплые сливки (осторожно!). Добавить масло, соль. Остудить." },
      { title: "Крем", description: "Взбить сливочный сыр с пудрой. Вмешать 2 ст.л. карамели." },
      { title: "Сборка", description: "Разрезать бисквит на 3 коржа. Промазать кремом с карамелью. Снаружи — тонкий слой крема, полить карамелью." },
      { title: "Декор", description: "Отсадить розочки, добавить надпись шоколадом. Упаковать в бенто-коробку." },
    ],
    tips: [
      "Бенто-торт = 10-12 см диаметром, 5-6 см высотой",
      "Карамель: вливайте сливки осторожно — пар обжигает!",
      "Надпись делайте растопленным шоколадом через корнетик",
      "Отличный формат для подарка или доставки",
      "Цена продажи: 800-1500₽ за штуку",
    ],
    tags: ["бенто-торт", "карамель", "мини", "подарок", "для начинающих"],
    category: "Торты",
    access: "free",
    views: 3160,
    likes: 489,
    comments: 72,
    published: true,
    publishedAt: "2026-06-28",
    createdAt: "2026-06-22",
  },
];

// ===== СКЛАД (для кондитера c1) =====
export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: "inv1",
    confectionerId: "c1",
    name: "Мука пшеничная высший сорт",
    category: "Мука",
    unit: "kg",
    quantity: 12.5,
    minQuantity: 5,
    costPerUnit: 65,
    supplierId: "s1",
    supplierName: "Мукомольная компания «Колос»",
    expiryDate: "2026-12-01",
    storageLocation: "Стеллаж А-1",
    lastRestocked: "2026-06-20",
    createdAt: "2026-01-15",
    updatedAt: "2026-06-20",
  },
  {
    id: "inv2",
    confectionerId: "c1",
    name: "Сахар-песок",
    category: "Сахар",
    unit: "kg",
    quantity: 3.2,
    minQuantity: 5,
    costPerUnit: 60,
    supplierId: "s1",
    supplierName: "Мукомольная компания «Колос»",
    expiryDate: "2027-06-01",
    storageLocation: "Стеллаж А-2",
    lastRestocked: "2026-06-15",
    createdAt: "2026-01-15",
    updatedAt: "2026-06-15",
  },
  {
    id: "inv3",
    confectionerId: "c1",
    name: "Сливочное масло 82.5%",
    category: "Молочные продукты",
    unit: "kg",
    quantity: 4.8,
    minQuantity: 3,
    costPerUnit: 850,
    supplierId: "s3",
    supplierName: "Сливочный край",
    expiryDate: "2026-07-15",
    storageLocation: "Холодильник 1",
    lastRestocked: "2026-06-25",
    createdAt: "2026-02-10",
    updatedAt: "2026-06-25",
  },
  {
    id: "inv4",
    confectionerId: "c1",
    name: "Сливки 33%",
    category: "Молочные продукты",
    unit: "l",
    quantity: 1.5,
    minQuantity: 3,
    costPerUnit: 290,
    supplierId: "s3",
    supplierName: "Сливочный край",
    expiryDate: "2026-07-05",
    storageLocation: "Холодильник 1",
    lastRestocked: "2026-06-28",
    createdAt: "2026-02-10",
    updatedAt: "2026-06-28",
  },
  {
    id: "inv5",
    confectionerId: "c1",
    name: "Яйца куриные С1",
    category: "Яйца",
    unit: "pc",
    quantity: 60,
    minQuantity: 30,
    costPerUnit: 12,
    supplierId: "s3",
    supplierName: "Сливочный край",
    expiryDate: "2026-07-10",
    storageLocation: "Холодильник 2",
    lastRestocked: "2026-06-27",
    createdAt: "2026-01-20",
    updatedAt: "2026-06-27",
  },
  {
    id: "inv6",
    confectionerId: "c1",
    name: "Шоколад тёмный 54%",
    category: "Шоколад",
    unit: "kg",
    quantity: 2.1,
    minQuantity: 1,
    costPerUnit: 1190,
    supplierId: "s2",
    supplierName: "Шоколад-Опт",
    expiryDate: "2027-03-01",
    storageLocation: "Стеллаж Б-1",
    lastRestocked: "2026-06-10",
    createdAt: "2026-03-05",
    updatedAt: "2026-06-10",
  },
  {
    id: "inv7",
    confectionerId: "c1",
    name: "Малина замороженная",
    category: "Ягоды",
    unit: "kg",
    quantity: 0.8,
    minQuantity: 1,
    costPerUnit: 540,
    supplierId: "s4",
    supplierName: "Ягоды-Опт",
    expiryDate: "2027-01-01",
    storageLocation: "Морозильник 1",
    lastRestocked: "2026-06-18",
    createdAt: "2026-04-12",
    updatedAt: "2026-06-18",
  },
  {
    id: "inv8",
    confectionerId: "c1",
    name: "Клубника свежая",
    category: "Ягоды",
    unit: "kg",
    quantity: 1.2,
    minQuantity: 0.5,
    costPerUnit: 760,
    supplierId: "s4",
    supplierName: "Ягоды-Опт",
    expiryDate: "2026-07-03",
    storageLocation: "Холодильник 1",
    lastRestocked: "2026-06-29",
    createdAt: "2026-06-29",
    updatedAt: "2026-06-29",
  },
  {
    id: "inv9",
    confectionerId: "c1",
    name: "Коробки для тортов 30см",
    category: "Упаковка",
    unit: "pc",
    quantity: 24,
    minQuantity: 10,
    costPerUnit: 45,
    storageLocation: "Стеллаж В-1",
    lastRestocked: "2026-06-05",
    createdAt: "2026-05-10",
    updatedAt: "2026-06-05",
  },
  {
    id: "inv10",
    confectionerId: "c1",
    name: "Подложки усиленные 28см",
    category: "Упаковка",
    unit: "pc",
    quantity: 8,
    minQuantity: 15,
    costPerUnit: 35,
    storageLocation: "Стеллаж В-2",
    lastRestocked: "2026-05-20",
    createdAt: "2026-05-10",
    updatedAt: "2026-05-20",
  },
  {
    id: "inv11",
    confectionerId: "c1",
    name: "Сахарная пудра",
    category: "Сахар",
    unit: "kg",
    quantity: 2.8,
    minQuantity: 2,
    costPerUnit: 110,
    storageLocation: "Стеллаж А-2",
    lastRestocked: "2026-06-22",
    createdAt: "2026-02-15",
    updatedAt: "2026-06-22",
  },
  {
    id: "inv12",
    confectionerId: "c1",
    name: "Ванильный экстракт",
    category: "Ароматизаторы",
    unit: "ml",
    quantity: 180,
    minQuantity: 100,
    costPerUnit: 8,
    storageLocation: "Стеллаж Б-2",
    expiryDate: "2027-12-01",
    lastRestocked: "2026-05-15",
    createdAt: "2026-03-20",
    updatedAt: "2026-05-15",
  },
];

// Движения по складу (последние)
export const MOCK_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: "sm1",
    itemId: "inv1",
    itemName: "Мука пшеничная высший сорт",
    type: "incoming",
    quantity: 10,
    unit: "kg",
    reason: "Поставка от «Колос»",
    costPerUnit: 65,
    totalCost: 650,
    date: "2026-06-20T10:00:00",
    createdBy: "Мария Уездная",
  },
  {
    id: "sm2",
    itemId: "inv1",
    itemName: "Мука пшеничная высший сорт",
    type: "outgoing",
    quantity: 1.5,
    unit: "kg",
    reason: "Заказ UK-2025-0005",
    orderId: "o5",
    costPerUnit: 65,
    totalCost: 97,
    date: "2026-06-26T14:00:00",
    createdBy: "Мария Уездная",
  },
  {
    id: "sm3",
    itemId: "inv3",
    itemName: "Сливочное масло 82.5%",
    type: "incoming",
    quantity: 5,
    unit: "kg",
    reason: "Поставка от «Сливочный край»",
    costPerUnit: 850,
    totalCost: 4250,
    date: "2026-06-25T09:30:00",
    createdBy: "Мария Уездная",
  },
  {
    id: "sm4",
    itemId: "inv8",
    itemName: "Клубника свежая",
    type: "incoming",
    quantity: 2,
    unit: "kg",
    reason: "Поставка от «Ягоды-Опт»",
    costPerUnit: 760,
    totalCost: 1520,
    date: "2026-06-29T08:00:00",
    createdBy: "Мария Уездная",
  },
  {
    id: "sm5",
    itemId: "inv2",
    itemName: "Сахар-песок",
    type: "waste",
    quantity: 0.3,
    unit: "kg",
    reason: "Рассыпано при транспортировке",
    costPerUnit: 60,
    totalCost: 18,
    date: "2026-06-28T16:00:00",
    createdBy: "Мария Уездная",
  },
  {
    id: "sm6",
    itemId: "inv4",
    itemName: "Сливки 33%",
    type: "outgoing",
    quantity: 0.5,
    unit: "l",
    reason: "Заказ UK-2025-0004",
    orderId: "o4",
    costPerUnit: 290,
    totalCost: 145,
    date: "2026-06-29T11:00:00",
    createdBy: "Мария Уездная",
  },
];

// ===== ТАБЛИЦА ГАНТА (для кондитера c1) =====
// Сегодня = 2026-06-30, неделя = 30/06 - 06/07
export const MOCK_GANTT_TASKS: GanttTask[] = [
  // Заказ UK-2025-0005 — срочный, готов сегодня
  {
    id: "g1",
    orderId: "o5",
    orderNumber: "UK-2025-0005",
    customerName: "Дмитрий Петров",
    productName: "Торт «Уездный классический»",
    stage: "decorating",
    stageLabel: "Декорирование",
    startDate: "2026-06-30T08:00:00",
    endDate: "2026-06-30T12:00:00",
    duration: 240,
    status: "in_progress",
    progress: 65,
    assignee: "Мария",
    color: "oklch(0.55 0.18 25)",
    reminderAt: "2026-06-30T11:00:00",
    reminderSent: false,
  },
  {
    id: "g2",
    orderId: "o5",
    orderNumber: "UK-2025-0005",
    customerName: "Дмитрий Петров",
    productName: "Торт «Уездный классический»",
    stage: "packaging",
    stageLabel: "Упаковка",
    startDate: "2026-06-30T12:00:00",
    endDate: "2026-06-30T13:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.70 0.14 70)",
    dependsOn: ["g1"],
    reminderAt: "2026-06-30T12:30:00",
    reminderSent: false,
  },
  {
    id: "g3",
    orderId: "o5",
    orderNumber: "UK-2025-0005",
    customerName: "Дмитрий Петров",
    productName: "Торт «Уездный классический»",
    stage: "delivery_prep",
    stageLabel: "Подготовка к выдаче",
    startDate: "2026-06-30T13:00:00",
    endDate: "2026-06-30T14:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.78 0.16 80)",
    dependsOn: ["g2"],
    reminderAt: "2026-06-30T13:30:00",
    reminderSent: false,
  },
  // Заказ UK-2025-0004 — капкейки на 3 июля
  {
    id: "g4",
    orderId: "o4",
    orderNumber: "UK-2025-0004",
    customerName: "Ольга Иванова",
    productName: "Набор капкейков «Праздничный»",
    stage: "preparation",
    stageLabel: "Подготовка ингредиентов",
    startDate: "2026-07-02T09:00:00",
    endDate: "2026-07-02T10:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Светлана",
    color: "oklch(0.65 0.10 145)",
    reminderAt: "2026-07-02T08:30:00",
    reminderSent: false,
  },
  {
    id: "g5",
    orderId: "o4",
    orderNumber: "UK-2025-0004",
    customerName: "Ольга Иванова",
    productName: "Набор капкейков «Праздничный»",
    stage: "baking",
    stageLabel: "Выпечка",
    startDate: "2026-07-02T10:00:00",
    endDate: "2026-07-02T12:30:00",
    duration: 150,
    status: "pending",
    progress: 0,
    assignee: "Светлана",
    color: "oklch(0.65 0.10 145)",
    dependsOn: ["g4"],
    reminderAt: "2026-07-02T12:00:00",
    reminderSent: false,
  },
  {
    id: "g6",
    orderId: "o4",
    orderNumber: "UK-2025-0004",
    customerName: "Ольга Иванова",
    productName: "Набор капкейков «Праздничный»",
    stage: "cooling",
    stageLabel: "Охлаждение",
    startDate: "2026-07-02T12:30:00",
    endDate: "2026-07-02T14:00:00",
    duration: 90,
    status: "pending",
    progress: 0,
    assignee: "Светлана",
    color: "oklch(0.65 0.10 145)",
    dependsOn: ["g5"],
  },
  {
    id: "g7",
    orderId: "o4",
    orderNumber: "UK-2025-0004",
    customerName: "Ольга Иванова",
    productName: "Набор капкейков «Праздничный»",
    stage: "decorating",
    stageLabel: "Декорирование",
    startDate: "2026-07-02T14:00:00",
    endDate: "2026-07-02T17:00:00",
    duration: 180,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.55 0.18 25)",
    dependsOn: ["g6"],
    reminderAt: "2026-07-02T16:30:00",
    reminderSent: false,
  },
  {
    id: "g8",
    orderId: "o4",
    orderNumber: "UK-2025-0004",
    customerName: "Ольга Иванова",
    productName: "Набор капкейков «Праздничный»",
    stage: "packaging",
    stageLabel: "Упаковка",
    startDate: "2026-07-02T17:00:00",
    endDate: "2026-07-02T18:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.70 0.14 70)",
    dependsOn: ["g7"],
  },
  // Заказ UK-2025-0006 — печенье на 4 июля
  {
    id: "g9",
    orderId: "o6",
    orderNumber: "UK-2025-0006",
    customerName: "Екатерина Смирнова",
    productName: "Печенье «Имбирное уездное» (20 шт)",
    stage: "preparation",
    stageLabel: "Подготовка",
    startDate: "2026-07-03T10:00:00",
    endDate: "2026-07-03T11:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Светлана",
    color: "oklch(0.65 0.10 145)",
    reminderAt: "2026-07-03T09:30:00",
    reminderSent: false,
  },
  {
    id: "g10",
    orderId: "o6",
    orderNumber: "UK-2025-0006",
    customerName: "Екатерина Смирнова",
    productName: "Печенье «Имбирное уездное» (20 шт)",
    stage: "baking",
    stageLabel: "Выпечка",
    startDate: "2026-07-03T11:00:00",
    endDate: "2026-07-03T13:00:00",
    duration: 120,
    status: "pending",
    progress: 0,
    assignee: "Светлана",
    color: "oklch(0.65 0.10 145)",
    dependsOn: ["g9"],
  },
  {
    id: "g11",
    orderId: "o6",
    orderNumber: "UK-2025-0006",
    customerName: "Екатерина Смирнова",
    productName: "Печенье «Имбирное уездное» (20 шт)",
    stage: "decorating",
    stageLabel: "Роспись",
    startDate: "2026-07-03T14:00:00",
    endDate: "2026-07-03T18:00:00",
    duration: 240,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.55 0.18 25)",
    dependsOn: ["g10"],
    reminderAt: "2026-07-03T17:00:00",
    reminderSent: false,
  },
  {
    id: "g12",
    orderId: "o6",
    orderNumber: "UK-2025-0006",
    customerName: "Екатерина Смирнова",
    productName: "Печенье «Имбирное уездное» (20 шт)",
    stage: "packaging",
    stageLabel: "Упаковка",
    startDate: "2026-07-03T18:00:00",
    endDate: "2026-07-03T19:00:00",
    duration: 60,
    status: "pending",
    progress: 0,
    assignee: "Мария",
    color: "oklch(0.70 0.14 70)",
    dependsOn: ["g11"],
  },
  // Заказ UK-2025-0001 — уже доставляется
  {
    id: "g13",
    orderId: "o1",
    orderNumber: "UK-2025-0001",
    customerName: "Анна Соколова",
    productName: "Торт «Уездный классический»",
    stage: "delivery_prep",
    stageLabel: "Доставка",
    startDate: "2026-06-30T11:00:00",
    endDate: "2026-06-30T13:00:00",
    duration: 120,
    status: "in_progress",
    progress: 80,
    assignee: "Сергей (курьер)",
    color: "oklch(0.78 0.16 80)",
    reminderAt: "2026-06-30T12:30:00",
    reminderSent: false,
  },
];

// ===== НАПОМИНАНИЯ =====
export const MOCK_REMINDERS: Reminder[] = [
  {
    id: "rm1",
    type: "order_deadline",
    title: "Заказ UK-2025-0005 готовится к выдаче",
    description: "Декорирование завершено на 65%. До выдачи 2 часа.",
    orderId: "o5",
    dueDate: "2026-06-30T14:00:00",
    isRead: false,
    isDone: false,
    priority: "high",
    createdAt: "2026-06-30T08:00:00",
  },
  {
    id: "rm2",
    type: "order_deadline",
    title: "Капкейки UK-2025-0004 — начать завтра",
    description: "Заказ на 3 июля, 12:00. Начать подготовку в 9:00.",
    orderId: "o4",
    dueDate: "2026-07-02T09:00:00",
    isRead: false,
    isDone: false,
    priority: "medium",
    createdAt: "2026-06-29T18:00:00",
  },
  {
    id: "rm3",
    type: "restock",
    title: "Заканчивается сахар-песок",
    description: "Остаток 3.2 кг, минимум 5 кг. Закажите у «Колос».",
    itemId: "inv2",
    dueDate: "2026-07-01T10:00:00",
    isRead: false,
    isDone: false,
    priority: "urgent",
    createdAt: "2026-06-30T07:00:00",
  },
  {
    id: "rm4",
    type: "restock",
    title: "Заканчиваются сливки 33%",
    description: "Остаток 1.5 л, минимум 3 л. Срок годности истекает 5 июля.",
    itemId: "inv4",
    dueDate: "2026-07-02T09:00:00",
    isRead: false,
    isDone: false,
    priority: "high",
    createdAt: "2026-06-30T07:00:00",
  },
  {
    id: "rm5",
    type: "restock",
    title: "Заканчиваются подложки 28см",
    description: "Остаток 8 шт, минимум 15 шт.",
    itemId: "inv10",
    dueDate: "2026-07-03T10:00:00",
    isRead: true,
    isDone: false,
    priority: "medium",
    createdAt: "2026-06-29T15:00:00",
  },
  {
    id: "rm6",
    type: "expiry",
    title: "Истекает срок годности клубники",
    description: "Свежая клубника, остаток 1.2 кг. Использовать до 3 июля.",
    itemId: "inv8",
    dueDate: "2026-07-03T00:00:00",
    isRead: false,
    isDone: false,
    priority: "high",
    createdAt: "2026-06-30T07:00:00",
  },
  {
    id: "rm7",
    type: "promotion_end",
    title: "Акция «Счастливые часы» заканчивается 31 июля",
    description: "Использовано 14 раз из 100. Конверсия 3.3%.",
    promotionId: "pr8",
    dueDate: "2026-07-31T23:59:00",
    isRead: true,
    isDone: false,
    priority: "low",
    createdAt: "2026-06-28T10:00:00",
  },
  {
    id: "rm8",
    type: "promotion_end",
    title: "Промо-бюджет акции WELCOME15 почти исчерпан",
    description: "Из 5000 ₽ потрачено 4820 ₽. До 15 июля осталось 96% бюджета.",
    promotionId: "pr1",
    dueDate: "2026-07-15T00:00:00",
    isRead: false,
    isDone: false,
    priority: "medium",
    createdAt: "2026-06-30T09:00:00",
  },
  {
    id: "rm9",
    type: "review_request",
    title: "Запросить отзыв у Ольги Ивановой",
    description: "Заказ UK-2025-0002 завершён 15 дней назад. Отзыва нет.",
    orderId: "o2",
    dueDate: "2026-06-30T18:00:00",
    isRead: true,
    isDone: false,
    priority: "low",
    createdAt: "2026-06-28T12:00:00",
  },
  {
    id: "rm10",
    type: "order_deadline",
    title: "Имбирное печенье UK-2025-0006 — роспись 3 июля",
    description: "Роспись 20 шт печенья займёт 4 часа. Начать в 14:00.",
    orderId: "o6",
    dueDate: "2026-07-03T14:00:00",
    isRead: false,
    isDone: false,
    priority: "medium",
    createdAt: "2026-06-29T16:00:00",
  },
];

// ===== ТИПЫ АКЦИЙ =====
export const PROMOTION_TYPE_INFO: Record<
  string,
  { label: string; icon: string; color: string; description: string }
> = {
  discount_percent: {
    label: "Скидка %",
    icon: "percent",
    color: "bg-red-100 text-red-800 border-red-200",
    description: "Процентная скидка на заказ",
  },
  discount_fixed: {
    label: "Скидка ₽",
    icon: "tag",
    color: "bg-amber-100 text-amber-800 border-amber-200",
    description: "Фиксированная скидка в рублях",
  },
  free_delivery: {
    label: "Бесплатная доставка",
    icon: "truck",
    color: "bg-blue-100 text-blue-800 border-blue-200",
    description: "Доставка за счёт кондитера",
  },
  gift: {
    label: "Подарок",
    icon: "gift",
    color: "bg-purple-100 text-purple-800 border-purple-200",
    description: "Бесплатный товар к заказу",
  },
  bundle: {
    label: "Набор",
    icon: "package",
    color: "bg-emerald-100 text-emerald-800 border-emerald-200",
    description: "Скидка при покупке набора",
  },
  early_booking: {
    label: "Раннее бронирование",
    icon: "calendar",
    color: "bg-cyan-100 text-cyan-800 border-cyan-200",
    description: "Скидка при раннем заказе",
  },
  loyalty_bonus: {
    label: "Бонусы x2",
    icon: "star",
    color: "bg-amber-100 text-amber-800 border-amber-200",
    description: "Увеличенные бонусы за заказ",
  },
  happy_hours: {
    label: "Счастливые часы",
    icon: "clock",
    color: "bg-pink-100 text-pink-800 border-pink-200",
    description: "Скидка в определённые часы",
  },
  first_order: {
    label: "Первый заказ",
    icon: "user-plus",
    color: "bg-indigo-100 text-indigo-800 border-indigo-200",
    description: "Скидка новым клиентам",
  },
  holiday: {
    label: "Праздник",
    icon: "party-popper",
    color: "bg-rose-100 text-rose-800 border-rose-200",
    description: "Праздничная акция",
  },
};

// ===== ТИПЫ СЛОЖНОСТИ РЕЦЕПТОВ =====
export const RECIPE_DIFFICULTY_INFO: Record<string, { label: string; color: string; stars: number }> = {
  easy: { label: "Легко", color: "bg-emerald-100 text-emerald-800", stars: 1 },
  medium: { label: "Средне", color: "bg-amber-100 text-amber-800", stars: 2 },
  hard: { label: "Сложно", color: "bg-orange-100 text-orange-800", stars: 3 },
  expert: { label: "Эксперт", color: "bg-red-100 text-red-800", stars: 4 },
};

// ===== ЭТАПЫ ПРОИЗВОДСТВА =====
export const PRODUCTION_STAGES: Record<
  string,
  { label: string; color: string; icon: string; description: string }
> = {
  preparation: {
    label: "Подготовка",
    color: "oklch(0.65 0.10 145)",
    icon: "🔪",
    description: "Подготовка ингредиентов и инструментов",
  },
  baking: {
    label: "Выпечка",
    color: "oklch(0.70 0.14 70)",
    icon: "🔥",
    description: "Основной процесс выпекания",
  },
  cooling: {
    label: "Охлаждение",
    color: "oklch(0.70 0.10 200)",
    icon: "❄️",
    description: "Охлаждение и стабилизация",
  },
  assembling: {
    label: "Сборка",
    color: "oklch(0.65 0.12 305)",
    icon: "🏗️",
    description: "Сборка торта из коржей",
  },
  decorating: {
    label: "Декорирование",
    color: "oklch(0.55 0.18 25)",
    icon: "🎨",
    description: "Декорирование и финальные штрихи",
  },
  packaging: {
    label: "Упаковка",
    color: "oklch(0.70 0.14 70)",
    icon: "📦",
    description: "Упаковка в коробку",
  },
  delivery_prep: {
    label: "Подготовка к доставке",
    color: "oklch(0.78 0.16 80)",
    icon: "🚗",
    description: "Подготовка к выдаче/доставке",
  },
  completed: {
    label: "Завершено",
    color: "oklch(0.60 0.10 145)",
    icon: "✅",
    description: "Заказ завершён",
  },
};
