import type { ConfectionerWork } from "./types";

// ===== Моковые работы кондитеров для портфолио =====
// Каждая работа связана с кондитером через confectionerId (соответствует MOCK_CONFECTIONERS)
export const MOCK_CONFECTIONER_WORKS: ConfectionerWork[] = [
  // ===== ОСНОВНОЙ КОНДИТЕР (c0 — Волоколамск) =====
  {
    id: "work-000-wedding",
    confectionerId: "c0",
    confectionerName: "Торты на заказ | Сахарная печать",
    title: "Свадебный торт с сахарной печатью — фото молодожёнов",
    description: "Трёхъярусный свадебный торт. Верхний ярус — сахарная печать с фото молодожёнов. Бисквит «Красный бархат» с маскарпоне. Декор: живые цветы, съедобный жемчуг.",
    category: "cakes",
    categoryLabel: "Торты",
    images: ["https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800"],
    mainImage: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800",
    eventType: "wedding",
    weight: "5 кг",
    servings: 40,
    prepTime: "5 дней",
    price: 7500,
    city: "Волоколамск",
    tags: ["свадебный", "сахарная печать", "фото на торте", "3 яруса", "премиум"],
    fillings: ["Красный бархат", "Маскарпоне"],
    likes: 1,
    views: 15,
    featured: true,
    createdAt: "2026-07-01T10:00:00",
    status: "published",
  },
  {
    id: "work-000-christening",
    confectionerId: "c0",
    confectionerName: "Торты на заказ | Сахарная печать",
    title: "Торт на крестины с фото малыша",
    description: "Нежный торт на крестины. Сахарная печать — фото ребёнка. Ванильный бисквит с кремом пломбир. Декор: имя, ангелочек, крестильная тематика.",
    category: "cakes",
    categoryLabel: "Торты",
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800"],
    mainImage: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800",
    eventType: "christening",
    weight: "2 кг",
    servings: 16,
    prepTime: "3 дня",
    price: 3200,
    city: "Волоколамск",
    tags: ["крестины", "сахарная печать", "фото", "детский", "имя"],
    fillings: ["Ваниль", "Крем пломбир"],
    likes: 1,
    views: 10,
    featured: true,
    createdAt: "2026-07-02T14:00:00",
    status: "published",
  },
  {
    id: "work-000-birthday",
    confectionerId: "c0",
    confectionerName: "Торты на заказ | Сахарная печать",
    title: "Торт с фото на день рождения",
    description: "Торт с сахарной печатью — фото именинника. Шоколадный бисквит с ганашем. Декор: надпись, свечи, шоколадная стружка.",
    category: "cakes",
    categoryLabel: "Торты",
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800"],
    mainImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
    eventType: "birthday",
    weight: "1.5 кг",
    servings: 12,
    prepTime: "2 дня",
    price: 2700,
    city: "Волоколамск",
    tags: ["день рождения", "сахарная печать", "фото на торте", "шоколад"],
    fillings: ["Шоколад", "Ганаш"],
    likes: 1,
    views: 8,
    featured: true,
    createdAt: "2026-07-03T11:00:00",
    status: "published",
  },
  // ===== Остальные работы =====
  {
    id: "work-001",
    confectionerId: "c1",
    confectionerName: "Сладкая мастерская Анны",
    title: "Свадебный торт «Романтика» — 3 яруса",
    description: "Многоярусный свадебный торт с декором из живых цветов, белым шоколадом и съедобным жемчугом. Бисквит «Красный бархат» с крем-чизом маскарпоне.",
    category: "cakes",
    categoryLabel: "Торты",
    images: [
      "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800&h=800&fit=crop",
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800&h=800&fit=crop",
    eventType: "wedding",
    weight: "6 кг",
    servings: 50,
    prepTime: "5 дней",
    price: 12000,
    city: "Москва",
    tags: ["свадебный", "3 яруса", "живые цветы", "жемчуг", "премиум"],
    fillings: ["Красный бархат", "Маскарпоне", "Ваниль"],
    likes: 342,
    views: 4128,
    featured: true,
    createdAt: "2026-06-15T10:00:00",
    status: "published",
  },
  {
    id: "work-002",
    confectionerId: "c1",
    confectionerName: "Сладкая мастерская Анны",
    title: "Торт «Красный бархат» с маскарпоне",
    description: "Классический американский торт с нежными коржами красного цвета и кремом из маскарпоне. Украшен свежими ягодами.",
    category: "cakes",
    categoryLabel: "Торты",
    images: [
      "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&h=800&fit=crop",
    eventType: "birthday",
    weight: "1.5 кг",
    servings: 12,
    prepTime: "2 дня",
    price: 2800,
    city: "Москва",
    tags: ["красный бархат", "маскарпоне", "ягоды", "хит"],
    fillings: ["Маскарпоне", "Сливочный сыр"],
    likes: 218,
    views: 2840,
    featured: true,
    createdAt: "2026-06-10T14:30:00",
    status: "published",
  },
  {
    id: "work-003",
    confectionerId: "c1",
    confectionerName: "Сладкая мастерская Анны",
    title: "Чизкейк «Нью-Йорк» классический",
    description: "Настоящий нью-йоркский чизкейк на основе творожного сыра «Филадельфия» с песочной основой.",
    category: "cheesecakes",
    categoryLabel: "Чизкейки",
    images: [
      "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1567171466295-4afa63d45416?w=800&h=800&fit=crop",
    eventType: "just",
    weight: "1.2 кг",
    servings: 10,
    prepTime: "1 день",
    price: 1900,
    city: "Москва",
    tags: ["чизкейк", "нью-йорк", "классика"],
    fillings: ["Сливочный сыр"],
    likes: 156,
    views: 1920,
    featured: false,
    createdAt: "2026-05-28T09:15:00",
    status: "published",
  },

  // ===== Vanil House (c2) =====
  {
    id: "work-004",
    confectionerId: "c2",
    confectionerName: "Кондитерский дом «Ваниль»",
    title: "Корпоративный торт с логотипом",
    description: "Торт для корпоративного праздника с точной копией логотипа компании из шоколадной глазури. Вес 4 кг, 40 порций.",
    category: "cakes",
    categoryLabel: "Торты",
    images: [
      "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&h=800&fit=crop",
    eventType: "corporate",
    weight: "4 кг",
    servings: 40,
    prepTime: "3 дня",
    price: 6500,
    city: "Москва",
    tags: ["корпоратив", "логотип", "брендинг", "B2B"],
    fillings: ["Ваниль", "Шоколад"],
    likes: 89,
    views: 1240,
    featured: true,
    createdAt: "2026-06-20T11:00:00",
    status: "published",
  },
  {
    id: "work-005",
    confectionerId: "c2",
    confectionerName: "Кондитерский дом «Ваниль»",
    title: "Детский торт «Принцесса»",
    description: "Яркий детский торт с декором из мастики: корона, платье принцессы, волшебная палочка. Начинка — клубничный конфитюр.",
    category: "cakes",
    categoryLabel: "Торты",
    images: [
      "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=800&fit=crop",
    eventType: "kids",
    weight: "2.5 кг",
    servings: 20,
    prepTime: "3 дня",
    price: 4200,
    city: "Москва",
    tags: ["детский", "мастика", "принцесса", "день рождения"],
    fillings: ["Клубника", "Ваниль"],
    likes: 167,
    views: 2180,
    featured: false,
    createdAt: "2026-06-05T16:20:00",
    status: "published",
  },

  // ===== Maria Dessert (c3) =====
  {
    id: "work-006",
    confectionerId: "c3",
    confectionerName: "Мария Десерт",
    title: "Веганский торт «Авокадо-манго»",
    description: "Постный торт без молока и яиц. Основа из миндальной муки, крем из авокадо, начинка манго-маракуйя. Без рафинированного сахара.",
    category: "vegan",
    categoryLabel: "Веганские десерты",
    images: [
      "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800&h=800&fit=crop",
    eventType: "just",
    weight: "1.3 кг",
    servings: 10,
    prepTime: "2 дня",
    price: 2400,
    city: "Санкт-Петербург",
    tags: ["веганский", "без сахара", "постный", "авокадо", "манго"],
    fillings: ["Авокадо", "Манго-маракуйя"],
    likes: 287,
    views: 3240,
    featured: true,
    createdAt: "2026-06-18T12:00:00",
    status: "published",
  },
  {
    id: "work-007",
    confectionerId: "c3",
    confectionerName: "Мария Десерт",
    title: "Кето-торт с ягодами (без сахара)",
    description: "Низкоуглеводный торт для кето-диеты. Миндальная мука, эритрит вместо сахара, сливочный крем из маскарпоне.",
    category: "keto",
    categoryLabel: "Кето-десерты",
    images: [
      "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&h=800&fit=crop",
    eventType: "birthday",
    weight: "1 кг",
    servings: 8,
    prepTime: "2 дня",
    price: 2200,
    city: "Санкт-Петербург",
    tags: ["кето", "без сахара", "эритрит", "миндальная мука"],
    fillings: ["Маскарпоне", "Ягоды"],
    likes: 134,
    views: 1680,
    featured: false,
    createdAt: "2026-06-12T10:30:00",
    status: "published",
  },

  // ===== Chocolatier Dmitry (c4) =====
  {
    id: "work-008",
    confectionerId: "c4",
    confectionerName: "Шоколатье Дмитрий",
    title: "Набор шоколадных конфет ручной работы (16 шт)",
    description: "Авторские конфеты из бельгийского шоколада: пралине, трюфели, фисташковые, с морской солью и карамелью. Подарочная коробка.",
    category: "chocolate",
    categoryLabel: "Шоколад",
    images: [
      "https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=800&h=800&fit=crop",
    eventType: "romantic",
    weight: "400 г",
    prepTime: "3 дня",
    price: 1600,
    city: "Москва",
    tags: ["шоколад", "конфеты", "бельгийский", "подарок", "премиум"],
    fillings: ["Пралине", "Трюфель", "Карамель"],
    likes: 412,
    views: 5240,
    featured: true,
    createdAt: "2026-06-22T15:00:00",
    status: "published",
  },
  {
    id: "work-009",
    confectionerId: "c4",
    confectionerName: "Шоколатье Дмитрий",
    title: "Шоколадная скульптура «Лебедь»",
    description: "Уникальная авторская скульптура из тёмного бельгийского шоколада. Высота 30 см. Идеально для свадеб и юбилеев.",
    category: "chocolate",
    categoryLabel: "Шоколад",
    images: [
      "https://images.unsplash.com/photo-1542843137-8791a6904d14?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1542843137-8791a6904d14?w=800&h=800&fit=crop",
    eventType: "wedding",
    weight: "1.5 кг",
    prepTime: "7 дней",
    price: 8500,
    city: "Москва",
    tags: ["шоколад", "скульптура", "лебедь", "авторская работа", "премиум"],
    likes: 523,
    views: 6890,
    featured: true,
    createdAt: "2026-06-08T09:00:00",
    status: "published",
  },

  // ===== Cupcake Studio (c5) =====
  {
    id: "work-010",
    confectionerId: "c5",
    confectionerName: "Капкейк-студия «Сладкоежка»",
    title: "Набор капкейков 12 шт ассорти",
    description: "12 ярких капкейков с разными вкусами: шоколад, ваниль, клубника, фисташка, карамель, черника. Идеально для детского праздника.",
    category: "cupcakes",
    categoryLabel: "Капкейки",
    images: [
      "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&h=800&fit=crop",
    eventType: "kids",
    weight: "600 г",
    prepTime: "1 день",
    price: 1200,
    city: "Екатеринбург",
    tags: ["капкейки", "ассорти", "детский праздник", "яркие"],
    fillings: ["Шоколад", "Ваниль", "Клубника", "Фисташка"],
    likes: 298,
    views: 3420,
    featured: true,
    createdAt: "2026-06-25T13:00:00",
    status: "published",
  },
  {
    id: "work-011",
    confectionerId: "c5",
    confectionerName: "Капкейк-студия «Сладкоежка»",
    title: "Бенто-торт «С днём рождения»",
    description: "Маленький бенто-торт 10-12 см с любой надписью. Идеальный размер для двоих. В комплекте свечка и ложечка.",
    category: "bento",
    categoryLabel: "Бенто-торты",
    images: [
      "https://images.unsplash.com/photo-1612203985729-70726954388c?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1612203985729-70726954388c?w=800&h=800&fit=crop",
    eventType: "birthday",
    weight: "400 г",
    servings: 2,
    prepTime: "1 день",
    price: 690,
    city: "Екатеринбург",
    tags: ["бенто", "мини", "надпись", "день рождения", "хит"],
    fillings: ["Шоколад", "Ваниль"],
    likes: 189,
    views: 2480,
    featured: false,
    createdAt: "2026-06-19T14:00:00",
    status: "published",
  },

  // ===== Lucy Macaron (c6) =====
  {
    id: "work-012",
    confectionerId: "c6",
    confectionerName: "Мастерская макарон «Люси»",
    title: "Макаруны 24 штуки ассорти",
    description: "Набор из 24 французских макарун 12 разных вкусов: фисташка, малина, шоколад, ваниль, лаванда, фиалка, карамель и другие.",
    category: "macarons",
    categoryLabel: "Макаронс",
    images: [
      "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1569864358642-9d1684040f43?w=800&h=800&fit=crop",
    eventType: "romantic",
    weight: "480 г",
    prepTime: "2 дня",
    price: 2100,
    city: "Казань",
    tags: ["макаруны", "французские", "ассорти", "подарок", "премиум"],
    fillings: ["Фисташка", "Малина", "Шоколад", "Карамель"],
    likes: 367,
    views: 4120,
    featured: true,
    createdAt: "2026-06-21T11:30:00",
    status: "published",
  },
  {
    id: "work-013",
    confectionerId: "c6",
    confectionerName: "Мастерская макарон «Люси»",
    title: "Башня макарон для свадьбы",
    description: "Пирамида из 80 макарун на 5 ярусах. Идеальная замена традиционному свадебному торту. 8 вкусов.",
    category: "macarons",
    categoryLabel: "Макаронс",
    images: [
      "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=800&h=800&fit=crop",
    eventType: "wedding",
    weight: "1.6 кг",
    servings: 40,
    prepTime: "4 дня",
    price: 8500,
    city: "Казань",
    tags: ["макаруны", "свадебная башня", "пирамида", "5 ярусов", "премиум"],
    fillings: ["Фисташка", "Малина", "Шоколад", "Ваниль"],
    likes: 445,
    views: 5670,
    featured: true,
    createdAt: "2026-06-14T16:45:00",
    status: "published",
  },
  {
    id: "work-014",
    confectionerId: "c1",
    confectionerName: "Сладкая мастерская Анны",
    title: "Муссовый торт «Северное сияние»",
    description: "Многослойный муссовый торт с зеркальной глазурью переливающихся цветов. Внутри: мусс из манго, бисквит, клубничный конфитюр.",
    category: "mousse_cakes",
    categoryLabel: "Муссовые торты",
    images: [
      "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=800&h=800&fit=crop",
    eventType: "anniversary",
    weight: "1.8 кг",
    servings: 14,
    prepTime: "3 дня",
    price: 4500,
    city: "Москва",
    tags: ["муссовый", "зеркальная глазурь", "северное сияние", "премиум"],
    fillings: ["Манго", "Клубника"],
    likes: 312,
    views: 3890,
    featured: true,
    createdAt: "2026-06-26T10:00:00",
    status: "published",
  },
  {
    id: "work-015",
    confectionerId: "c2",
    confectionerName: "Кондитерский дом «Ваниль»",
    title: "Медовик классический",
    description: "Тонкие медовые коржи с нежным сметанным кремом. По семейному рецепту, тает во рту.",
    category: "honey_cakes",
    categoryLabel: "Медовики",
    images: [
      "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&h=800&fit=crop",
    ],
    mainImage: "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&h=800&fit=crop",
    eventType: "just",
    weight: "1.4 кг",
    servings: 12,
    prepTime: "1 день",
    price: 1800,
    city: "Москва",
    tags: ["медовик", "классика", "сметанный крем"],
    fillings: ["Сметанный крем", "Мёд"],
    likes: 178,
    views: 2230,
    featured: false,
    createdAt: "2026-06-02T09:00:00",
    status: "published",
  },
];
