import type { ServiceShop, ServiceProduct } from "./types";

// ===== МАГАЗИНЫ УСЛУГ =====
export const MOCK_SERVICE_SHOPS: ServiceShop[] = [
  {
    id: "ss1",
    businessName: "Праздник-Салют",
    description:
      "Профессиональные фейерверки и пиротехника для праздников. Холодные салюты для помещений, уличные фейерверки. Лицензия на пиротехнику. Безопасность гарантирована.",
    avatar: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400",
    cover: "https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=1200",
    city: "Москва",
    region: "Москва",
    rating: 4.9,
    reviewsCount: 670,
    shipsNationwide: false,
    deliveryCities: ["Москва", "Химки", "Подольск", "Мытищи"],
    minOrder: 2000,
    categories: ["fireworks_indoor", "fireworks_outdoor", "fireworks_stage"],
    verified: true,
    platformDiscount: 10,
    phone: "+7 495 555-12-34",
  },
  {
    id: "ss2",
    businessName: "Шар-Сюрприз",
    description:
      "Воздушные шары и композиции для любого праздника. Гелиевые шары, арки, цифры, фотозоны. Доставка и монтаж. 500+ цветов и оттенков.",
    avatar: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
    city: "Москва",
    region: "Москва",
    rating: 4.85,
    reviewsCount: 1240,
    shipsNationwide: false,
    deliveryCities: ["Москва", "Химки", "Балашиха", "Подольск", "Мытищи"],
    minOrder: 1500,
    categories: ["balloons_helium", "balloons_composition", "balloons_arch", "balloons_release"],
    verified: true,
    platformDiscount: 8,
    phone: "+7 495 333-44-55",
  },
  {
    id: "ss3",
    businessName: "Аниматоры-Про",
    description:
      "Профессиональные аниматоры, клоуны, сказочные герои для детских праздников. Шоу-программы, квесты, аквагрим. Выезд по Москве и области.",
    avatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    city: "Москва",
    region: "Москва",
    rating: 4.95,
    reviewsCount: 890,
    shipsNationwide: false,
    serviceRadiusKm: 50,
    minOrder: 3000,
    categories: ["animator_clown", "animator_hero", "animator_show", "animator_facepaint", "animator_quest"],
    verified: true,
    platformDiscount: 12,
    phone: "+7 916 777-88-99",
  },
  {
    id: "ss4",
    businessName: "Праздник-Студия",
    description:
      "Полный цикл организации праздников. Ведущие, диджеи, фотографы, видеографы. Свадьбы, корпоративы, дни рождения. Работаем с 2010 года.",
    avatar: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
    city: "Москва",
    region: "Москва",
    rating: 4.9,
    reviewsCount: 420,
    shipsNationwide: false,
    serviceRadiusKm: 60,
    minOrder: 5000,
    categories: ["photographer", "videographer", "music", "host", "other"],
    verified: true,
    platformDiscount: 5,
    phone: "+7 495 222-33-44",
  },
  {
    id: "ss5",
    businessName: "Шарики-СПб",
    description:
      "Воздушные шары и декор для праздников в Санкт-Петербурге. Гелиевые композиции, арки, цифры. Доставка по городу и пригородам.",
    avatar: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
    city: "Санкт-Петербург",
    region: "Санкт-Петербург",
    rating: 4.8,
    reviewsCount: 340,
    shipsNationwide: false,
    deliveryCities: ["Санкт-Петербург", "Кудрово", "Всеволожск"],
    minOrder: 1000,
    categories: ["balloons_helium", "balloons_composition", "balloons_arch"],
    verified: true,
    platformDiscount: 10,
    phone: "+7 812 555-66-77",
  },
];

// ===== УСЛУГИ =====
export const MOCK_SERVICE_PRODUCTS: ServiceProduct[] = [
  // --- ФЕЙЕРВЕРКИ ---
  {
    id: "sp1",
    shopId: "ss1",
    shopName: "Праздник-Салют",
    shopAvatar: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400",
    title: "Холодный салют для торта «Золотой дождь»",
    description:
      "Холодный фейерверк для помещения — крепится на торт. Не дымит, не пахнет, искры холодные. Идеально для выноса торта на празднике. Высота искр 60 см, горит 30 секунд.",
    category: "fireworks_indoor",
    price: 850,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600"],
    durationSeconds: 30,
    shotsCount: 1,
    customizable: false,
    suitableFor: ["birthday", "wedding", "new_year"],
    rating: 4.9,
    reviewsCount: 234,
    isPopular: true,
    crossSellWith: ["p1", "p4", "p2"],
    inStock: 180,
    available: true,
    safetyNote: "Использовать только в помещении с потолком выше 3 м. Не направлять на людей.",
  },
  {
    id: "sp2",
    shopId: "ss1",
    shopName: "Праздник-Салют",
    title: "Салют 25 залпов «Праздничный»",
    description:
      "Уличный салют 25 залпов. Разноцветные искры, трещащие эффекты. Высота до 30 м. Идеально для свадеб, корпоративов, дней рождения на свежем воздухе.",
    category: "fireworks_outdoor",
    price: 3500,
    oldPrice: 4200,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600"],
    durationSeconds: 60,
    shotsCount: 25,
    suitableFor: ["wedding", "new_year", "corporate"],
    rating: 4.85,
    reviewsCount: 89,
    isPopular: true,
    crossSellWith: ["p4"],
    inStock: 45,
    available: true,
    safetyNote: "Запускать только на улице, на расстоянии 30+ м от зданий и людей. Нужна площадка 50×50 м.",
  },
  {
    id: "sp3",
    shopId: "ss1",
    shopName: "Праздник-Салют",
    title: "Сценический фейерверк «Водопад искр»",
    description:
      "Сценический холодный фейерверк — каскад искр высотой до 3 м. Для выездных церемоний, свадеб, конференций. Гори 60 секунд. Безопасен для помещений.",
    category: "fireworks_stage",
    price: 6500,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600"],
    durationSeconds: 60,
    shotsCount: 6,
    suitableFor: ["wedding", "corporate"],
    rating: 5.0,
    reviewsCount: 34,
    isNew: true,
    crossSellWith: ["p4"],
    inStock: 12,
    available: true,
    safetyNote: "Профессиональный монтаж. Требуется технический райдер.",
  },
  {
    id: "sp4",
    shopId: "ss1",
    shopName: "Праздник-Салют",
    title: "Набор холодных салютов (5 шт) для торта",
    description:
      "Набор из 5 холодных салютов для торта. Разная высота: 40, 50, 60 см. Создают эффект «огненного водопада». Не дымят, безопасны.",
    category: "fireworks_indoor",
    price: 2900,
    oldPrice: 3500,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=600"],
    durationSeconds: 40,
    shotsCount: 5,
    suitableFor: ["birthday", "wedding"],
    rating: 4.8,
    reviewsCount: 67,
    crossSellWith: ["p1", "p4"],
    inStock: 78,
    available: true,
    safetyNote: "Закрепить на подложке торта. Не использовать вблизи легковоспламеняющихся материалов.",
  },

  // --- ШАРЫ ---
  {
    id: "sp5",
    shopId: "ss2",
    shopName: "Шар-Сюрприз",
    shopAvatar: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
    title: "Фонтан из 50 гелиевых шаров",
    description:
      "Фонтан из 50 разноцветных гелиевых шаров. Высота 2-3 м. Идеально для дня рождения, корпоратива, свадьбы. Доставка и установка включены.",
    category: "balloons_composition",
    price: 2800,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 50,
    customizable: true,
    suitableFor: ["birthday", "wedding", "corporate"],
    rating: 4.9,
    reviewsCount: 156,
    isPopular: true,
    crossSellWith: ["p1", "p5", "p2"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp6",
    shopId: "ss2",
    shopName: "Шар-Сюрприз",
    title: "Арка из шаров «С Днём Рождения» (3 м)",
    description:
      "Арка из гелиевых шаров с надписью «С Днём Рождения». Размер 3×2 м. Идеальна для фотозоны. Монтаж и демонтаж включены.",
    category: "balloons_arch",
    price: 5500,
    oldPrice: 6500,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 150,
    customizable: true,
    suitableFor: ["birthday", "kids"],
    rating: 4.95,
    reviewsCount: 78,
    isPopular: true,
    crossSellWith: ["p1", "p5"],
    inStock: 50,
    available: true,
  },
  {
    id: "sp7",
    shopId: "ss2",
    shopName: "Шар-Сюрприз",
    title: "Цифра из шаров (любая цифра)",
    description:
      "Большая цифра из гелиевых шаров. Размер 1.5 м. Любой цвет. Идеально для дня рождения, годовщины. Укажите цифру при заказе.",
    category: "balloons_composition",
    price: 1900,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 80,
    customizable: true,
    suitableFor: ["birthday", "kids", "corporate"],
    rating: 4.85,
    reviewsCount: 234,
    isPopular: true,
    crossSellWith: ["p1", "p5", "p6"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp8",
    shopId: "ss2",
    shopName: "Шар-Сюрприз",
    title: "Гелиевые шары (набор 30 шт, разные цвета)",
    description:
      "Набор из 30 гелиевых шаров разных цветов. Латексные, обрабатываются Hi-Float (летают 3-5 дней). Доставка по Москве включена.",
    category: "balloons_helium",
    price: 1500,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 30,
    suitableFor: ["birthday", "kids", "corporate"],
    rating: 4.7,
    reviewsCount: 312,
    crossSellWith: ["p1", "p5", "p2"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp9",
    shopId: "ss2",
    shopName: "Шар-Сюрприз",
    title: "Запуск 100 шаров (экологичных)",
    description:
      "Запуск 100 биоразлагаемых шаров. Финал праздника — эффектный запуск в небо. Идеально для свадеб и больших торжеств.",
    category: "balloons_release",
    price: 3200,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 100,
    suitableFor: ["wedding", "corporate"],
    rating: 4.9,
    reviewsCount: 45,
    isNew: true,
    crossSellWith: ["p4"],
    inStock: 30,
    available: true,
  },

  // --- АНИМАТОРЫ ---
  {
    id: "sp10",
    shopId: "ss3",
    shopName: "Аниматоры-Про",
    shopAvatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    title: "Аниматор-клоун «Кеша» (2 часа)",
    description:
      "Профессиональный аниматор в образе клоуна Кеши. Игры, конкурсы, фокусы, мыльные пузыри. Возраст 3-8 лет. 2 часа программы. Выезд по Москве.",
    category: "animator_clown",
    price: 4500,
    priceUnit: "hour",
    images: ["https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=600"],
    duration: "2 часа",
    programDuration: 120,
    ageRange: "3-8 лет",
    customizable: false,
    suitableFor: ["birthday", "kids"],
    rating: 4.95,
    reviewsCount: 287,
    isPopular: true,
    crossSellWith: ["p1", "p5", "p6"],
    inStock: 1,
    available: true,
    portfolioImages: [
      "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
      "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
    ],
  },
  {
    id: "sp11",
    shopId: "ss3",
    shopName: "Аниматоры-Про",
    title: "Аниматор — Человек-Паук (2 часа)",
    description:
      "Любимый герой Marvel на дне рождения вашего ребёнка! Игры, конкурсы, фото-сессия, паутинка. Возраст 4-10 лет. 2 часа.",
    category: "animator_hero",
    price: 5500,
    priceUnit: "hour",
    images: ["https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=600"],
    duration: "2 часа",
    programDuration: 120,
    ageRange: "4-10 лет",
    suitableFor: ["birthday", "kids"],
    rating: 5.0,
    reviewsCount: 198,
    isPopular: true,
    crossSellWith: ["p1", "p5"],
    inStock: 1,
    available: true,
  },
  {
    id: "sp12",
    shopId: "ss3",
    shopName: "Аниматоры-Про",
    title: "Шоу мыльных пузырей (45 минут)",
    description:
      "Захватывающее шоу гигантских мыльных пузырей. Внутри пузыря — ребёнок! Светящиеся пузыри, трюки. 45 минут. Возраст 2-12 лет.",
    category: "animator_show",
    price: 6500,
    oldPrice: 7500,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=600"],
    duration: "45 минут",
    programDuration: 45,
    ageRange: "2-12 лет",
    suitableFor: ["birthday", "kids"],
    rating: 4.9,
    reviewsCount: 134,
    isNew: true,
    crossSellWith: ["p1", "p5", "p6"],
    inStock: 1,
    available: true,
  },
  {
    id: "sp13",
    shopId: "ss3",
    shopName: "Аниматоры-Про",
    title: "Аквагрим для детей (1 час, до 15 детей)",
    description:
      "Профессиональный художник по аквагриму. Рисунки на лицах детей: бабочки, супергерои, животные. Гипоаллергенные краски. 1 час, до 15 детей.",
    category: "animator_facepaint",
    price: 3000,
    priceUnit: "hour",
    images: ["https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=600"],
    duration: "1 час",
    programDuration: 60,
    ageRange: "3-12 лет",
    suitableFor: ["birthday", "kids"],
    rating: 4.85,
    reviewsCount: 156,
    crossSellWith: ["p1", "p5"],
    inStock: 1,
    available: true,
  },
  {
    id: "sp14",
    shopId: "ss3",
    shopName: "Аниматоры-Про",
    title: "Квест-программа «Поиск сокровищ» (2 часа)",
    description:
      "Интерактивный квест для детей 6-12 лет. Загадки, испытания, поиск сокровищ. 2 аниматора, реквизит, призы. Идеально для дня рождения.",
    category: "animator_quest",
    price: 8500,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=600"],
    duration: "2 часа",
    programDuration: 120,
    ageRange: "6-12 лет",
    customizable: true,
    suitableFor: ["birthday", "kids"],
    rating: 5.0,
    reviewsCount: 67,
    isPopular: true,
    crossSellWith: ["p1", "p5", "p6"],
    inStock: 1,
    available: true,
  },

  // --- ФОТОГРАФЫ, ВЕДУЩИЕ ---
  {
    id: "sp15",
    shopId: "ss4",
    shopName: "Праздник-Студия",
    shopAvatar: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
    title: "Фотограф на праздник (4 часа)",
    description:
      "Профессиональный фотограф на день рождения, свадьбу, корпоратив. 4 часа съёмки, 200+ обработанных фото в онлайн-галерее. Выезд по Москве.",
    category: "photographer",
    price: 8000,
    priceUnit: "hour",
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    duration: "4 часа",
    suitableFor: ["birthday", "wedding", "corporate"],
    rating: 4.9,
    reviewsCount: 89,
    crossSellWith: ["p4", "p1"],
    inStock: 1,
    available: true,
    portfolioImages: [
      "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
    ],
  },
  {
    id: "sp16",
    shopId: "ss4",
    shopName: "Праздник-Студия",
    title: "Ведущий на корпоратив (3 часа)",
    description:
      "Профессиональный ведущий на корпоратив. Конкурсы, викторины, интерактивы. Опыт 10+ лет. 3 часа программы. Реквизит включён.",
    category: "host",
    price: 12000,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    duration: "3 часа",
    customizable: true,
    suitableFor: ["corporate", "new_year"],
    rating: 4.85,
    reviewsCount: 56,
    crossSellWith: ["p4"],
    inStock: 1,
    available: true,
  },
  {
    id: "sp17",
    shopId: "ss4",
    shopName: "Праздник-Студия",
    title: "Диджей на свадьбу (5 часов)",
    description:
      "Профессиональный диджей на свадьбу. 5 часов, своё оборудование (звук + свет). Музыка под ваш вкус. Выезд по Москве и области.",
    category: "music",
    price: 15000,
    oldPrice: 18000,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    duration: "5 часов",
    suitableFor: ["wedding", "corporate"],
    rating: 4.95,
    reviewsCount: 78,
    isPopular: true,
    crossSellWith: ["p4"],
    inStock: 1,
    available: true,
  },
  {
    id: "sp18",
    shopId: "ss4",
    shopName: "Праздник-Студия",
    title: "Видеограф на свадьбу (весь день)",
    description:
      "Профессиональный видеограф на свадьбу. Съёмка с утра до вечера. Клип 5-7 минут + хроника. 2 оператора. Выезд по Москве и области.",
    category: "videographer",
    price: 35000,
    priceUnit: "event",
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    duration: "весь день",
    customizable: true,
    suitableFor: ["wedding"],
    rating: 5.0,
    reviewsCount: 34,
    isNew: true,
    crossSellWith: ["p4"],
    inStock: 1,
    available: true,
  },

  // --- ШАРЫ СПб ---
  {
    id: "sp19",
    shopId: "ss5",
    shopName: "Шарики-СПб",
    shopAvatar: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
    title: "Композиция из шаров «Свадебные лебеди»",
    description:
      "Свадебная композиция из гелиевых шаров в форме лебедей. Белые и золотые шары. Размер 2×1.5 м. Доставка по СПб.",
    category: "balloons_composition",
    price: 4200,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 100,
    customizable: true,
    suitableFor: ["wedding"],
    rating: 4.9,
    reviewsCount: 23,
    crossSellWith: ["p3"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp20",
    shopId: "ss5",
    shopName: "Шарики-СПб",
    title: "Набор гелиевых шаров (20 шт, пастель)",
    description:
      "Набор из 20 гелиевых шаров пастельных тонов. Латексные, Hi-Float. Доставка по Санкт-Петербургу.",
    category: "balloons_helium",
    price: 1200,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    balloonsCount: 20,
    suitableFor: ["birthday", "kids"],
    rating: 4.8,
    reviewsCount: 67,
    crossSellWith: ["p3"],
    inStock: 999,
    available: true,
  },
  // ===== ПЕЧАТЬ НА ПРЯНИКАХ И СЪЕДОБНОЙ БУМАГЕ (НОВОЕ) =====
  {
    id: "sp_print_1",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на пряниках (фото, логотип, надпись)",
    description: "Пищевая печать на имбирных пряниках. Любое изображение, фото, логотип или текст. Пищевые чернила, безопасные для здоровья. Пряники включены в стоимость. Возможна срочная печать за 2 часа.",
    category: "print_gingerbread",
    price: 150,
    priceOffers: [
      { name: "1 пряник (стандарт)", price: 150, unit: "шт.", description: "Стандартный имбирный пряник с печатью" },
      { name: "Опт от 10 шт", price: 120, unit: "шт.", description: "Скидка при заказе от 10 пряников" },
      { name: "Опт от 50 шт", price: 95, unit: "шт.", description: "Для корпоративов и свадеб" },
      { name: "Срочный заказ (2 часа)", price: 280, unit: "шт.", description: "Экспресс-печать за 2 часа" },
    ],
    locations: ["Москва, ул. Складочная 1", "Москва, м. Китай-город", "Подольск", "Мытищи"],
    productionTime: "1-2 дня (срочно — 2 часа)",
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600"],
    customizable: true,
    suitableFor: ["birthday", "kids", "corporate", "new_year"],
    rating: 5.0,
    reviewsCount: 1,
    isPopular: true,
    crossSellWith: ["p0_birthday"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_2",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на сахарной бумаге (для торта)",
    description: "Сахарная печать — любое фото или изображение на съедобной сахарной бумаге пищевыми чернилами. Кладётся прямо на торт. Размер: А4 (210×297мм). Время: 1 час.",
    category: "print_sugar_paper",
    price: 500,
    priceOffers: [
      { name: "А4 (210×297мм)", price: 500, unit: "лист", description: "Стандартный размер" },
      { name: "А5 (половина)", price: 280, unit: "лист", description: "Маленький формат" },
      { name: "А3 (большой)", price: 850, unit: "лист", description: "Для больших тортов" },
      { name: "Опт от 5 листов", price: 420, unit: "лист", description: "Скидка при оптовом заказе" },
    ],
    locations: ["Москва, ул. Складочная 1", "Химки", "Подольск"],
    productionTime: "1 час",
    priceUnit: "sheet",
    images: ["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600"],
    customizable: true,
    suitableFor: ["birthday", "wedding", "kids", "corporate"],
    rating: 5.0,
    reviewsCount: 1,
    isPopular: true,
    crossSellWith: ["p0_wedding", "p0_birthday"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_3",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на рисовой бумаге (для тортов и капкейков)",
    description: "Печать изображений на рисовой бумаге — тоньше сахарной, идеально для капкейков и мини-тортов. Не меняет вкус изделия. Размер: А4. Пищевые чернила.",
    category: "print_rice_paper",
    price: 450,
    priceOffers: [
      { name: "А4", price: 450, unit: "лист" },
      { name: "А5", price: 250, unit: "лист" },
      { name: "Набор 10 кружков d=6см", price: 350, unit: "набор", description: "Для капкейков" },
    ],
    locations: ["Москва, ул. Складочная 1", "Балашиха"],
    productionTime: "1-2 дня",
    priceUnit: "sheet",
    images: ["https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600"],
    customizable: true,
    suitableFor: ["birthday", "kids", "wedding"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["p0_birthday"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_4",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на вафельной бумаге (для декора)",
    description: "Печать на тонкой вафельной бумаге — для создания съедобных картинок, фигурок, топперов. Не имеет вкуса. Размер: А3 и А4.",
    category: "print_wafer_paper",
    price: 350,
    priceUnit: "sheet",
    images: ["https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600"],
    customizable: true,
    suitableFor: ["birthday", "wedding", "kids"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: [],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_5",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на шоколаде (какао-бумага)",
    description: "Прямая печать изображения на шоколадной плитке или трансферной бумаге. Идеально для логотипов, надписей, фирменного дизайна. Размер: 20×30см.",
    category: "print_chocolate",
    price: 700,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1511381939415-e44015466834?w=600"],
    customizable: true,
    suitableFor: ["corporate", "birthday", "wedding"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["p0_custom"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_6",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на глазурной бумаге (icing sheet)",
    description: "Профессиональная глазурная бумага для печати — гибкая, легко ложится на торт любой формы. Лучшее качество цветопередачи. Размер: А4, А3.",
    category: "print_icing_sheet",
    price: 550,
    priceUnit: "sheet",
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600"],
    customizable: true,
    suitableFor: ["birthday", "wedding", "kids", "corporate"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["p0_wedding"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_7",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Печать на печенье (сахарное песочное)",
    description: "Печать фото или рисунка на сахарном/песочном печенье. Отличный подарок и сувенир. Печенье включено. Минимальный заказ: 5 шт.",
    category: "print_custom_cookie",
    price: 120,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600"],
    customizable: true,
    suitableFor: ["birthday", "kids", "corporate", "new_year"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["p0_birthday"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_8",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Съедобные наклейки для тортов и капкейков",
    description: "Готовые съедобные наклейки с принтом — отклеил и приклеил на торт/капкейк. Наборы по теме: дни рождения, свадьбы, Новый год, корпоративные. 12 шт в наборе.",
    category: "print_edible_stickers",
    price: 600,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600"],
    customizable: true,
    suitableFor: ["birthday", "kids", "new_year"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["p0_birthday"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_9",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Дизайн изображения для пищевой печати",
    description: "Создание уникального дизайна для печати на торте/прянике/печенье. Наш дизайнер подготовит макет по вашему ТЗ: фото-коллаж, векторный рисунок, надпись. Файл + печать.",
    category: "print_design",
    price: 800,
    priceUnit: "item",
    images: ["https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600"],
    customizable: true,
    suitableFor: ["birthday", "wedding", "kids", "corporate"],
    rating: 5.0,
    reviewsCount: 0,
    crossSellWith: ["sp_print_1", "sp_print_2", "sp_print_3"],
    inStock: 999,
    available: true,
  },
  {
    id: "sp_print_10",
    shopId: "ss1",
    shopName: "Сладкая уездная",
    shopAvatar: "https://i.pravatar.cc/150?img=32",
    title: "Набор пряников с печатью (10 шт, коробка)",
    description: "Имбирные пряники с пищевой печатью — 10 шт в подарочной коробке. Любые изображения: фото, логотип, надпись. Отличный подарок и сувенир на праздник.",
    category: "print_gingerbread",
    price: 1200,
    priceUnit: "set",
    images: ["https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600"],
    customizable: true,
    suitableFor: ["birthday", "kids", "corporate", "new_year"],
    rating: 5.0,
    reviewsCount: 0,
    isPopular: true,
    crossSellWith: ["p0_birthday", "p0_custom"],
    inStock: 999,
    available: true,
  },
];
export const SERVICE_CATEGORIES = [
  { slug: "fireworks_indoor", name: "Холодные салюты", icon: "✨", group: "Фейерверки" },
  { slug: "fireworks_outdoor", name: "Уличные салюты", icon: "🎆", group: "Фейерверки" },
  { slug: "fireworks_stage", name: "Сценические", icon: "🎇", group: "Фейерверки" },
  { slug: "balloons_helium", name: "Гелиевые шары", icon: "🎈", group: "Шары" },
  { slug: "balloons_composition", name: "Композиции", icon: "🎈", group: "Шары" },
  { slug: "balloons_arch", name: "Арки", icon: "🎈", group: "Шары" },
  { slug: "balloons_release", name: "Запуск шаров", icon: "🎈", group: "Шары" },
  { slug: "animator_clown", name: "Клоуны", icon: "🤡", group: "Аниматоры" },
  { slug: "animator_hero", name: "Сказочные герои", icon: "🦸", group: "Аниматоры" },
  { slug: "animator_show", name: "Шоу-программы", icon: "🎭", group: "Аниматоры" },
  { slug: "animator_facepaint", name: "Аквагрим", icon: "🎨", group: "Аниматоры" },
  { slug: "animator_quest", name: "Квесты", icon: "🗺️", group: "Аниматоры" },
  { slug: "photographer", name: "Фотографы", icon: "📷", group: "Профессионалы" },
  { slug: "videographer", name: "Видеографы", icon: "🎥", group: "Профессионалы" },
  { slug: "music", name: "Диджеи, музыканты", icon: "🎵", group: "Профессионалы" },
  { slug: "host", name: "Ведущие", icon: "🎤", group: "Профессионалы" },
  // — Печать на пряниках и съедобной бумаге (НОВОЕ) —
  { slug: "print_gingerbread", name: "Печать на пряниках", icon: "🍪", group: "Печать на пряниках и бумаге" },
  { slug: "print_sugar_paper", name: "Печать на сахарной бумаге", icon: "📄", group: "Печать на пряниках и бумаге" },
  { slug: "print_rice_paper", name: "Печать на рисовой бумаге", icon: "📃", group: "Печать на пряниках и бумаге" },
  { slug: "print_wafer_paper", name: "Печать на вафельной бумаге", icon: "🖼️", group: "Печать на пряниках и бумаге" },
  { slug: "print_chocolate", name: "Печать на шоколаде", icon: "🍫", group: "Печать на пряниках и бумаге" },
  { slug: "print_icing_sheet", name: "Печать на глазурной бумаге", icon: "✨", group: "Печать на пряниках и бумаге" },
  { slug: "print_custom_cookie", name: "Печать на печенье", icon: "🍪", group: "Печать на пряниках и бумаге" },
  { slug: "print_edible_stickers", name: "Съедобные наклейки", icon: "🏷️", group: "Печать на пряниках и бумаге" },
  { slug: "print_design", name: "Дизайн для печати", icon: "🎨", group: "Печать на пряниках и бумаге" },
] as const;

export const SERVICE_GROUPS = [
  "Фейерверки",
  "Шары",
  "Аниматоры",
  "Профессионалы",
  "Площадки и развлечения",
  "Печать на пряниках и бумаге",
];

export const PRICE_UNIT_LABELS: Record<string, string> = {
  item: "за шт",
  hour: "за час",
  set: "за набор",
  event: "за мероприятие",
  sqm: "за м²",
  day: "за день",
  person: "за человека",
  session: "за сеанс",
  rent: "за аренду",
  kid: "за ребёнка",
  sheet: "за лист",
  batch: "за партию",
};
