import type {
  CorporateEvent,
  BlacklistEntry,
  SemaphoreEntry,
  User,
  UserLegalInfo,
} from "./types";

// ===== ЗАРЕГИСТРИРОВАННЫЕ EMAIL/ТЕЛЕФОНЫ (для семафора) =====
export const MOCK_SEMAPHORES: SemaphoreEntry[] = [
  // Демо-аккаунты
  { id: "s1", type: "email", value: "customer@demo.ru", userId: "u1", verified: true, registeredAt: "2025-03-12", attempts: 1 },
  { id: "s2", type: "phone", value: "+7 916 123-45-67", userId: "u1", verified: true, registeredAt: "2025-03-12", attempts: 1 },
  { id: "s3", type: "email", value: "confectioner@demo.ru", userId: "u2", verified: true, registeredAt: "2024-11-04", attempts: 1 },
  { id: "s4", type: "phone", value: "+7 905 222-33-44", userId: "u2", verified: true, registeredAt: "2024-11-04", attempts: 1 },
  { id: "s5", type: "email", value: "supplier@demo.ru", userId: "u3", verified: true, registeredAt: "2024-08-20", attempts: 1 },
  { id: "s6", type: "phone", value: "+7 903 555-66-77", userId: "u3", verified: true, registeredAt: "2024-08-20", attempts: 1 },
  { id: "s7", type: "email", value: "courier@demo.ru", userId: "u4", verified: true, registeredAt: "2025-01-15", attempts: 1 },
  { id: "s8", type: "phone", value: "+7 926 888-99-00", userId: "u4", verified: true, registeredAt: "2025-01-15", attempts: 1 },
  { id: "s9", type: "email", value: "admin@demo.ru", userId: "u5", verified: true, registeredAt: "2024-01-01", attempts: 1 },
  // Корпоративный клиент
  { id: "s10", type: "email", value: "events@technopolis.ru", userId: "u15", verified: true, registeredAt: "2024-09-15", attempts: 1 },
  { id: "s11", type: "phone", value: "+7 495 100-20-30", userId: "u15", verified: true, registeredAt: "2024-09-15", attempts: 1 },
  // Другие реальные пользователи (для тестов семафора)
  { id: "s12", type: "email", value: "olga@example.ru", userId: "u16", verified: true, registeredAt: "2025-04-10", attempts: 1 },
  { id: "s13", type: "phone", value: "+7 916 555-12-34", userId: "u16", verified: true, registeredAt: "2025-04-10", attempts: 1 },
  { id: "s14", type: "email", value: "test@blocked.ru", userId: "u17", verified: false, registeredAt: "2025-05-20", attempts: 3, lastAttemptAt: "2025-06-25" },
];

// ===== ЮРЛИЦА-ПОКУПАТЕЛИ (для тестов) =====
export const MOCK_LEGAL_USERS: User[] = [
  {
    id: "u15",
    email: "events@technopolis.ru",
    name: "Менеджер мероприятий",
    phone: "+7 495 100-20-30",
    avatar: "https://i.pravatar.cc/150?img=60",
    roles: ["CUSTOMER", "CORPORATE_CLIENT"],
    createdAt: "2024-09-15",
    city: "Москва",
    accountType: "legal",
    legalInfo: {
      type: "OOO",
      companyName: "ООО «Технополис»",
      fullName: "Общество с ограниченной ответственностью «Технополис»",
      inn: "7700000456",
      kpp: "770001001",
      ogrn: "1157700012345",
      legalAddress: "125009, г. Москва, ул. Тверская, д. 16, пом. 12",
      postalAddress: "125009, г. Москва, ул. Тверская, д. 16",
      bankAccount: "40702810000000123456",
      bankBik: "044525225",
      bankName: "ПАО Сбербанк",
      correspondentAccount: "30101810400000000225",
      ceoName: "Иванов Иван Иванович",
      ceoPosition: "Генеральный директор",
      ceoBasis: "Устава",
      accountingEmail: "buh@technopolis.ru",
      accountingPhone: "+7 495 100-20-31",
      taxSystem: "OSNO",
      hasVat: true,
      documentsVerified: true,
      verifiedAt: "2024-09-20",
    },
  },
];

// ===== КОРПОРАТИВНЫЕ ПРАЗДНИКИ =====
export const MOCK_CORPORATE_EVENTS: CorporateEvent[] = [
  {
    id: "ce1",
    customerId: "u15",
    customerName: "ООО «Технополис»",
    customerAvatar: "https://i.pravatar.cc/150?img=60",
    companyName: "ООО «Технополис»",
    companyInn: "7700000456",
    contactName: "Елена Менеджер",
    contactPhone: "+7 495 100-20-30",
    contactEmail: "events@technopolis.ru",
    type: "new_year",
    title: "Корпоратив на Новый год 2027 — 200 сотрудников",
    description:
      "Ищем кондитера для новогоднего корпоратива. Нужно: 1 большой торт на разрезание (3 яруса, 200 порций), 200 капкейков с логотипом компании, набор имбирных печенек с росписью для подарков сотрудникам. Декор — зимняя тема, синий + серебро. Доставка в офис 25 декабря.",
    eventDate: "2026-12-25",
    eventLocation: "Москва, Пресненская наб., 12 (башня «Федерация»)",
    attendeesCount: 200,
    budget: { min: 80000, max: 150000 },
    neededItems: ["Большой торт 200 порций", "200 капкейков с логотипом", "Набор имбирных печеней (200 шт)"],
    status: "open",
    responsesCount: 7,
    createdAt: "2026-06-28",
    deadline: "2026-08-15",
    needsInvoice: true,
    needsVatInvoice: true,
    needsAct: true,
    needsContract: true,
    paymentDeferred: true,
    paymentDays: 14,
  },
  {
    id: "ce2",
    customerId: "u15",
    customerName: "ООО «Технополис»",
    customerAvatar: "https://i.pravatar.cc/150?img=60",
    companyName: "ООО «Технополис»",
    companyInn: "7700000456",
    contactName: "Елена Менеджер",
    contactPhone: "+7 495 100-20-30",
    contactEmail: "events@technopolis.ru",
    type: "mar_8",
    title: "8 марта — подарки сотрудницам (50 коробочек)",
    description:
      "К Международному женскому дню нужны подарочные наборы для 50 сотрудниц: мини-торты (бенто) с цветочным декором + макаронс в коробочке с логотипом. Доставка 7 марта до 12:00. Бюджет — до 2000₽ за набор.",
    eventDate: "2026-03-07",
    eventLocation: "Москва, ул. Тверская, 16",
    attendeesCount: 50,
    budget: { min: 50000, max: 100000 },
    neededItems: ["50 бенто-тортов", "50 наборов макаронс (по 6 шт)", "Упаковка с логотипом"],
    status: "completed",
    responsesCount: 12,
    selectedConfectionerId: "c2",
    createdAt: "2026-01-15",
    deadline: "2026-02-10",
    needsInvoice: true,
    needsVatInvoice: true,
    needsAct: true,
    needsContract: true,
    paymentDeferred: true,
    paymentDays: 7,
  },
  {
    id: "ce3",
    customerId: "u16",
    customerName: "Event-агентство «Праздник»",
    customerAvatar: "https://i.pravatar.cc/150?img=44",
    companyName: "ИП Смирнова А.В. (Event-агентство «Праздник»)",
    companyInn: "780000012345",
    contactName: "Анна Смирнова",
    contactPhone: "+7 921 333-44-55",
    contactEmail: "anna@prazdnik-event.ru",
    type: "company_anniversary",
    title: "Годовщина клиента — 5 лет компании, торт 5 ярусов",
    description:
      "Организуем празднование 5-летия IT-компании. Нужен многоярусный торт (5 ярусов) на 150 человек с логотипом юбиляра. Декор — золотой + чёрный. Также нужны 100 макаронс в корпоративных цветах. Доставка в Ленэкспо 15 июля.",
    eventDate: "2026-07-15",
    eventLocation: "Санкт-Петербург, Ленэкспо",
    attendeesCount: 150,
    budget: { min: 60000, max: 120000 },
    neededItems: ["Торт 5 ярусов на 150 порций", "100 макаронс"],
    status: "open",
    responsesCount: 5,
    createdAt: "2026-06-25",
    deadline: "2026-07-05",
    needsInvoice: true,
    needsVatInvoice: false,
    needsAct: true,
    needsContract: true,
    paymentDeferred: false,
  },
  {
    id: "ce4",
    customerId: "u17",
    customerName: "АО «РосТех»",
    companyName: "АО «РосТех»",
    companyInn: "7700000789",
    contactName: "Дмитрий Сергеевич",
    contactPhone: "+7 495 200-30-40",
    contactEmail: "d.sergeev@rosteh.ru",
    type: "feb_23",
    title: "23 февраля — подарочные наборы для 300 мужчин",
    description:
      "К Дню защитника Отечества нужны подарочные наборы для 300 сотрудников-мужчин. В набор: торт-бенто с военной/мужской тематикой + шоколадные конфеты ручной работы. Упаковка — чёрная с тиснением. Доставка 22 февраля.",
    eventDate: "2027-02-22",
    eventLocation: "Москва, 3 locations",
    attendeesCount: 300,
    budget: { min: 200000, max: 350000 },
    neededItems: ["300 бенто-тортов", "300 коробок шоколадных конфет", "Упаковка с тиснением"],
    status: "open",
    responsesCount: 3,
    createdAt: "2026-06-20",
    deadline: "2026-12-15",
    needsInvoice: true,
    needsVatInvoice: true,
    needsAct: true,
    needsContract: true,
    paymentDeferred: true,
    paymentDays: 30,
  },
  {
    id: "ce5",
    customerId: "u15",
    customerName: "ООО «Технополис»",
    customerAvatar: "https://i.pravatar.cc/150?img=60",
    companyName: "ООО «Технополис»",
    contactName: "Елена Менеджер",
    contactPhone: "+7 495 100-20-30",
    contactEmail: "events@technopolis.ru",
    type: "office_party",
    title: "Офисная пятница — капкейки на корпоратив",
    description:
      "Пятничный офисный перекус. Нужно 60 капкейков разных вкусов на 60 сотрудников. Без декора — простой офисный формат. Бюджет небольшой. Доставка в пятницу 17:00.",
    eventDate: "2026-07-04",
    eventLocation: "Москва, ул. Тверская, 16",
    attendeesCount: 60,
    budget: { min: 8000, max: 15000 },
    neededItems: ["60 капкейков разных вкусов"],
    status: "open",
    responsesCount: 9,
    createdAt: "2026-06-29",
    deadline: "2026-07-03",
    needsInvoice: true,
    needsVatInvoice: false,
    needsAct: false,
    needsContract: false,
    paymentDeferred: false,
  },
];

// ===== ЧЁРНЫЙ СПИСОК =====
export const MOCK_BLACKLIST: BlacklistEntry[] = [
  {
    id: "bl1",
    scope: "email",
    value: "fraud1@scam.ru",
    reason: "fraud",
    reasonDetails:
      "Пользователь пытался оплатить торты украденной кредитной картой. После получения товара инициировал chargeback. Был обнаружен повторный аккаунт с тем же IP.",
    evidence: ["screenshot_chargeback.png", "chat_log_1.png", "ip_log.png"],
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-05-12",
    isPermanent: true,
    status: "active",
    relatedOrderIds: ["o_fraud_1", "o_fraud_2"],
  },
  {
    id: "bl2",
    scope: "phone",
    value: "+7 999 000-11-22",
    reason: "extortion",
    reasonDetails:
      "Пользователь угрожал кондитеру плохими отзывами, требуя бесплатный торт и денежную компенсацию. При отказе — опубликовал 5 фейковых негативных отзывов с разных аккаунтов.",
    evidence: ["chat_threats.png", "reviews_log.png"],
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-05-25",
    isPermanent: true,
    status: "active",
    appeals: [
      {
        id: "ap1",
        text: "Это была ошибка, я извиняюсь перед кондитером",
        createdAt: "2026-06-10",
        status: "rejected",
      },
    ],
  },
  {
    id: "bl3",
    scope: "user",
    value: "u_fraud_1",
    userId: "u_fraud_1",
    reason: "scam",
    reasonDetails:
      "Создавал фейковые аккаунты кондитеров с чужими фотографиями тортов. Получал предоплату от покупателей и пропадал. Жертв — 3 покупателя на сумму 15 400 ₽.",
    evidence: ["fake_profiles.png", "victims_log.png"],
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-06-01",
    isPermanent: true,
    status: "active",
  },
  {
    id: "bl4",
    scope: "email",
    value: "spam@bulk.ru",
    reason: "spam",
    reasonDetails:
      "Массовая рассылка спама в чатах с рекламой сторонних услуг. Получил 12 жалоб от пользователей за неделю.",
    blockedBy: "moderator@demo.ru",
    blockedAt: "2026-06-15",
    isPermanent: false,
    expiresAt: "2026-07-15",
    status: "active",
  },
  {
    id: "bl5",
    scope: "phone",
    value: "+7 916 555-12-34",
    reason: "duplicate_account",
    reasonDetails:
      "Обнаружено 3 аккаунта с одним телефоном. Создавались для получения приветственных бонусов многократно.",
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-06-20",
    isPermanent: false,
    expiresAt: "2026-08-20",
    status: "active",
  },
  {
    id: "bl6",
    scope: "ip",
    value: "192.168.1.100",
    reason: "suspicious_activity",
    reasonDetails:
      "Множественные попытки подбора паролей (brute-force). Зафиксировано 250 неудачных попыток входа за 1 час.",
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-06-22",
    isPermanent: false,
    expiresAt: "2026-07-22",
    status: "active",
  },
  {
    id: "bl7",
    scope: "user",
    value: "u_abuser_1",
    userId: "u_abuser_1",
    reason: "abuse",
    reasonDetails:
      "Систематические оскорбления кондитеров и службы поддержки. 8 жалоб от разных пользователей за месяц.",
    evidence: ["chat_abuse_1.png", "chat_abuse_2.png"],
    blockedBy: "moderator@demo.ru",
    blockedAt: "2026-06-18",
    isPermanent: false,
    expiresAt: "2026-07-18",
    status: "active",
    appeals: [
      {
        id: "ap2",
        text: "Обещаю исправиться, больше не буду оскорблять",
        createdAt: "2026-06-25",
        status: "pending",
      },
    ],
  },
  {
    id: "bl8",
    scope: "user",
    value: "u_old_1",
    userId: "u_old_1",
    reason: "non_payment",
    reasonDetails:
      "Неоплата 3 заказов на сумму 8 900 ₽. Заказы получал, но отказывался платить. Был заблокирован, через 3 месяца подал апелляцию и оплатил долг.",
    blockedBy: "admin@demo.ru",
    blockedAt: "2026-03-15",
    isPermanent: false,
    expiresAt: "2026-06-15",
    status: "lifted",
    appeals: [
      {
        id: "ap3",
        text: "Долг погашен, чеки прилагаю",
        createdAt: "2026-06-10",
        status: "approved",
      },
    ],
  },
];

// ===== ПРЕДСТОЯЩИЕ ПРАЗДНИКИ (для страницы) =====
export const UPCOMING_HOLIDAYS = [
  {
    type: "new_year" as const,
    name: "Новый год",
    date: "2026-12-31",
    daysLeft: 184,
    icon: "🎄",
    description: "Самый ожидаемый праздник. Корпоративы, подарки, торты для офиса и семьи",
    color: "bg-red-100 text-red-800 border-red-200",
  },
  {
    type: "feb_23" as const,
    name: "День защитника Отечества",
    date: "2027-02-23",
    daysLeft: 67,
    icon: "🎖️",
    description: "Подарки сотрудникам и близким мужчинам",
    color: "bg-blue-100 text-blue-800 border-blue-200",
  },
  {
    type: "mar_8" as const,
    name: "Международный женский день",
    date: "2027-03-08",
    daysLeft: 80,
    icon: "🌷",
    description: "Подарочные наборы и торты для сотрудниц",
    color: "bg-pink-100 text-pink-800 border-pink-200",
  },
  {
    type: "knowledge_day" as const,
    name: "День знаний",
    date: "2026-09-01",
    daysLeft: 63,
    icon: "📚",
    description: "Торты в школу, cupcakes для первоклассников",
    color: "bg-amber-100 text-amber-800 border-amber-200",
  },
  {
    type: "company_anniversary" as const,
    name: "Корпоративный юбилей",
    date: null,
    daysLeft: null,
    icon: "🎂",
    description: "Годовщина компании — закажите торт с логотипом",
    color: "bg-purple-100 text-purple-800 border-purple-200",
  },
  {
    type: "office_party" as const,
    name: "Офисная вечеринка",
    date: null,
    daysLeft: null,
    icon: "🎉",
    description: "Пятничный корпоратив, тимбилдинг, день рождения коллеги",
    color: "bg-emerald-100 text-emerald-800 border-emerald-200",
  },
];

// ===== МЕТКИ ТИПОВ КОРПОРАТИВНЫХ СОБЫТИЙ =====
export const CORPORATE_EVENT_TYPES: Record<
  string,
  { label: string; icon: string; color: string; description: string }
> = {
  new_year: { label: "Новый год", icon: "🎄", color: "bg-red-100 text-red-800", description: "Корпоратив на Новый год" },
  christmas: { label: "Рождество", icon: "✨", color: "bg-amber-100 text-amber-800", description: "Рождественский корпоратив" },
  feb_23: { label: "23 февраля", icon: "🎖️", color: "bg-blue-100 text-blue-800", description: "День защитника Отечества" },
  mar_8: { label: "8 марта", icon: "🌷", color: "bg-pink-100 text-pink-800", description: "Международный женский день" },
  easter: { label: "Пасха", icon: "🥚", color: "bg-purple-100 text-purple-800", description: "Пасхальные куличи и торты" },
  may_1: { label: "1 мая", icon: "🌸", color: "bg-emerald-100 text-emerald-800", description: "Праздник Весны и Труда" },
  may_9: { label: "9 мая", icon: "🎖️", color: "bg-orange-100 text-orange-800", description: "День Победы" },
  russia_day: { label: "12 июня", icon: "🇷🇺", color: "bg-white border-2 border-red-500 text-red-700", description: "День России" },
  nov_4: { label: "4 ноября", icon: "🤝", color: "bg-indigo-100 text-indigo-800", description: "День народного единства" },
  knowledge_day: { label: "1 сентября", icon: "📚", color: "bg-amber-100 text-amber-800", description: "День знаний" },
  company_anniversary: { label: "Юбилей компании", icon: "🎂", color: "bg-purple-100 text-purple-800", description: "Годовщина компании" },
  office_party: { label: "Офисная вечеринка", icon: "🎉", color: "bg-emerald-100 text-emerald-800", description: "Корпоративное мероприятие" },
  team_building: { label: "Тимбилдинг", icon: "🤝", color: "bg-cyan-100 text-cyan-800", description: "Командное мероприятие" },
  conference: { label: "Конференция", icon: "🎤", color: "bg-slate-100 text-slate-800", description: "Конференция или форум" },
  client_event: { label: "Клиентское", icon: "🤝", color: "bg-blue-100 text-blue-800", description: "Мероприятие для клиентов" },
  corporate_gifts: { label: "Подарки", icon: "🎁", color: "bg-rose-100 text-rose-800", description: "Корпоративные подарки" },
  other: { label: "Другое", icon: "📅", color: "bg-slate-100 text-slate-800", description: "Другое мероприятие" },
};

// ===== ПРИЧИНЫ БЛОКИРОВКИ =====
export const BLACKLIST_REASONS: Record<
  string,
  { label: string; icon: string; color: string; severity: "high" | "medium" | "low" }
> = {
  fraud: { label: "Мошенничество", icon: "🎭", color: "bg-red-100 text-red-800", severity: "high" },
  scam: { label: "Обман", icon: "🚫", color: "bg-red-100 text-red-800", severity: "high" },
  extortion: { label: "Вымогательство", icon: "💰", color: "bg-red-100 text-red-800", severity: "high" },
  spam: { label: "Спам", icon: "📢", color: "bg-amber-100 text-amber-800", severity: "low" },
  fake_reviews: { label: "Накрутка отзывов", icon: "⭐", color: "bg-amber-100 text-amber-800", severity: "medium" },
  non_payment: { label: "Неоплата", icon: "💳", color: "bg-amber-100 text-amber-800", severity: "medium" },
  abuse: { label: "Оскорбления", icon: "😡", color: "bg-orange-100 text-orange-800", severity: "medium" },
  threats: { label: "Угрозы", icon: "⚠️", color: "bg-red-100 text-red-800", severity: "high" },
  duplicate_account: { label: "Дубль-аккаунт", icon: "👥", color: "bg-blue-100 text-blue-800", severity: "low" },
  violated_terms: { label: "Нарушение условий", icon: "📋", color: "bg-amber-100 text-amber-800", severity: "medium" },
  suspicious_activity: { label: "Подозрительная активность", icon: "🔍", color: "bg-purple-100 text-purple-800", severity: "medium" },
  other: { label: "Другое", icon: "📌", color: "bg-slate-100 text-slate-800", severity: "low" },
};

// ===== ТИПЫ ОРГАНИЗАЦИЙ =====
export const LEGAL_TYPES: Record<
  string,
  { label: string; shortLabel: string; needsKpp: boolean; innLength: number; ogrnLength: number }
> = {
  IP: { label: "Индивидуальный предприниматель (ИП)", shortLabel: "ИП", needsKpp: false, innLength: 12, ogrnLength: 15 },
  OOO: { label: "Общество с ограниченной ответственностью (ООО)", shortLabel: "ООО", needsKpp: true, innLength: 10, ogrnLength: 13 },
  PAO: { label: "Публичное акционерное общество (ПАО)", shortLabel: "ПАО", needsKpp: true, innLength: 10, ogrnLength: 13 },
  NAO: { label: "Непубличное акционерное общество (НАО)", shortLabel: "НАО", needsKpp: true, innLength: 10, ogrnLength: 13 },
  FKUP: { label: "Федеральное казённое унитарное предприятие (ФКУП)", shortLabel: "ФКУП", needsKpp: true, innLength: 10, ogrnLength: 13 },
  GUP: { label: "Государственное унитарное предприятие (ГУП)", shortLabel: "ГУП", needsKpp: true, innLength: 10, ogrnLength: 13 },
  OTHER: { label: "Другая организация", shortLabel: "Прочее", needsKpp: false, innLength: 10, ogrnLength: 13 },
};
