import type { Venue, VenueService, PriceList, VenueVendor } from "./types";

// ===== Размещённые на площадках продавцы (кондитеры, кейтеринг, декораторы) =====
export const MOCK_VENUE_VENDORS: VenueVendor[] = [
  {
    id: "vv1", venueId: "v1", vendorId: "c1", vendorName: "Сладкая уездная",
    vendorAvatar: "https://i.pravatar.cc/150?img=32", vendorType: "confectioner",
    placement: "Кафе на 1 этаже, стойка у входа", floor: "1", pavilion: "—", unit: "стойка 5",
    contractStart: "2026-01-15", contractEnd: "2026-12-31", commissionPercent: 12,
    status: "active", createdAt: "2026-01-10T10:00:00",
  },
  {
    id: "vv2", venueId: "v1", vendorId: "c2", vendorName: "Торты от Марии",
    vendorAvatar: "https://i.pravatar.cc/150?img=45", vendorType: "confectioner",
    placement: "Кафе на 1 этаже, витрина у окна", floor: "1", pavilion: "—", unit: "остров 3",
    contractStart: "2026-03-01", contractEnd: "2026-09-30", commissionPercent: 10,
    status: "active", createdAt: "2026-02-25T12:00:00",
  },
  {
    id: "vv3", venueId: "v2", vendorId: "c3", vendorName: "Кейтеринг «Вкусно и точка»",
    vendorAvatar: "https://i.pravatar.cc/150?img=12", vendorType: "catering",
    placement: "Зона фуд-корта, павильон B-7", floor: "1", pavilion: "B-7", unit: "—",
    contractStart: "2026-02-01", contractEnd: "2027-01-31", commissionPercent: 15,
    status: "active", createdAt: "2026-01-20T11:00:00",
  },
  {
    id: "vv4", venueId: "v3", vendorId: "c1", vendorName: "Сладкая уездная",
    vendorAvatar: "https://i.pravatar.cc/150?img=32", vendorType: "confectioner",
    placement: "Банкетная зона, кухня под ключ", floor: "2", pavilion: "—", unit: "кухня",
    contractStart: "2026-04-01", contractEnd: "2026-10-31", commissionPercent: 8,
    status: "active", createdAt: "2026-03-15T15:00:00",
  },
  {
    id: "vv5", venueId: "v3", vendorId: "c4", vendorName: "Декор-студия «Праздник»",
    vendorAvatar: "https://i.pravatar.cc/150?img=22", vendorType: "decorator",
    placement: "Складское помещение, цокольный этаж", floor: "цоколь", pavilion: "—", unit: "комната 2",
    contractStart: "2026-04-01", contractEnd: "2026-12-31", commissionPercent: 10,
    status: "active", createdAt: "2026-03-20T16:00:00",
  },
  {
    id: "vv6", venueId: "v4", vendorId: "c2", vendorName: "Торты от Марии",
    vendorAvatar: "https://i.pravatar.cc/150?img=45", vendorType: "confectioner",
    placement: "Кафе на 2 этаже, у боулинга", floor: "2", pavilion: "—", unit: "стойка 1",
    contractStart: "2026-05-01", contractEnd: "2026-11-30", commissionPercent: 12,
    status: "pending", createdAt: "2026-04-25T09:00:00",
  },
  {
    id: "vv7", venueId: "v4", vendorId: "c5", vendorName: "Фото-Стиль",
    vendorAvatar: "https://i.pravatar.cc/150?img=33", vendorType: "photographer",
    placement: "Лобби, стойка информации", floor: "1", pavilion: "—", unit: "стойка 0",
    contractStart: "2026-04-15", commissionPercent: 5,
    status: "active", createdAt: "2026-04-10T13:00:00",
  },
];

// ===== Моковые площадки для проведения праздников =====
export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    ownerId: "demo-venue-owner",
    ownerName: "Батутный парк «Гравитация»",
    businessName: "Батутный парк «Гравитация»",
    slug: "gravitatsiya-trampoline",
    description:
      "Большой батутный парк 1500 м² с зоной для детей и взрослых. Аренда для праздников, день рождения с аниматором, спецплощадки для прыжков. Кафе на территории.",
    logo: "https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=400",
    coverImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=1200",
    galleryImages: [
      "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800",
      "https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=800",
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=800",
    ],
    country: "Россия",
    city: "Москва",
    region: "Москва",
    district: "Свиблово",
    street: "ул. Складочная",
    building: "1, стр. 18",
    floor: "1",
    pavilion: "—",
    unit: "главный зал",
    fullAddress: "Россия, Москва, ул. Складочная, 1, стр. 18, 1 этаж",
    postalCode: "127411",
    address: "ул. Складочная, 1, стр. 18",
    lat: 55.7972,
    lng: 37.5886,
    venueType: "venue_trampoline",
    venueTypeLabel: "Батутный парк",
    area: 1500,
    capacity: 80,
    ageGroups: ["5-8", "9-12", "13+"],
    amenities: ["Парковка", "Кафе", "Wi-Fi", "Раздевалки", "Душ", "Кондиционер"],
    services: ["Аниматор", "Еда", "Торт", "Фото", "Видео"],
    workingHours: { days: "Пн-Вс", from: "10:00", to: "22:00" },
    phone: "+7 495 555-44-66",
    email: "info@gravitatsiya.ru",
    website: "https://gravitatsiya.ru",
    rating: 4.8,
    reviewsCount: 1245,
    bookingsCount: 856,
    verified: true,
    minOrder: 5000,
    platformDiscount: 5,
    createdAt: "2026-05-15T10:00:00",
    status: "published",
  },
  {
    id: "v2",
    ownerId: "demo-venue-owner-2",
    ownerName: "Картинг-центр «Молния»",
    businessName: "Картинг-центр «Молния»",
    slug: "molniya-karting",
    description:
      "Профессиональный картинг с трассой 800 м. Проведение детских праздников, корпоративных заездов, турниры. Инструкторы, экипировка, кафе.",
    logo: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400",
    coverImage: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200",
    galleryImages: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=800",
      "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800",
    ],
    country: "Россия",
    city: "Москва",
    region: "Москва",
    district: "Перово",
    street: "Шоссе Энтузиастов",
    building: "56",
    floor: "1",
    pavilion: "B-7",
    unit: "—",
    fullAddress: "Россия, Москва, Шоссе Энтузиастов, 56, павильон B-7",
    postalCode: "111024",
    address: "Шоссе Энтузиастов, 56",
    lat: 55.7531,
    lng: 37.7325,
    venueType: "venue_karting",
    venueTypeLabel: "Картинг",
    area: 3000,
    capacity: 40,
    ageGroups: ["9-12", "13+"],
    amenities: ["Парковка", "Кафе", "Wi-Fi", "Экипировка", "Раздевалки"],
    services: ["Инструктор", "Еда", "Медаль победителю", "Фото"],
    workingHours: { days: "Пн-Вс", from: "12:00", to: "23:00" },
    phone: "+7 495 555-77-88",
    email: "book@molniya-karting.ru",
    rating: 4.7,
    reviewsCount: 856,
    bookingsCount: 524,
    verified: true,
    minOrder: 8000,
    platformDiscount: 0,
    createdAt: "2026-05-20T11:00:00",
    status: "published",
  },
  {
    id: "v3",
    ownerId: "demo-venue-owner-3",
    ownerName: "Лофт-пространство «Сказка»",
    businessName: "Лофт-пространство «Сказка»",
    slug: "skazka-loft",
    description:
      "Дизайнерский лофт 200 м² для детских праздников. Две зоны: игровая с аниматорами и банкетная. Кухня под ключ, своё меню, прокат оборудования.",
    logo: "https://images.unsplash.com/photo-1519167758481-83f550bb46b3?w=400",
    coverImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200",
    galleryImages: [
      "https://images.unsplash.com/photo-1511578314322-379afb476865?w=800",
      "https://images.unsplash.com/photo-1519167758481-83f550bb46b3?w=800",
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=800",
    ],
    country: "Россия",
    city: "Москва",
    region: "Москва",
    district: "Пресненский",
    street: "Большая Никитская",
    building: "24/1",
    floor: "2",
    pavilion: "—",
    unit: "офис 5",
    fullAddress: "Россия, Москва, Большая Никитская, 24/1, 2 этаж, офис 5",
    postalCode: "121069",
    address: "Большая Никитская, 24/1",
    lat: 55.7568,
    lng: 37.6056,
    venueType: "venue_loft",
    venueTypeLabel: "Лофт для праздников",
    area: 200,
    capacity: 30,
    ageGroups: ["1-4", "5-8", "9-12", "13+"],
    amenities: ["Парковка", "Кухня", "Wi-Fi", "Звук", "Проектор", "Кондиционер", "Холодильник"],
    services: ["Аниматор", "Еда", "Торт", "Фото", "Видео", "Декор"],
    workingHours: { days: "Пн-Вс", from: "10:00", to: "23:00" },
    phone: "+7 495 555-99-00",
    email: "hello@skazka-loft.ru",
    website: "https://skazka-loft.ru",
    rating: 4.92,
    reviewsCount: 423,
    bookingsCount: 287,
    verified: true,
    minOrder: 12000,
    platformDiscount: 10,
    createdAt: "2026-04-10T14:00:00",
    status: "published",
  },
  {
    id: "v4",
    ownerId: "demo-venue-owner-4",
    ownerName: "Развлекательный центр «Космос»",
    businessName: "Развлекательный центр «Космос»",
    slug: "kosmos-rc",
    description:
      "Многофункциональный центр: лазертаг, VR-арена, квест-комнаты, боулинг. Полный пакет для праздника: аниматоры, еда, торт.",
    logo: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400",
    coverImage: "https://images.unsplash.com/photo-1504670933227-846dc1e0e1bf?w=1200",
    galleryImages: [
      "https://images.unsplash.com/photo-1504670933227-846dc1e0e1bf?w=800",
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800",
      "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=800",
    ],
    country: "Россия",
    city: "Санкт-Петербург",
    region: "Санкт-Петербург",
    district: "Центральный",
    street: "Лиговский пр.",
    building: "50, лит. А",
    floor: "2",
    pavilion: "—",
    unit: "—",
    fullAddress: "Россия, Санкт-Петербург, Лиговский пр., 50, лит. А, 2 этаж",
    postalCode: "191040",
    address: "Лиговский пр., 50, лит. А",
    lat: 59.9262,
    lng: 30.3596,
    venueType: "venue_laser_tag",
    venueTypeLabel: "Лазертаг / VR / Квесты",
    area: 1200,
    capacity: 100,
    ageGroups: ["5-8", "9-12", "13+"],
    amenities: ["Парковка", "Кафе", "Wi-Fi", "Гардероб", "Кондиционер"],
    services: ["Аниматор", "Еда", "Торт", "Фото", "Видео", "Призы"],
    workingHours: { days: "Пн-Вс", from: "11:00", to: "23:00" },
    phone: "+7 812 555-22-33",
    email: "info@kosmos-rc.ru",
    rating: 4.85,
    reviewsCount: 967,
    bookingsCount: 642,
    verified: true,
    minOrder: 15000,
    platformDiscount: 8,
    createdAt: "2026-03-25T09:00:00",
    status: "published",
  },
];

// ===== Моковые карточки услуг площадок =====
export const MOCK_VENUE_SERVICES: VenueService[] = [
  {
    id: "vs1",
    venueId: "v1",
    venueName: "Батутный парк «Гравитация»",
    venueLogo: "https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=400",
    title: "Аренда батутного парка на день рождения (2 часа, до 15 детей)",
    description: "Приватная зона батутов 500 м² на 2 часа. Аниматор в подарок, комната для чаепития, холодильник для торта. Инструкторы, страховка включена.",
    category: "venue_trampoline",
    categoryLabel: "Батутный парк",
    includes: ["2 часа аренды", "Аниматор", "Комната для чаепития", "Холодильник для торта", "Инструктор", "Страховка"],
    images: ["https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600"],
    mainImage: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600",
    price: 12000,
    priceUnit: "event",
    durationMinutes: 120,
    groupSize: { min: 5, max: 15 },
    ageRestriction: { min: 5, max: 15 },
    suitableFor: ["birthday", "kids"],
    rating: 4.8,
    reviewsCount: 234,
    bookingsCount: 189,
    isPopular: true,
    isFeatured: true,
    availability: "available",
    crossSellWith: ["p5"],
    safetyNote: "Дети до 8 лет — в сопровождении взрослых. Спортивная одежда и носки обязательны.",
    createdAt: "2026-05-15T10:00:00",
    status: "published",
  },
  {
    id: "vs2",
    venueId: "v1",
    venueName: "Батутный парк «Гравитация»",
    venueLogo: "https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=400",
    title: "Игровая комната для малышей (1-4 года)",
    description: "Отдельная безопасная зона с мягкими модулями, сухим бассейном и развивающими играми. 1 час с аниматором-воспитателем.",
    category: "venue_indoor_play",
    categoryLabel: "Игровая комната",
    includes: ["1 час", "Аниматор-воспитатель", "Мягкие модули", "Сухой бассейн"],
    images: ["https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600"],
    mainImage: "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600",
    price: 2500,
    priceUnit: "hour",
    durationMinutes: 60,
    groupSize: { min: 1, max: 8 },
    ageRestriction: { min: 1, max: 4 },
    suitableFor: ["kids"],
    rating: 4.9,
    reviewsCount: 156,
    bookingsCount: 98,
    isPopular: false,
    isFeatured: false,
    availability: "available",
    crossSellWith: [],
    createdAt: "2026-05-16T11:00:00",
    status: "published",
  },
  {
    id: "vs3",
    venueId: "v2",
    venueName: "Картинг-центр «Молния»",
    venueLogo: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=400",
    title: "Детский праздник на картинге (10 детей, 2 заезда)",
    description: "2 заезда по 10 минут на детских картах (от 7 лет). Инструктор, экипировка, медаль победителю. Комната для чаепития 1 час.",
    category: "venue_karting",
    categoryLabel: "Картинг",
    includes: ["2 заезда по 10 мин", "Инструктор", "Экипировка", "Медаль победителю", "Комната 1 час"],
    images: ["https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600"],
    mainImage: "https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=600",
    price: 18000,
    priceUnit: "event",
    durationMinutes: 120,
    groupSize: { min: 5, max: 10 },
    ageRestriction: { min: 7, max: 14 },
    suitableFor: ["birthday", "kids", "corporate"],
    rating: 4.7,
    reviewsCount: 187,
    bookingsCount: 134,
    isPopular: true,
    isFeatured: true,
    availability: "limited",
    crossSellWith: ["p1"],
    safetyNote: "Возраст от 7 лет, рост от 120 см. Закрытая обувь обязательна.",
    createdAt: "2026-05-20T12:00:00",
    status: "published",
  },
  {
    id: "vs4",
    venueId: "v3",
    venueName: "Лофт-пространство «Сказка»",
    venueLogo: "https://images.unsplash.com/photo-1519167758481-83f550bb46b3?w=400",
    title: "Аренда лофта для детского праздника (4 часа)",
    description: "Дизайнерский лофт 200 м² с двумя зонами: игровая (с аниматором, мягкие модули, сухой бассейн) и банкетная (стол на 20 чел, кухня).",
    category: "venue_loft",
    categoryLabel: "Лофт для праздников",
    includes: ["4 часа аренды", "Игровая зона", "Банкетная зона", "Кухня", "Звук", "Проектор", "Wi-Fi"],
    images: ["https://images.unsplash.com/photo-1511578314322-379afb476865?w=600"],
    mainImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=600",
    price: 16000,
    priceUnit: "rent",
    durationMinutes: 240,
    groupSize: { min: 5, max: 30 },
    ageRestriction: { min: 0, max: 99 },
    suitableFor: ["birthday", "kids", "wedding", "corporate"],
    rating: 4.92,
    reviewsCount: 178,
    bookingsCount: 145,
    isPopular: true,
    isFeatured: true,
    availability: "available",
    crossSellWith: ["p1", "p5"],
    createdAt: "2026-04-10T14:00:00",
    status: "published",
  },
  {
    id: "vs5",
    venueId: "v3",
    venueName: "Лофт-пространство «Сказка»",
    venueLogo: "https://images.unsplash.com/photo-1519167758481-83f550bb46b3?w=400",
    title: "Кулинарный мастер-класс для детей (10 чел, 2 часа)",
    description: "Дети готовят сами пиццу, капкейки и украшают торт под руководством шеф-повара. Все продукты, фартуки, упаковка. Сертификат «Юный кондитер».",
    category: "venue_master_class",
    categoryLabel: "Мастер-класс",
    includes: ["2 часа", "Шеф-повар", "Все продукты", "Фартуки", "Упаковка", "Сертификат"],
    images: ["https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600"],
    mainImage: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600",
    price: 14000,
    priceUnit: "event",
    durationMinutes: 120,
    groupSize: { min: 5, max: 10 },
    ageRestriction: { min: 6, max: 14 },
    suitableFor: ["birthday", "kids"],
    rating: 4.94,
    reviewsCount: 134,
    bookingsCount: 92,
    isPopular: true,
    isFeatured: true,
    availability: "available",
    crossSellWith: ["p5"],
    createdAt: "2026-04-12T10:00:00",
    status: "published",
  },
  {
    id: "vs6",
    venueId: "v4",
    venueName: "Развлекательный центр «Космос»",
    venueLogo: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400",
    title: "Лазертаг-арена для праздника (1 час, до 16 чел)",
    description: "Профессиональная лазертаг-арена 400 м² с укрытиями, туманами, светомузыкой. 1 час игры, инструктор, вооружение.",
    category: "venue_laser_tag",
    categoryLabel: "Лазертаг",
    includes: ["1 час игры", "Инструктор", "Вооружение", "Комната 30 мин"],
    images: ["https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600"],
    mainImage: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=600",
    price: 11000,
    priceUnit: "event",
    durationMinutes: 60,
    groupSize: { min: 6, max: 16 },
    ageRestriction: { min: 7, max: 99 },
    suitableFor: ["birthday", "kids", "corporate"],
    rating: 4.85,
    reviewsCount: 312,
    bookingsCount: 245,
    isPopular: true,
    isFeatured: true,
    availability: "available",
    crossSellWith: ["p1", "p5"],
    safetyNote: "Возраст от 7 лет. Запрещено бегать без головного убора.",
    createdAt: "2026-03-25T09:00:00",
    status: "published",
  },
];

// ===== Моковые прайс-листы =====
export const MOCK_PRICE_LISTS: PriceList[] = [
  {
    id: "pl1",
    ownerId: "demo-venue-owner",
    ownerName: "Батутный парк «Гравитация»",
    ownerType: "VENUE_OWNER",
    title: "Прайс-лист батутного парка 2026",
    description: "Актуальные цены на аренду батутного парка для праздников",
    category: "venue_trampoline",
    validFrom: "2026-01-01",
    validTo: "2026-12-31",
    currency: "RUB",
    createdAt: "2026-01-15T10:00:00",
    status: "active",
    items: [
      {
        id: "pli1",
        priceListId: "pl1",
        serviceName: "Аренда батутного парка (2 часа, до 15 детей)",
        description: "Приватная зона 500 м², аниматор в подарок",
        category: "venue_trampoline",
        price: 12000,
        priceUnit: "event",
        duration: 120,
        minQuantity: 5,
        maxQuantity: 15,
        notes: "Возраст от 5 лет",
        isAvailable: true,
        venueServiceId: "vs1",
      },
      {
        id: "pli2",
        priceListId: "pl1",
        serviceName: "Игровая комната для малышей (1 час)",
        description: "Зона с мягкими модулями для детей 1-4 лет",
        category: "venue_indoor_play",
        price: 2500,
        priceUnit: "hour",
        duration: 60,
        minQuantity: 1,
        maxQuantity: 8,
        isAvailable: true,
        venueServiceId: "vs2",
      },
      {
        id: "pli3",
        priceListId: "pl1",
        serviceName: "Доп. час аренды батутов",
        description: "Продление праздника",
        category: "venue_trampoline",
        price: 4500,
        priceUnit: "hour",
        duration: 60,
        isAvailable: true,
      },
      {
        id: "pli4",
        priceListId: "pl1",
        serviceName: "Аниматор-инструктор (1 час)",
        description: "Профессиональный аниматор с программой",
        category: "venue_trampoline",
        price: 2500,
        priceUnit: "hour",
        duration: 60,
        isAvailable: true,
      },
      {
        id: "pli5",
        priceListId: "pl1",
        serviceName: "Пицца для детей (10 шт)",
        description: "Маргарита, пепперони, сырная",
        category: "venue_trampoline",
        price: 2800,
        priceUnit: "set",
        isAvailable: true,
      },
      {
        id: "pli6",
        priceListId: "pl1",
        serviceName: "Фотоотчёт праздника",
        description: "Профессиональный фотограф на 2 часа + 50 фото",
        category: "venue_trampoline",
        price: 5000,
        priceUnit: "event",
        duration: 120,
        isAvailable: true,
      },
    ],
  },
  {
    id: "pl2",
    ownerId: "demo-venue-owner-2",
    ownerName: "Картинг-центр «Молния»",
    ownerType: "VENUE_OWNER",
    title: "Прайс-лист картинга 2026",
    description: "Цены на заезды и пакеты для праздников",
    category: "venue_karting",
    validFrom: "2026-01-01",
    currency: "RUB",
    createdAt: "2026-01-20T11:00:00",
    status: "active",
    items: [
      {
        id: "pli7",
        priceListId: "pl2",
        serviceName: "Детский праздник (10 детей, 2 заезда)",
        description: "2 заезда по 10 минут, инструктор, экипировка, медаль",
        category: "venue_karting",
        price: 18000,
        priceUnit: "event",
        duration: 120,
        minQuantity: 5,
        maxQuantity: 10,
        notes: "Возраст от 7 лет, рост от 120 см",
        isAvailable: true,
        venueServiceId: "vs3",
      },
      {
        id: "pli8",
        priceListId: "pl2",
        serviceName: "Аренда автодрома (электромобили) — 1 час",
        description: "10 электромобилей для детей 4-10 лет",
        category: "venue_bumper_cars",
        price: 8500,
        priceUnit: "hour",
        duration: 60,
        maxQuantity: 12,
        isAvailable: true,
      },
      {
        id: "pli9",
        priceListId: "pl2",
        serviceName: "Корпоративный заезд (20 чел, 3 заезда)",
        description: "Турнир с призами, кофе-брейк",
        category: "venue_karting",
        price: 45000,
        priceUnit: "event",
        duration: 180,
        minQuantity: 15,
        maxQuantity: 25,
        isAvailable: true,
      },
      {
        id: "pli10",
        priceListId: "pl2",
        serviceName: "Доп. заезд (10 минут)",
        description: "Продление заезда",
        category: "venue_karting",
        price: 1500,
        priceUnit: "item",
        duration: 10,
        isAvailable: true,
      },
    ],
  },
  {
    id: "pl3",
    ownerId: "demo-venue-owner-3",
    ownerName: "Лофт-пространство «Сказка»",
    ownerType: "VENUE_OWNER",
    title: "Прайс-лист лофта 2026",
    description: "Аренда лофта, мастер-классы, доп. услуги",
    category: "venue_loft",
    validFrom: "2026-02-01",
    currency: "RUB",
    createdAt: "2026-02-05T14:00:00",
    status: "active",
    items: [
      {
        id: "pli11",
        priceListId: "pl3",
        serviceName: "Аренда лофта для детского праздника (4 часа)",
        description: "200 м², 2 зоны, кухня, звук, проектор",
        category: "venue_loft",
        price: 16000,
        priceUnit: "rent",
        duration: 240,
        maxQuantity: 30,
        isAvailable: true,
        venueServiceId: "vs4",
      },
      {
        id: "pli12",
        priceListId: "pl3",
        serviceName: "Банкетный зал на 30 персон (5 часов)",
        description: "С обслуживанием, официантами, чайной станцией",
        category: "venue_banquet",
        price: 35000,
        priceUnit: "rent",
        duration: 300,
        maxQuantity: 30,
        isAvailable: true,
      },
      {
        id: "pli13",
        priceListId: "pl3",
        serviceName: "Кулинарный мастер-класс (10 чел, 2 часа)",
        description: "Пицца, капкейки, торт + сертификат",
        category: "venue_master_class",
        price: 14000,
        priceUnit: "event",
        duration: 120,
        minQuantity: 5,
        maxQuantity: 10,
        isAvailable: true,
        venueServiceId: "vs5",
      },
      {
        id: "pli14",
        priceListId: "pl3",
        serviceName: "Аниматор (1 час)",
        description: "Профессиональный аниматор с программой",
        category: "venue_loft",
        price: 3000,
        priceUnit: "hour",
        duration: 60,
        isAvailable: true,
      },
      {
        id: "pli15",
        priceListId: "pl3",
        serviceName: "Декор площадки под тематику",
        description: "Оформление шарами, текстилем, цветами",
        category: "venue_loft",
        price: 8000,
        priceUnit: "event",
        isAvailable: true,
      },
      {
        id: "pli16",
        priceListId: "pl3",
        serviceName: "Доп. час аренды",
        description: "Продление праздника",
        category: "venue_loft",
        price: 4000,
        priceUnit: "hour",
        duration: 60,
        isAvailable: true,
      },
    ],
  },
];
