import type { DecorShop, DecorProduct, ProductBundle } from "./types";

// ===== МАГАЗИНЫ ДЕКОРА И УПАКОВКИ =====
export const MOCK_DECOR_SHOPS: DecorShop[] = [
  {
    id: "ds1",
    businessName: "Праздник-Сервис",
    description:
      "Всё для оформления тортов и праздников: свечи, топперы, подложки, ленты, бенгальские огни. Доставка по всей России.",
    avatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    cover: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=1200",
    city: "Москва",
    rating: 4.9,
    reviewsCount: 1840,
    shipsNationwide: true,
    deliveryCities: ["Москва", "Санкт-Петербург", "Тула", "Вся Россия"],
    minOrder: 500,
    categories: ["candles", "toppers", "boards", "sparklers", "ribbon"],
    verified: true,
    platformDiscount: 10,
  },
  {
    id: "ds2",
    businessName: "Упаковка-Маркет",
    description:
      "Премиальная упаковка для кондитеров: коробки, подложки, ленты, тишью. Экологичные материалы. Опт и розница.",
    avatar: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
    city: "Москва",
    rating: 4.85,
    reviewsCount: 920,
    shipsNationwide: true,
    minOrder: 800,
    categories: ["boxes", "packaging", "boards", "ribbon"],
    verified: true,
    platformDiscount: 5,
  },
  {
    id: "ds3",
    businessName: "Сахарный Декор",
    description:
      "Сахарные фигурки, цветы и декор для тортов ручной работы. Авторские топперы с гравировкой.",
    avatar: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
    city: "Санкт-Петербург",
    rating: 4.95,
    reviewsCount: 340,
    shipsNationwide: true,
    minOrder: 300,
    categories: ["figures", "flowers", "toppers", "tools"],
    verified: true,
    platformDiscount: 15,
  },
  {
    id: "ds4",
    businessName: "GiftBox Pro",
    description:
      "Подарочная упаковка премиум-класса. Подарочные карты, коробки с тиснением, ленты. Брендирование.",
    avatar: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
    city: "Москва",
    rating: 4.8,
    reviewsCount: 412,
    shipsNationwide: true,
    minOrder: 1000,
    categories: ["gift_cards", "boxes", "packaging", "ribbon"],
    verified: true,
    platformDiscount: 8,
  },
];

// ===== ТОВАРЫ ДЕКОРА И УПАКОВКИ =====
export const MOCK_DECOR_PRODUCTS: DecorProduct[] = [
  // --- Свечи ---
  {
    id: "dp1",
    shopId: "ds1",
    shopName: "Праздник-Сервис",
    shopAvatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    title: "Свечи-цифры для торта (набор 0-9)",
    description:
      "Золотые свечи-цифры для торта. В наборе 10 шт (0-9). Высота 5 см. Не капают, горят ровно. Идеально для дней рождения.",
    category: "candles",
    price: 290,
    oldPrice: 390,
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    material: "Парафин, краситель пищевой",
    color: "Золотой",
    size: "5 см",
    packQuantity: 10,
    reusable: false,
    customizable: false,
    suitableFor: ["birthday", "new_year"],
    rating: 4.8,
    reviewsCount: 145,
    isPopular: true,
    crossSellWith: ["p1", "p5", "p6"],
    inStock: 450,
  },
  {
    id: "dp2",
    shopId: "ds1",
    shopName: "Праздник-Сервис",
    shopAvatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    title: "Бенгальские огни для торта (5 шт)",
    description:
      "Холодные бенгальские огни для украшения торта. Не дымят, не пахнут. Создают праздничное настроение. 5 шт в наборе.",
    category: "sparklers",
    price: 180,
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    packQuantity: 5,
    suitableFor: ["birthday", "new_year", "wedding"],
    rating: 4.9,
    reviewsCount: 87,
    isPopular: true,
    crossSellWith: ["p1", "p4"],
    inStock: 220,
  },
  {
    id: "dp3",
    shopId: "ds1",
    shopName: "Праздник-Сервис",
    title: "Свечи «С Днём Рождения» (набор)",
    description: "Набор из 12 разноцветных свечей с надписью «С Днём Рождения». Высота 7 см.",
    category: "candles",
    price: 150,
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    packQuantity: 12,
    suitableFor: ["birthday"],
    rating: 4.7,
    reviewsCount: 56,
    crossSellWith: ["p1", "p5"],
    inStock: 380,
  },

  // --- Топперы ---
  {
    id: "dp4",
    shopId: "ds1",
    shopName: "Праздник-Сервис",
    shopAvatar: "https://images.unsplash.com/photo-1513885535751-8b9238bd345c?w=400",
    title: "Топпер «Happy Birthday» золотой (акрил)",
    description:
      "Акриловый топпер «Happy Birthday» золотого цвета. Многоразовый. Не боится влаги. Размер 15×10 см.",
    category: "toppers",
    price: 350,
    oldPrice: 450,
    images: ["https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600"],
    material: "Акрил",
    color: "Золотой",
    size: "15×10 см",
    reusable: true,
    customizable: false,
    suitableFor: ["birthday"],
    rating: 4.9,
    reviewsCount: 98,
    isPopular: true,
    crossSellWith: ["p1", "p2", "p5"],
    inStock: 180,
  },
  {
    id: "dp5",
    shopId: "ds3",
    shopName: "Сахарный Декор",
    shopAvatar: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
    title: "Топпер «С Днём Рождения» с персонализацией",
    description:
      "Деревянный топпер с гравировкой имени. Укажите имя при заказе. Размер 18×12 см. Экологичное дерево.",
    category: "toppers",
    price: 450,
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    material: "Дерево (фанера)",
    reusable: true,
    customizable: true,
    suitableFor: ["birthday", "kids"],
    rating: 5.0,
    reviewsCount: 42,
    isNew: true,
    crossSellWith: ["p1", "p6"],
    inStock: 65,
  },
  {
    id: "dp6",
    shopId: "ds3",
    shopName: "Сахарный Декор",
    title: "Топпер свадебный «Forever» (зеркальный акрил)",
    description: "Свадебный топпер «Forever» из зеркального акрила. Премиум-качество. 20×8 см.",
    category: "toppers",
    price: 690,
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    material: "Зеркальный акрил",
    color: "Серебро",
    size: "20×8 см",
    reusable: true,
    suitableFor: ["wedding"],
    rating: 4.95,
    reviewsCount: 28,
    crossSellWith: ["p4"],
    inStock: 34,
  },

  // --- Подложки ---
  {
    id: "dp7",
    shopId: "ds2",
    shopName: "Упаковка-Маркет",
    shopAvatar: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
    title: "Подложка усиленная для торта 28 см (золото)",
    description:
      "Усиленная подложка для торта диаметром 28 см. Золотое покрытие. Плотный картон 3 мм. Не прогибается.",
    category: "boards",
    price: 85,
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600"],
    material: "Картон ламинированный",
    color: "Золото",
    size: "28 см",
    packQuantity: 1,
    suitableFor: ["birthday", "wedding", "corporate"],
    rating: 4.85,
    reviewsCount: 312,
    isPopular: true,
    crossSellWith: ["p1", "p2", "p8"],
    inStock: 1200,
  },
  {
    id: "dp8",
    shopId: "ds2",
    shopName: "Упаковка-Маркет",
    title: "Подложка для торта 30 см (серебро) — 5 шт",
    description: "Набор из 5 серебряных подложек 30 см. Усиленный картон. Для больших тортов.",
    category: "boards",
    price: 380,
    oldPrice: 450,
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600"],
    color: "Серебро",
    size: "30 см",
    packQuantity: 5,
    suitableFor: ["wedding", "corporate"],
    rating: 4.9,
    reviewsCount: 167,
    crossSellWith: ["p4", "p2"],
    inStock: 340,
  },

  // --- Коробки ---
  {
    id: "dp9",
    shopId: "ds2",
    shopName: "Упаковка-Маркет",
    shopAvatar: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
    title: "Коробка для торта 30×30×15 см с окном",
    description:
      "Премиальная коробка для торта с прозрачным окном. Размер 30×30×15 см. Крафт + прозрачная плёнка. Идеально для подарка.",
    category: "boxes",
    price: 220,
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600"],
    material: "Крафт-картон, PET",
    color: "Крафт",
    size: "30×30×15 см",
    packQuantity: 1,
    suitableFor: ["birthday", "wedding", "corporate"],
    rating: 4.9,
    reviewsCount: 245,
    isPopular: true,
    crossSellWith: ["p1", "p2", "p4"],
    inStock: 580,
  },
  {
    id: "dp10",
    shopId: "ds2",
    shopName: "Упаковка-Маркет",
    title: "Коробка для капкейков (на 12 шт)",
    description: "Коробка для транспортировки 12 капкейков. С прозрачной крышкой. Не мнёт декор.",
    category: "boxes",
    price: 150,
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600"],
    size: "38×28×10 см",
    packQuantity: 1,
    suitableFor: ["birthday", "corporate"],
    rating: 4.8,
    reviewsCount: 89,
    crossSellWith: ["p5"],
    inStock: 420,
  },

  // --- Ленты ---
  {
    id: "dp11",
    shopId: "ds2",
    shopName: "Упаковка-Маркет",
    title: "Атласная лента для упаковки 25 мм × 10 м (золото)",
    description: "Атласная лента золотого цвета. Ширина 25 мм, длина 10 м. Для бантов и декора коробок.",
    category: "ribbon",
    price: 95,
    images: ["https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=600"],
    material: "Атлас",
    color: "Золото",
    size: "25 мм × 10 м",
    suitableFor: ["birthday", "wedding", "new_year"],
    rating: 4.7,
    reviewsCount: 134,
    crossSellWith: ["p1", "p4", "p9"],
    inStock: 890,
  },

  // --- Фигурки ---
  {
    id: "dp12",
    shopId: "ds3",
    shopName: "Сахарный Декор",
    shopAvatar: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
    title: "Сахарные фигурки «Животные» (6 шт)",
    description:
      "Набор из 6 сахарных фигурок животных для детского торта. Съедобные, ручная роспись. Без консервантов.",
    category: "figures",
    price: 590,
    oldPrice: 750,
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600"],
    material: "Сахарная паста",
    packQuantity: 6,
    suitableFor: ["kids", "birthday"],
    rating: 4.95,
    reviewsCount: 67,
    isPopular: true,
    crossSellWith: ["p1", "p5"],
    inStock: 78,
  },
  {
    id: "dp13",
    shopId: "ds3",
    shopName: "Сахарный Декор",
    title: "Сахарные цветы (набор 5 шт, розы)",
    description: "Набор из 5 сахарных роз. Реалистичные, ручная работа. Цвета: белый, розовый, красный.",
    category: "flowers",
    price: 890,
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600"],
    material: "Сахарная паста",
    packQuantity: 5,
    suitableFor: ["wedding", "birthday"],
    rating: 5.0,
    reviewsCount: 34,
    isNew: true,
    crossSellWith: ["p4", "p1"],
    inStock: 23,
  },

  // --- Подарочные карты ---
  {
    id: "dp14",
    shopId: "ds4",
    shopName: "GiftBox Pro",
    shopAvatar: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
    title: "Подарочная карта «Уездный кондитер» 5000 ₽",
    description:
      "Электронная подарочная карта номиналом 5000 ₽. Код приходит на email. Можно использовать для любого заказа на платформе.",
    category: "gift_cards",
    price: 5000,
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    customizable: true,
    suitableFor: ["birthday", "new_year", "corporate"],
    rating: 4.9,
    reviewsCount: 156,
    isPopular: true,
    crossSellWith: [],
    inStock: 9999,
  },
  {
    id: "dp15",
    shopId: "ds4",
    shopName: "GiftBox Pro",
    title: "Подарочная карта «Уездный кондитер» 10000 ₽",
    description: "Электронная подарочная карта номиналом 10000 ₽. С персональным поздравлением.",
    category: "gift_cards",
    price: 10000,
    images: ["https://images.unsplash.com/photo-1549887534-1541e9326642?w=600"],
    customizable: true,
    suitableFor: ["birthday", "new_year", "corporate", "wedding"],
    rating: 5.0,
    reviewsCount: 78,
    crossSellWith: [],
    inStock: 9999,
  },

  // --- Инструменты ---
  {
    id: "dp16",
    shopId: "ds3",
    shopName: "Сахарный Декор",
    title: "Набор кондитерских насадок (12 шт)",
    description: "Профессиональный набор из 12 насадок для крема. Нержавеющая сталь. Для декора тортов и капкейков.",
    category: "tools",
    price: 690,
    oldPrice: 890,
    images: ["https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=600"],
    material: "Нержавеющая сталь",
    packQuantity: 12,
    reusable: true,
    rating: 4.85,
    reviewsCount: 92,
    crossSellWith: [],
    inStock: 145,
  },
];

// ===== ГОТОВЫЕ НАБОРЫ (BUNDLES) =====
export const MOCK_BUNDLES: ProductBundle[] = [
  {
    id: "b1",
    name: "Набор «День рождения»",
    description: "Торт «Уездный классический» + свечи-цифры + топпер «Happy Birthday» + подарочная коробка с окном",
    items: [
      {
        productId: "p1",
        productType: "cake",
        title: "Торт «Уездный классический»",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        price: 2400,
        quantity: 1,
      },
      {
        productId: "dp1",
        productType: "decor",
        title: "Свечи-цифры для торта (0-9)",
        image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
        price: 290,
        quantity: 1,
      },
      {
        productId: "dp4",
        productType: "decor",
        title: "Топпер «Happy Birthday» золотой",
        image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
        price: 350,
        quantity: 1,
      },
      {
        productId: "dp9",
        productType: "packaging",
        title: "Коробка для торта с окном",
        image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
        price: 220,
        quantity: 1,
      },
    ],
    bundlePrice: 3100,
    originalPrice: 3260,
    discount: 5,
    mainProductId: "p1",
    suitableFor: "birthday",
    soldCount: 142,
    rating: 4.9,
  },
  {
    id: "b2",
    name: "Набор «Праздничный капкейки»",
    description: "12 капкейков + коробка для капкейков + бенгальские огни + топпер персональный",
    items: [
      {
        productId: "p5",
        productType: "cake",
        title: "Набор капкейков «Праздничный»",
        image: "https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=400",
        price: 1800,
        quantity: 1,
      },
      {
        productId: "dp10",
        productType: "packaging",
        title: "Коробка для капкейков (на 12 шт)",
        image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
        price: 150,
        quantity: 1,
      },
      {
        productId: "dp2",
        productType: "decor",
        title: "Бенгальские огни для торта (5 шт)",
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
        price: 180,
        quantity: 1,
      },
      {
        productId: "dp5",
        productType: "decor",
        title: "Топпер с персонализацией",
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
        price: 450,
        quantity: 1,
      },
    ],
    bundlePrice: 2450,
    originalPrice: 2580,
    discount: 5,
    mainProductId: "p5",
    suitableFor: "birthday",
    soldCount: 89,
    rating: 4.95,
  },
  {
    id: "b3",
    name: "Набор «Свадебный премиум»",
    description: "Авторский торт «Лебедь» + сахарные розы + свадебный топпер + премиальная подложка 30 см",
    items: [
      {
        productId: "p4",
        productType: "cake",
        title: "Авторский торт «Лебедь»",
        image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=400",
        price: 12500,
        quantity: 1,
      },
      {
        productId: "dp13",
        productType: "decor",
        title: "Сахарные цветы (5 роз)",
        image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
        price: 890,
        quantity: 1,
      },
      {
        productId: "dp6",
        productType: "decor",
        title: "Топпер свадебный «Forever»",
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
        price: 690,
        quantity: 1,
      },
      {
        productId: "dp8",
        productType: "packaging",
        title: "Подложка 30 см (серебро) — 5 шт",
        image: "https://images.unsplash.com/photo-1607344645866-009c320c5ab8?w=400",
        price: 380,
        quantity: 1,
      },
    ],
    bundlePrice: 13900,
    originalPrice: 14460,
    discount: 4,
    mainProductId: "p4",
    suitableFor: "wedding",
    soldCount: 23,
    rating: 5.0,
  },
  {
    id: "b4",
    name: "Набор «Детский праздник»",
    description: "Торт «Уездный классический» + сахарные фигурки животных + свечи + топпер с именем",
    items: [
      {
        productId: "p1",
        productType: "cake",
        title: "Торт «Уездный классический»",
        image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400",
        price: 2400,
        quantity: 1,
      },
      {
        productId: "dp12",
        productType: "decor",
        title: "Сахарные фигурки «Животные» (6 шт)",
        image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=400",
        price: 590,
        quantity: 1,
      },
      {
        productId: "dp3",
        productType: "decor",
        title: "Свечи «С Днём Рождения» (12 шт)",
        image: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400",
        price: 150,
        quantity: 1,
      },
      {
        productId: "dp5",
        productType: "decor",
        title: "Топпер с персонализацией",
        image: "https://images.unsplash.com/photo-1549887534-1541e9326642?w=400",
        price: 450,
        quantity: 1,
      },
    ],
    bundlePrice: 3400,
    originalPrice: 3590,
    discount: 5,
    mainProductId: "p1",
    suitableFor: "kids",
    soldCount: 67,
    rating: 4.9,
  },
];

// Категории декора для отображения
export const DECOR_CATEGORIES = [
  { slug: "candles", name: "Свечи", icon: "🕯️" },
  { slug: "toppers", name: "Топперы", icon: "👑" },
  { slug: "boards", name: "Подложки", icon: "🍽️" },
  { slug: "boxes", name: "Коробки", icon: "📦" },
  { slug: "ribbon", name: "Ленты", icon: "🎀" },
  { slug: "sparklers", name: "Бенгальские огни", icon: "✨" },
  { slug: "figures", name: "Фигурки", icon: "🎭" },
  { slug: "flowers", name: "Цветы", icon: "🌹" },
  { slug: "packaging", name: "Упаковка", icon: "🎁" },
  { slug: "tools", name: "Инструменты", icon: "🔧" },
  { slug: "gift_cards", name: "Подарочные карты", icon: "💳" },
] as const;
