import type {
  UserHoliday,
  GiftCertificate,
  Referral,
  EcoBadge,
  VideoReview,
  CourierTracking,
} from "./types";

// ===== ЭКО-БЕЙДЖИ =====
export const ECO_BADGES: EcoBadge[] = [
  {
    type: "biodegradable_packaging",
    label: "Биоразлагаемая упаковка",
    icon: "🌱",
    description: "Использует упаковку из переработанных материалов, разлагается за 6 месяцев",
    verified: true,
  },
  {
    type: "local_ingredients",
    label: "Локальные ингредиенты",
    icon: "🚜",
    description: "Закупает продукты у местных фермеров в радиусе 100 км",
    verified: true,
  },
  {
    type: "organic",
    label: "Органические продукты",
    icon: "🌿",
    description: "Использует сертифицированные органические ингредиенты",
    verified: true,
  },
  {
    type: "zero_waste",
    label: "Zero Waste",
    icon: "♻️",
    description: "Минимизирует отходы: переработка, composting, многоразовая тара",
    verified: false,
  },
  {
    type: "no_preservatives",
    label: "Без консервантов",
    icon: "🚫",
    description: "Не использует искусственные консерванты и улучшители",
    verified: true,
  },
  {
    type: "no_margarine",
    label: "Без маргарина",
    icon: "🧈",
    description: "Использует только натуральное сливочное масло 82.5%+",
    verified: true,
  },
  {
    type: "carbon_offset",
    label: "Компенсация CO₂",
    icon: "🌍",
    description: "Компенсирует углеродный след через посадку деревьев",
    verified: false,
  },
  {
    type: "recyclable",
    label: "Перерабатываемые материалы",
    icon: "♻️",
    description: "Вся упаковка подлежит переработке",
    verified: true,
  },
];

// Эко-бейджи по кондитерам (id → список типов бейджей)
export const CONFECTIONER_ECO_BADGES: Record<string, string[]> = {
  c1: ["no_preservatives", "no_margarine", "local_ingredients", "biodegradable_packaging"],
  c2: ["no_preservatives", "no_margarine", "recyclable"],
  c3: ["no_preservatives", "no_margarine", "local_ingredients", "organic", "biodegradable_packaging", "zero_waste"],
  c4: ["no_preservatives", "no_margarine", "recyclable", "carbon_offset"],
};

// ===== КАЛЕНДАРЬ ПРАЗДНИКОВ (для user u1 — Анна) =====
export const MOCK_USER_HOLIDAYS: UserHoliday[] = [
  {
    id: "uh1",
    userId: "u1",
    title: "День рождения Маши",
    type: "birthday",
    date: "2026-07-15",
    recurring: true,
    personName: "Маша",
    relationship: "Дочь",
    reminderDays: 14,
    reminderSent: false,
    pastOrderIds: ["o2"],
    notes: "Любит шоколадные торты с малиной",
  },
  {
    id: "uh2",
    userId: "u1",
    title: "Годовщина свадьбы",
    type: "wedding_anniversary",
    date: "2026-08-20",
    recurring: true,
    personName: "Дмитрий",
    relationship: "Муж",
    reminderDays: 30,
    reminderSent: false,
    notes: "5 лет совместной жизни",
  },
  {
    id: "uh3",
    userId: "u1",
    title: "День рождения мамы",
    type: "birthday",
    date: "2026-09-03",
    recurring: true,
    personName: "Людмила",
    relationship: "Мама",
    reminderDays: 7,
    reminderSent: false,
  },
  {
    id: "uh4",
    userId: "u1",
    title: "Корпоратив в офисе",
    type: "other",
    date: "2026-12-22",
    recurring: false,
    reminderDays: 30,
    reminderSent: false,
    notes: "Нужен торт на 30 человек + капкейки",
  },
  {
    id: "uh5",
    userId: "u1",
    title: "День рождения Анны",
    type: "birthday",
    date: "2026-10-12",
    recurring: true,
    personName: "Анна",
    relationship: "Я",
    reminderDays: 14,
    reminderSent: false,
  },
];

// ===== ПОДАРОЧНЫЕ СЕРТИФИКАТЫ =====
export const MOCK_GIFT_CERTIFICATES: GiftCertificate[] = [
  {
    id: "gc1",
    code: "UK-GIFT-2026-001",
    amount: 5000,
    fromName: "Анна Соколова",
    fromEmail: "customer@demo.ru",
    toName: "Людмила Соколова",
    toEmail: "lyudmila@example.ru",
    toPhone: "+7 916 555-12-34",
    message: "С Днём Рождения, мама! Пусть каждый день будет сладким ❤️",
    design: "birthday",
    purchasedAt: "2026-06-20",
    expiresAt: "2027-06-20",
    status: "active",
    remainingAmount: 5000,
    deliveryMethod: "email",
    sendDate: "2026-09-03",
    sentAt: "2026-09-03T09:00:00",
  },
  {
    id: "gc2",
    code: "UK-GIFT-2026-002",
    amount: 3000,
    fromName: "Анна Соколова",
    fromEmail: "customer@demo.ru",
    toName: "Ольга Иванова",
    toEmail: "olga@example.ru",
    message: "Спасибо за помощь с проектом!",
    design: "classic",
    purchasedAt: "2026-05-15",
    expiresAt: "2027-05-15",
    status: "used",
    usedAt: "2026-06-01",
    usedAmount: 3000,
    remainingAmount: 0,
    deliveryMethod: "email",
    sentAt: "2026-05-15T10:00:00",
  },
];

export const GIFT_CERTIFICATE_DESIGNS = [
  { id: "classic", name: "Классический", color: "from-amber-400 to-primary", emoji: "🎁" },
  { id: "birthday", name: "День рождения", color: "from-pink-400 to-rose-500", emoji: "🎂" },
  { id: "wedding", name: "Свадьба", color: "from-slate-300 to-blue-200", emoji: "💍" },
  { id: "new_year", name: "Новый год", color: "from-red-500 to-green-600", emoji: "🎄" },
  { id: "floral", name: "Цветочный", color: "from-emerald-400 to-teal-500", emoji: "🌸" },
] as const;

export const GIFT_CERTIFICATE_AMOUNTS = [1000, 2000, 3000, 5000, 10000, 15000, 25000, 50000];

// ===== РЕФЕРАЛЬНАЯ ПРОГРАММА (для user u1) =====
export const MOCK_REFERRAL: Referral = {
  id: "ref1",
  userId: "u1",
  referralCode: "ANNA-UK-2026",
  referralLink: "https://conditera.ru/r/ANNA-UK-2026",
  totalInvited: 12,
  activeReferrals: 7,
  totalEarned: 8400,
  availableBalance: 3200,
  rewardAmount: 500,
  rewardPercent: 5,
  history: [
    {
      id: "rh1",
      referredName: "Ольга Иванова",
      referredEmail: "olga@example.ru",
      invitedAt: "2026-03-10",
      firstOrderAt: "2026-03-15",
      orderAmount: 1800,
      earnedAmount: 90,
      status: "ordered",
    },
    {
      id: "rh2",
      referredName: "Дмитрий Петров",
      referredEmail: "dmitry@example.ru",
      invitedAt: "2026-03-20",
      firstOrderAt: "2026-04-01",
      orderAmount: 5400,
      earnedAmount: 270,
      status: "ordered",
    },
    {
      id: "rh3",
      referredName: "Екатерина Смирнова",
      referredEmail: "ekaterina@example.ru",
      invitedAt: "2026-04-05",
      firstOrderAt: "2026-04-10",
      orderAmount: 3200,
      earnedAmount: 160,
      status: "ordered",
    },
    {
      id: "rh4",
      referredName: "Сергей Волков",
      referredEmail: "sergey@example.ru",
      invitedAt: "2026-04-15",
      firstOrderAt: "2026-05-01",
      orderAmount: 2400,
      earnedAmount: 120,
      status: "ordered",
    },
    {
      id: "rh5",
      referredName: "Мария Кузнецова",
      referredEmail: "maria.k@example.ru",
      invitedAt: "2026-05-10",
      status: "registered",
    },
    {
      id: "rh6",
      referredName: "Алексей Морозов",
      referredEmail: "alexey@example.ru",
      invitedAt: "2026-05-20",
      status: "invited",
    },
    {
      id: "rh7",
      referredName: "Ирина Лебедева",
      referredEmail: "irina@example.ru",
      invitedAt: "2026-06-01",
      firstOrderAt: "2026-06-05",
      orderAmount: 12500,
      earnedAmount: 625,
      status: "ordered",
    },
  ],
};

// ===== ВИДЕО-ОТЗЫВЫ =====
export const MOCK_VIDEO_REVIEWS: VideoReview[] = [
  {
    id: "vr1",
    productId: "p1",
    userId: "u1",
    userName: "Анна Соколова",
    userAvatar: "https://i.pravatar.cc/150?img=47",
    videoUrl: "https://example.com/video/review1.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600",
    rating: 5,
    text: "Торт превзошёл все ожидания! Нежный, не приторный. Смотрите видео — покажу в разрезе.",
    duration: 32,
    createdAt: "2026-06-20",
    views: 234,
    likes: 45,
  },
  {
    id: "vr2",
    productId: "p1",
    userId: "u9",
    userName: "Екатерина Смирнова",
    userAvatar: "https://i.pravatar.cc/150?img=49",
    videoUrl: "https://example.com/video/review2.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?w=600",
    rating: 5,
    text: "Заказывала на день рождения мужа — все были в восторге!",
    duration: 18,
    createdAt: "2026-06-15",
    views: 156,
    likes: 28,
  },
  {
    id: "vr3",
    productId: "p4",
    userId: "u10",
    userName: "Дмитрий Петров",
    userAvatar: "https://i.pravatar.cc/150?img=51",
    videoUrl: "https://example.com/video/review3.mp4",
    thumbnailUrl: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
    rating: 5,
    text: "Свадебный торт от «Сахарного Лебедя» — произведение искусства!",
    duration: 45,
    createdAt: "2026-06-10",
    views: 412,
    likes: 87,
  },
];

// ===== ТРЕКИНГ КУРЬЕРА (для заказа o1) =====
export const MOCK_COURIER_TRACKING: CourierTracking = {
  orderId: "o1",
  orderNumber: "UK-2025-0001",
  courierId: "cr1",
  courierName: "Иван Курьеров",
  courierAvatar: "https://i.pravatar.cc/150?img=15",
  courierPhone: "+7 926 888-99-00",
  currentLat: 55.7630,
  currentLng: 37.6250,
  routePoints: [
    { lat: 55.7558, lng: 37.6173, timestamp: "2026-06-30T11:00:00", label: "Забрал заказ" },
    { lat: 55.7580, lng: 37.6200, timestamp: "2026-06-30T11:10:00" },
    { lat: 55.7600, lng: 37.6220, timestamp: "2026-06-30T11:20:00" },
    { lat: 55.7630, lng: 37.6250, timestamp: "2026-06-30T11:30:00", label: "В пути" },
  ],
  pickupPoint: { lat: 55.7558, lng: 37.6173, label: "Кондитерская Купец, ул. Русаковская 28", arrived: true },
  deliveryPoint: { lat: 55.7680, lng: 37.6300, label: "ул. Тверская, д. 12, кв. 45", arrived: false },
  estimatedArrival: "2026-06-30T12:00:00",
  minutesLeft: 25,
  status: "en_route",
  transport: "car",
  distanceKm: 5.2,
  distanceLeftKm: 2.1,
};
