import type { OrderNegotiation } from "./types";

export const MOCK_NEGOTIATIONS: OrderNegotiation[] = [
  {
    id: "neg1",
    inquiryId: "ci1",
    customerId: "u9",
    customerName: "Ольга Иванова",
    customerAvatar: "https://i.pravatar.cc/150?img=49",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    originalRequest: {
      eventType: "kids",
      base: "sponge",
      filling: "Крем пломбир",
      coating: "Крем-чиз",
      decorations: ["Свежие ягоды"],
      servings: 10,
      city: "Москва",
      deliveryDate: "2026-07-10",
      deliveryType: "delivery",
      comment: "Хочу торт с машинкой для сына",
      estimatedPrice: 3500,
    },
    quotedItems: [
      {
        name: "Бисквитный торт «Машинка» (10 порций)",
        description: "2 яруса, бисквит + крем пломбир, декор — сахарная машинка ручной работы",
        quantity: 1,
        unitPrice: 3200,
        totalPrice: 3200,
        category: "cake",
      },
      {
        name: "Доп: сахарная машинка (ручная работа)",
        description: "Объёмная сахарная машинка красного цвета с колёсами",
        quantity: 1,
        unitPrice: 600,
        totalPrice: 600,
        category: "decoration",
      },
      {
        name: "Надпись «С Днём Рождения, Максим!»",
        description: "Шоколадная надпись на торте",
        quantity: 1,
        unitPrice: 200,
        totalPrice: 200,
        category: "service",
      },
      {
        name: "Доставка по Москве",
        description: "В пределах МКАД, 10 июля, 14:00-16:00",
        quantity: 1,
        unitPrice: 350,
        totalPrice: 350,
        category: "delivery",
      },
    ],
    quotedTotal: 4350,
    quotedComment:
      "Здравствуйте! Машинку делаю из сахарной пасты вручную, поэтому +600₽. Также добавил шоколадную надпись с именем. Доставка 350₽. Срок готовки — 2 дня, торт будет готов 10 июля к обеду. Если есть вопросы — пишите в чат!",
    quotedDeliveryCost: 350,
    quotedPrepTime: "2 дня",
    quotedAt: "2026-06-29T15:30:00",
    status: "pending_customer",
    validUntil: "2026-07-05",
    createdAt: "2026-06-29T09:15:00",
    updatedAt: "2026-06-29T15:30:00",
    revisions: [
      {
        id: "rev1",
        at: "2026-06-29T09:15:00",
        by: "customer",
        action: "Создана заявка из конструктора",
        comment: "Оценка: 3500₽",
      },
      {
        id: "rev2",
        at: "2026-06-29T15:30:00",
        by: "confectioner",
        action: "Отправлено предложение",
        oldTotal: 3500,
        newTotal: 4350,
        comment: "Добавлена сахарная машинка (+600₽) и надпись (+200₽)",
      },
    ],
  },
  {
    id: "neg2",
    inquiryId: "ci2",
    customerId: "u10",
    customerName: "Дмитрий Петров",
    customerAvatar: "https://i.pravatar.cc/150?img=51",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    originalRequest: {
      eventType: "wedding",
      base: "sponge",
      filling: "Шоколадный ганаш",
      coating: "Сахарная мастика",
      decorations: ["Сахарные цветы", "Сусальное золото"],
      servings: 40,
      city: "Тула",
      deliveryDate: "2026-07-20",
      deliveryType: "delivery",
      comment: "Свадебный торт, 3 яруса",
      estimatedPrice: 15000,
    },
    quotedItems: [
      {
        name: "Свадебный торт 3 яруса (40 порций)",
        description: "Нижний ярус — бисквит + шоколадный ганаш, средний — красный бархат, верхний — мусс с малиной. Покрытие — белая мастика.",
        quantity: 1,
        unitPrice: 18000,
        totalPrice: 18000,
        category: "cake",
      },
      {
        name: "Сахарные цветы (5 шт, ручная работа)",
        description: "Розы и пионы бело-розовые, пищевая краска",
        quantity: 5,
        unitPrice: 500,
        totalPrice: 2500,
        category: "decoration",
      },
      {
        name: "Сусальное золото (декор)",
        description: "Пищевое золото 23 карата, декор нижнего яруса",
        quantity: 1,
        unitPrice: 800,
        totalPrice: 800,
        category: "decoration",
      },
      {
        name: "Доставка + монтаж на площадке",
        description: "Тула, доставка + сборка 3-ярусного торта на месте, 20 июля",
        quantity: 1,
        unitPrice: 1500,
        totalPrice: 1500,
        category: "delivery",
      },
    ],
    quotedTotal: 22800,
    quotedComment:
      "Для 3-ярусного свадебного торта на 40 порций цена 22 800₽. Каждый ярус — разный вкус. Сахарные цветы ручной работы (5 шт). Доставка + монтаж на площадке — 1500₽. Готовлю 3 дня. Срок: готов к 20 июля. Предложение действительно до 15 июля.",
    quotedDeliveryCost: 1500,
    quotedPrepTime: "3 дня",
    quotedAt: "2026-06-28T17:00:00",
    status: "approved",
    customerResponse: "approved",
    customerRespondedAt: "2026-06-29T10:00:00",
    validUntil: "2026-07-15",
    createdAt: "2026-06-28T14:30:00",
    updatedAt: "2026-06-29T10:00:00",
    revisions: [
      {
        id: "rev3",
        at: "2026-06-28T14:30:00",
        by: "customer",
        action: "Создана заявка из конструктора",
        comment: "Оценка: 15000₽, 3 яруса",
      },
      {
        id: "rev4",
        at: "2026-06-28T17:00:00",
        by: "confectioner",
        action: "Отправлено предложение",
        oldTotal: 15000,
        newTotal: 22800,
        comment: "3 разных вкуса + сахарные цветы + золото + монтаж",
      },
      {
        id: "rev5",
        at: "2026-06-29T10:00:00",
        by: "customer",
        action: "Одобрено покупателем",
        comment: "Всё нравится, оплачиваю!",
      },
    ],
  },
  {
    id: "neg3",
    inquiryId: "ci_new1",
    customerId: "u_new1",
    customerName: "Екатерина Смирнова",
    customerAvatar: "https://i.pravatar.cc/150?img=44",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    originalRequest: {
      eventType: "birthday",
      base: "mousse",
      filling: "Манго-маракуйя",
      coating: "Зеркальная глазурь",
      decorations: ["Съедобный декор"],
      servings: 8,
      city: "Тула",
      deliveryDate: "2026-07-05",
      deliveryType: "pickup",
      inscription: "С Юбилеем!",
      comment: "Хочу яркий торт, необычный",
      estimatedPrice: 4500,
    },
    quotedItems: [],
    quotedTotal: 0,
    quotedDeliveryCost: 0,
    quotedPrepTime: "",
    status: "pending_confectioner",
    createdAt: "2026-06-30T08:00:00",
    updatedAt: "2026-06-30T08:00:00",
    revisions: [
      {
        id: "rev6",
        at: "2026-06-30T08:00:00",
        by: "customer",
        action: "Создана заявка из конструктора",
        comment: "Оценка: 4500₽, муссовый, 8 порций",
      },
    ],
  },
  {
    id: "neg4",
    inquiryId: "ci_new2",
    customerId: "u_new2",
    customerName: "Андрей Соколов",
    customerAvatar: "https://i.pravatar.cc/150?img=12",
    confectionerId: "c1",
    confectionerName: "Сладкая уездная",
    confectionerAvatar: "https://i.pravatar.cc/150?img=32",
    originalRequest: {
      eventType: "corporate",
      base: "sponge",
      filling: "Варёная сгущёнка",
      coating: "Крем-чиз",
      decorations: ["Шоколадная крошка"],
      servings: 30,
      city: "Тула",
      deliveryDate: "2026-07-08",
      deliveryType: "delivery",
      comment: "Корпоратив, нужен торт с логотипом компании",
      estimatedPrice: 6000,
    },
    quotedItems: [
      {
        name: "Торт корпоративный (30 порций)",
        description: "Бисквит + сгущёнка, крем-чиз, 2 яруса",
        quantity: 1,
        unitPrice: 5400,
        totalPrice: 5400,
        category: "cake",
      },
      {
        name: "Логотип компании (сахарная печать)",
        description: "Пищевая печать логотипа на вафельной бумаге, диаметр 20 см",
        quantity: 1,
        unitPrice: 500,
        totalPrice: 500,
        category: "decoration",
      },
      {
        name: "Доставка по Туле",
        description: "8 июля, 14:00",
        quantity: 1,
        unitPrice: 0,
        totalPrice: 0,
        category: "delivery",
      },
    ],
    quotedTotal: 5900,
    quotedComment:
      "Логотип сделаю на пищевой принтере (вафельная бумага). Доставка по Туле — бесплатно при заказе от 5000₽. Торт будет готов 8 июля к 14:00.",
    quotedDeliveryCost: 0,
    quotedPrepTime: "2 дня",
    quotedAt: "2026-06-29T12:00:00",
    status: "rejected",
    customerResponse: "rejected",
    customerComment: "Спасибо, но нашёл дешевле у другого кондитера. Отменяю.",
    customerRespondedAt: "2026-06-30T09:00:00",
    validUntil: "2026-07-05",
    createdAt: "2026-06-29T10:00:00",
    updatedAt: "2026-06-30T09:00:00",
    revisions: [
      {
        id: "rev7",
        at: "2026-06-29T10:00:00",
        by: "customer",
        action: "Создана заявка",
        comment: "Оценка: 6000₽",
      },
      {
        id: "rev8",
        at: "2026-06-29T12:00:00",
        by: "confectioner",
        action: "Отправлено предложение",
        oldTotal: 6000,
        newTotal: 5900,
        comment: "Логотип + бесплатная доставка",
      },
      {
        id: "rev9",
        at: "2026-06-30T09:00:00",
        by: "customer",
        action: "Отклонено покупателем",
        comment: "Нашёл дешевле",
      },
    ],
  },
];
